In [207]:
import pandas as pd
import numpy as np

from utilities.preprocessors import preprocess, assign_gender, series_to_1D_array, map_value_to_index
from utilities.visualizers import view_rows
from utilities.loaders import load_file
from models.fil_lstm_glove import load_lstm_model

import os
import re

from dotenv import load_dotenv
from pathlib import Path

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Load dataframe

In [208]:
conn_info = pd.read_csv('../documents/conn_info.csv', index_col=0)
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,male,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,male,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,male,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,male,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,male,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,transcosmos Asia Philippines Inc. · Full-time,https://www.linkedin.com/in/jamie-rose-cleofas...,Jamie Rose Cleofas,NaN,NaN
1066,jovitfrias@gmail.com,0,RCM Health Care Services · Full-time,https://www.linkedin.com/in/jovit-frias-06a561...,Jovit Frias,NaN,NaN
1067,danlopezatwork@gmail.com,0,Abacus Service Corporation · Full-time,https://www.linkedin.com/in/danlopezprofessional/,Mark Daniel Lopez,NaN,NaN
1068,dmrc_06@yahoo.com,09983696222 (Mobile),RingCentral · Full-time,https://www.linkedin.com/in/daena-michaela-roy...,Daena Michaela Ceria,NaN,NaN
1069,reyes.joanamace10@gmail.com,09672 182668 (Mobile),iQor Philippines,https://www.linkedin.com/in/joana-mace-reyes-b...,Joana Mace Reyes,NaN,NaN

In [209]:
conn_info['gender'].unique()

array(['male', 'female', nan], dtype=object)

In [210]:
# what I want to do is if there are names that have more than 1 first name e.g.
# Jherick and Sid, we want to train a classifier that classifies these individual
# names and output its probability and then average these two probabilities to get
# the final probability of whether it is male or female name
# i.e. Jherick has prob 0.75732 of being positive label Sid has prob of 0.6343 of
# being a positive label the average of this would be 0.69581 which would be a postive
# label, wee can assign the positive label 1 to a male label and the negative label 0
# would be female
conn_info['conn_name'].apply(lambda name: name.split() if not pd.isna(name) else name)

0                    [Marcus, Paulino]
1            [Jherick, Sid, Celestial]
2       [Evan, Jake, Soriano, Montano]
3                   [Reggielee, Capio]
4                 [John, Carlo, Tadeo]
                     ...
1065            [Jamie, Rose, Cleofas]
1066                    [Jovit, Frias]
1067             [Mark, Daniel, Lopez]
1068          [Daena, Michaela, Ceria]
1069              [Joana, Mace, Reyes]
Name: conn_name, Length: 1070, dtype: object

# Loading libraries for gender classifier

In [211]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow import one_hot

# Loading dataset for gender classifier

In [212]:
name_gender_df = pd.read_csv('./data/name_gender_dataset.csv')
name_gender_df

           Name Gender    Count   Probability
0         James      M  5304407  1.451679e-02
1          John      M  5260831  1.439753e-02
2        Robert      M  4970386  1.360266e-02
3       Michael      M  4579950  1.253414e-02
4       William      M  4226608  1.156713e-02
...         ...    ...      ...           ...
147264   Zylenn      M        1  2.736740e-09
147265   Zymeon      M        1  2.736740e-09
147266   Zyndel      M        1  2.736740e-09
147267   Zyshan      M        1  2.736740e-09
147268    Zyton      M        1  2.736740e-09

[147269 rows x 4 columns]

In [213]:
name_gender_df['Gender'].value_counts()

Gender
F    89749
M    57520
Name: count, dtype: int64

#### 0 for male 1 for female

In [214]:
name_gender_df['Gender'] = name_gender_df['Gender'].apply(lambda label: 0 if label == 'M' else 1)
name_gender_df['Gender'].value_counts()

Gender
1    89749
0    57520
Name: count, dtype: int64

In [215]:
name_gender_df["Name"] = name_gender_df["Name"].apply(lambda name: name.lower())
name_gender_df

           Name  Gender    Count   Probability
0         james       0  5304407  1.451679e-02
1          john       0  5260831  1.439753e-02
2        robert       0  4970386  1.360266e-02
3       michael       0  4579950  1.253414e-02
4       william       0  4226608  1.156713e-02
...         ...     ...      ...           ...
147264   zylenn       0        1  2.736740e-09
147265   zymeon       0        1  2.736740e-09
147266   zyndel       0        1  2.736740e-09
147267   zyshan       0        1  2.736740e-09
147268    zyton       0        1  2.736740e-09

[147269 rows x 4 columns]

In [216]:
def helper(row):
    # splits the name into smaller chunks if the name
    # is more than 1
    
    name = row["Name"]
    gender = row["Gender"]

    new_name = re.sub(r'[^0-9A-Za-z]', " ", name)
    split_name = new_name.split(' ')
    if len(split_name) > 1:
        return [(name_chunk, gender) for name_chunk in split_name]
    
    return [(name, gender)]

In [217]:
name_gender_exp = name_gender_df.apply(helper, axis=1).to_list()
name_gender_exp

[[('james', 0)],
 [('john', 0)],
 [('robert', 0)],
 [('michael', 0)],
 [('william', 0)],
 [('mary', 1)],
 [('david', 0)],
 [('joseph', 0)],
 [('richard', 0)],
 [('charles', 0)],
 [('thomas', 0)],
 [('christopher', 0)],
 [('daniel', 0)],
 [('matthew', 0)],
 [('elizabeth', 1)],
 [('patricia', 1)],
 [('jennifer', 1)],
 [('anthony', 0)],
 [('george', 0)],
 [('linda', 1)],
 [('barbara', 1)],
 [('donald', 0)],
 [('paul', 0)],
 [('mark', 0)],
 [('andrew', 0)],
 [('steven', 0)],
 [('kenneth', 0)],
 [('edward', 0)],
 [('joshua', 0)],
 [('margaret', 1)],
 [('brian', 0)],
 [('kevin', 0)],
 [('jessica', 1)],
 [('sarah', 1)],
 [('susan', 1)],
 [('timothy', 0)],
 [('dorothy', 1)],
 [('jason', 0)],
 [('ronald', 0)],
 [('helen', 1)],
 [('ryan', 0)],
 [('jeffrey', 0)],
 [('karen', 1)],
 [('nancy', 1)],
 [('betty', 1)],
 [('lisa', 1)],
 [('jacob', 0)],
 [('nicholas', 0)],
 [('ashley', 1)],
 [('eric', 0)],
 [('frank', 0)],
 [('gary', 0)],
 [('anna', 1)],
 [('stephen', 0)],
 [('jonathan', 0)],
 [('sandra', 1)],
 [('emily', 1)],
 [('amanda', 1)],
 [('kimberly', 1)],
 [('michelle', 1)],
 [('donna', 1)],
 [('justin', 0)],
 [('laura', 1)],
 [('ruth', 1)],
 [('carol', 1)],
 [('brandon', 0)],
 [('larry', 0)],
 [('scott', 0)],
 [('melissa', 1)],
 [('stephanie', 1)],
 [('benjamin', 0)],
 [('raymond', 0)],
 [('samuel', 0)],
 [('rebecca', 1)],
 [('deborah', 1)],
 [('gregory', 0)],
 [('sharon', 1)],
 [('kathleen', 1)],
 [('amy', 1)],
 [('cynthia', 1)],
 [('alexander', 0)],
 [('patrick', 0)],
 [('jack', 0)],
 [('henry', 0)],
 [('angela', 1)],
 [('shirley', 1)],
 [('emma', 1)],
 [('catherine', 1)],
 [('katherine', 1)],
 [('virginia', 1)],
 [('nicole', 1)],
 [('dennis', 0)],
 [('walter', 0)],
 [('tyler', 0)],
 [('peter', 0)],
 [('brenda', 1)],
 [('aaron', 0)],
 [('jerry', 0)],
 [('christine', 1)],
 [('samantha', 1)],
 [('adam', 0)],
 [('rachel', 1)],
 [('pamela', 1)],
 [('frances', 1)],
 [('nathan', 0)],
 [('douglas', 0)],
 [('heather', 1)],
 [('evelyn', 1)],
 [('jose', 0)],
 [('alice', 1)],
 [('janet', 1)],
 [('maria', 1)],
 [('zachary', 0)],
 [('carolyn', 1)],
 [('debra', 1)],
 [('harold', 0)],
 [('martha', 1)],
 [('marie', 1)],
 [('arthur', 0)],
 [('julie', 1)],
 [('kyle', 0)],
 [('diane', 1)],
 [('christina', 1)],
 [('victoria', 1)],
 [('joyce', 1)],
 [('carl', 0)],
 [('lauren', 1)],
 [('grace', 1)],
 [('kelly', 1)],
 [('albert', 0)],
 [('rose', 1)],
 [('megan', 1)],
 [('joan', 1)],
 [('jeremy', 0)],
 [('ann', 1)],
 [('julia', 1)],
 [('kathryn', 1)],
 [('lawrence', 0)],
 [('olivia', 1)],
 [('judith', 1)],
 [('doris', 1)],
 [('jean', 1)],
 [('andrea', 1)],
 [('gerald', 0)],
 [('sean', 0)],
 [('joe', 0)],
 [('keith', 0)],
 [('sara', 1)],
 [('cheryl', 1)],
 [('hannah', 1)],
 [('mildred', 1)],
 [('willie', 0)],
 [('lillian', 1)],
 [('roger', 0)],
 [('jesse', 0)],
 [('jacqueline', 1)],
 [('ethan', 0)],
 [('terry', 0)],
 [('christian', 0)],
 [('harry', 0)],
 [('teresa', 1)],
 [('austin', 0)],
 [('gloria', 1)],
 [('ralph', 0)],
 [('janice', 1)],
 [('roy', 0)],
 [('theresa', 1)],
 [('amber', 1)],
 [('danielle', 1)],
 [('noah', 0)],
 [('bryan', 0)],
 [('jordan', 0)],
 [('louis', 0)],
 [('brittany', 1)],
 [('bruce', 0)],
 [('madison', 1)],
 [('judy', 1)],
 [('billy', 0)],
 [('dylan', 0)],
 [('denise', 1)],
 [('beverly', 1)],
 [('eugene', 0)],
 [('jane', 1)],
 [('marilyn', 1)],
 [('abigail', 1)],
 [('diana', 1)],
 [('charlotte', 1)],
 [('natalie', 1)],
 [('tiffany', 1)],
 [('wayne', 0)],
 [('russell', 0)],
 [('alan', 0)],
 [('crystal', 1)],
 [('sophia', 1)],
 [('irene', 1)],
 [('juan', 0)],
 [('ruby', 1)],
 [('gabriel', 0)],
 [('philip', 0)],
 [('annie', 1)],
 [('kayla', 1)],
 [('vincent', 0)],
 [('lori', 1)],
 [('howard', 0)],
 [('alexis', 1)],
 [('erin', 1)],
 [('fred', 0)],
 [('logan', 0)],
 [('isabella', 1)],
 [('tammy', 1)],
 [('louise', 1)],
 [('florence', 1)],
 [('randy', 0)],
 [('bradley', 0)],
 [('kathy', 1)],
 [('lois', 1)],
 [('anne', 1)],
 [('bonnie', 1)],
 [('victor', 0)],
 [('taylor', 1)],
 [('travis', 0)],
 [('phyllis', 1)],
 [('shawn', 0)],
 [('phillip', 0)],
 [('shannon', 1)],
 [('martin', 0)],
 [('johnny', 0)],
 [('craig', 0)],
 [('allison', 1)],
 [('bobby', 0)],
 [('alyssa', 1)],
 [('ella', 1)],
 [('josephine', 1)],
 [('ernest', 0)],
 [('stanley', 0)],
 [('cody', 0)],
 [('clarence', 0)],
 [('tina', 1)],
 [('elijah', 0)],
 [('leonard', 0)],
 [('carlos', 0)],
 [('dawn', 1)],
 [('robin', 1)],
 [('edna', 1)],
 [('cameron', 0)],
 [('peggy', 1)],
 [('caleb', 0)],
 [('eleanor', 1)],
 [('isaac', 0)],
 [('todd', 0)],
 [('jamie', 1)],
 [('earl', 0)],
 [('francis', 0)],
 [('jimmy', 0)],
 [('mason', 0)],
 [('danny', 0)],
 [('audrey', 1)],
 [('rita', 1)],
 [('luke', 0)],
 [('dale', 0)],
 [('alex', 0)],
 [('paula', 1)],
 [('clara', 1)],
 [('wanda', 1)],
 [('joel', 0)],
 [('evan', 0)],
 [('norma', 1)],
 [('luis', 0)],
 [('courtney', 1)],
 [('ethel', 1)],
 [('nathaniel', 0)],
 [('wendy', 1)],
 [('ellen', 1)],
 [('leslie', 1)],
 [('marjorie', 1)],
 [('vanessa', 1)],
 [('allen', 0)],
 [('valerie', 1)],
 [('carrie', 1)],
 [('ava', 1)],
 [('eva', 1)],
 [('frederick', 0)],
 [('curtis', 0)],
 [('edith', 1)],
 [('connie', 1)],
 [('lucas', 0)],
 [('gladys', 1)],
 [('cindy', 1)],
 [('tracy', 1)],
 [('elaine', 1)],
 [('hazel', 1)],
 [('monica', 1)],
 [('norman', 0)],
 [('esther', 1)],
 [('melanie', 1)],
 [('brianna', 1)],
 [('antonio', 0)],
 [('jasmine', 1)],
 [('chad', 0)],
 [('katie', 1)],
 [('tony', 0)],
 [('rodney', 0)],
 [('glenn', 0)],
 [('marvin', 0)],
 [('april', 1)],
 [('derek', 0)],
 [('erica', 1)],
 [('ian', 0)],
 [('adrian', 0)],
 [('theodore', 0)],
 [('alexandra', 1)],
 [('marcus', 0)],
 [('alfred', 0)],
 [('jackson', 0)],
 [('edwin', 0)],
 [('melvin', 0)],
 [('sylvia', 1)],
 [('sheila', 1)],
 [('alicia', 1)],
 [('steve', 0)],
 [('leah', 1)],
 [('hunter', 0)],
 [('lee', 0)],
 [('jeffery', 0)],
 [('kristen', 1)],
 [('caroline', 1)],
 [('mia', 1)],
 [('sherry', 1)],
 [('angel', 0)],
 [('jesus', 0)],
 [('dustin', 0)],
 [('herbert', 0)],
 [('pauline', 1)],
 [('michele', 1)],
 [('veronica', 1)],
 [('ricky', 0)],
 [('liam', 0)],
 [('wesley', 0)],
 [('thelma', 1)],
 [('suzanne', 1)],
 [('lucille', 1)],
 [('morgan', 1)],
 [('joanne', 1)],
 [('troy', 0)],
 [('chloe', 1)],
 [('anita', 1)],
 [('connor', 0)],
 [('isaiah', 0)],
 [('julian', 0)],
 [('jared', 0)],
 [('holly', 1)],
 [('lorraine', 1)],
 [('jayden', 0)],
 [('jill', 1)],
 [('geraldine', 1)],
 [('rhonda', 1)],
 [('dolores', 1)],
 [('eddie', 0)],
 [('vivian', 1)],
 [('darlene', 1)],
 [('aiden', 0)],
 [('calvin', 0)],
 [('shane', 0)],
 [('leo', 0)],
 [('juanita', 1)],
 [('sally', 1)],
 [('lucy', 1)],
 [('bertha', 1)],
 [('gail', 1)],
 [('oscar', 0)],
 [('mike', 0)],
 [('randall', 0)],
 [('ray', 0)],
 [('bernard', 0)],
 [('jeremiah', 0)],
 [('dana', 1)],
 [('brooke', 1)],
 [('leroy', 0)],
 [('amelia', 1)],
 [('corey', 0)],
 [('june', 1)],
 [('owen', 0)],
 [('claire', 1)],
 [('jay', 0)],
 [('kristin', 1)],
 [('beatrice', 1)],
 [('clifford', 0)],
 [('marion', 1)],
 [('renee', 1)],
 [('tara', 1)],
 [('madeline', 1)],
 [('barry', 0)],
 [('debbie', 1)],
 [('eileen', 1)],
 [('manuel', 0)],
 [('ida', 1)],
 [('lynn', 1)],
 [('blake', 0)],
 [('dean', 0)],
 [('kim', 1)],
 [('bernice', 1)],
 [('ronnie', 0)],
 [('warren', 0)],
 [('gavin', 0)],
 [('miguel', 0)],
 [('cassandra', 1)],
 [('regina', 1)],
 [('elsie', 1)],
 [('jo', 1)],
 [('tommy', 0)],
 [('trevor', 0)],
 [('stella', 1)],
 [('gertrude', 1)],
 [('loretta', 1)],
 [('rosa', 1)],
 [('sydney', 1)],
 [('oliver', 0)],
 [('chelsea', 1)],
 [('roberta', 1)],
 [('savannah', 1)],
 [('lindsey', 1)],
 [('brett', 0)],
 [('colleen', 1)],
 [('gordon', 0)],
 [('mitchell', 0)],
 [('charlie', 0)],
 [('dominic', 0)],
 [('jessie', 1)],
 [('annette', 1)],
 [('molly', 1)],
 [('cathy', 1)],
 [('stacy', 1)],
 [('laurie', 1)],
 [('lydia', 1)],
 [('jon', 0)],
 [('chase', 0)],
 [('leon', 0)],
 [('bessie', 1)],
 [('seth', 0)],
 [('kaitlyn', 1)],
 [('don', 0)],
 [('naomi', 1)],
 [('jeanette', 1)],
 [('hailey', 1)],
 [('jeanne', 1)],
 [('darrell', 0)],
 [('lloyd', 0)],
 [('carter', 0)],
 [('jerome', 0)],
 [('erik', 0)],
 [('alvin', 0)],
 [('beth', 1)],
 [('jenna', 1)],
 [('yvonne', 1)],
 [('rosemary', 1)],
 [('landon', 0)],
 [('bill', 0)],
 [('haley', 1)],
 [('alma', 1)],
 [('wyatt', 0)],
 [('micheal', 0)],
 [('agnes', 1)],
 [('gina', 1)],
 [('minnie', 1)],
 [('sebastian', 0)],
 [('devin', 0)],
 [('georgia', 1)],
 [('stacey', 1)],
 [('pearl', 1)],
 [('vicki', 1)],
 [('joann', 1)],
 [('max', 0)],
 [('kelsey', 1)],
 [('lillie', 1)],
 [('levi', 0)],
 [('lily', 1)],
 [('floyd', 0)],
 [('carla', 1)],
 [('edgar', 0)],
 [('lewis', 0)],
 [('jim', 0)],
 [('nora', 1)],
 [('maureen', 1)],
 [('brent', 0)],
 [('heidi', 1)],
 [('derrick', 0)],
 [('mario', 0)],
 [('nellie', 1)],
 [('lindsay', 1)],
 [('kristina', 1)],
 [('shelby', 1)],
 [('terri', 1)],
 [('destiny', 1)],
 [('vernon', 0)],
 [('paige', 1)],
 [('chris', 0)],
 [('marc', 0)],
 [('violet', 1)],
 [('willie', 1)],
 [('arlene', 1)],
 [('sue', 1)],
 [('cole', 0)],
 [('daisy', 1)],
 [('sabrina', 1)],
 [('ricardo', 0)],
 [('carmen', 1)],
 [('clyde', 0)],
 [('marian', 1)],
 [('vera', 1)],
 [('constance', 1)],
 [('deanna', 1)],
 [('wilma', 1)],
 [('colin', 0)],
 [('melinda', 1)],
 [('tom', 0)],
 [('lena', 1)],
 [('tamara', 1)],
 [('joy', 1)],
 [('faith', 1)],
 [('clayton', 0)],
 [('maurice', 0)],
 [('gabrielle', 1)],
 [('cory', 0)],
 [('franklin', 0)],
 [('ivan', 0)],
 [('xavier', 0)],
 [('charlene', 1)],
 [('katelyn', 1)],
 [('francisco', 0)],
 [('sofia', 1)],
 [('garrett', 0)],
 [('myrtle', 1)],
 [('cora', 1)],
 [('jordan', 1)],
 [('alejandro', 0)],
 [('herman', 0)],
 [('mabel', 1)],
 [('jorge', 0)],
 [('marcia', 1)],
 [('grant', 0)],
 [('marlene', 1)],
 [('erika', 1)],
 [('zoe', 1)],
 [('mackenzie', 1)],
 [('glen', 0)],
 [('viola', 1)],
 [('gilbert', 0)],
 [('jake', 0)],
 [('mattie', 1)],
 [('nina', 1)],
 [('claudia', 1)],
 [('lester', 0)],
 [('kaylee', 1)],
 [('avery', 1)],
 [('elmer', 0)],
 [('tanya', 1)],
 [('andre', 0)],
 [('alexa', 1)],
 [('jennie', 1)],
 [('autumn', 1)],
 [('sadie', 1)],
 [('gene', 0)],
 [('sam', 0)],
 [('marissa', 1)],
 [('colton', 0)],
 [('spencer', 0)],
 [('eli', 0)],
 [('alison', 1)],
 [('caitlin', 1)],
 [('harvey', 0)],
 [('tonya', 1)],
 [('priscilla', 1)],
 [('addison', 1)],
 [('isabel', 1)],
 [('angelina', 1)],
 [('brayden', 0)],
 [('sophie', 1)],
 [('chester', 0)],
 [('jeff', 0)],
 [('gwendolyn', 1)],
 [('casey', 0)],
 [('bryce', 0)],
 [('patsy', 1)],
 [('tristan', 0)],
 [('gabriella', 1)],
 [('taylor', 0)],
 [('leslie', 0)],
 [('maggie', 1)],
 [('miranda', 1)],
 [('darren', 0)],
 [('delores', 1)],
 [('milton', 0)],
 [('duane', 0)],
 [('preston', 0)],
 [('kylie', 1)],
 [('reginald', 0)],
 [('genevieve', 1)],
 [('ruben', 0)],
 [('aidan', 0)],
 [('brandy', 1)],
 [('yolanda', 1)],
 [('maxine', 1)],
 [('aubrey', 1)],
 [('jessie', 0)],
 [('roberto', 0)],
 [('carole', 1)],
 [('jimmie', 0)],
 [('joanna', 1)],
 [('neil', 0)],
 [('miriam', 1)],
 [('natasha', 1)],
 [('carson', 0)],
 [('katrina', 1)],
 [('leona', 1)],
 [('glenda', 1)],
 [('lance', 0)],
 [('mae', 1)],
 [('mariah', 1)],
 [('vickie', 1)],
 [('brandi', 1)],
 [('whitney', 1)],
 [('jocelyn', 1)],
 [('josiah', 0)],
 [('everett', 0)],
 [('riley', 1)],
 [('diego', 0)],
 [('parker', 0)],
 [('cecil', 0)],
 [('kara', 1)],
 [('dan', 0)],
 [('meghan', 1)],
 [('dora', 1)],
 [('brooklyn', 1)],
 [('margie', 1)],
 [('allan', 0)],
 [('bethany', 1)],
 [('eduardo', 0)],
 [('ana', 1)],
 [('hector', 0)],
 [('arnold', 0)],
 [('marsha', 1)],
 [('karl', 0)],
 [('nolan', 0)],
 [('makayla', 1)],
 [('hayden', 0)],
 [('toni', 1)],
 [('riley', 0)],
 [('christy', 1)],
 [('clinton', 0)],
 [('billie', 1)],
 [('johnnie', 0)],
 [('dianne', 1)],
 [('ariana', 1)],
 [('kendra', 1)],
 [('alexandria', 1)],
 [('sierra', 1)],
 [('bailey', 1)],
 [('javier', 0)],
 [('penny', 1)],
 [('maya', 1)],
 [('melody', 1)],
 [('angel', 1)],
 [('roland', 0)],
 [('omar', 0)],
 [('hattie', 1)],
 [('johnathan', 0)],
 [('kay', 1)],
 [('cecilia', 1)],
 [('fernando', 0)],
 [('terry', 1)],
 [('darryl', 0)],
 [('brendan', 0)],
 [('felicia', 1)],
 [('maxwell', 0)],
 [('jenny', 1)],
 [('micah', 0)],
 [('isabelle', 1)],
 [('ada', 1)],
 [('briana', 1)],
 [('tanner', 0)],
 [('marguerite', 1)],
 [('jamie', 0)],
 [('lonnie', 0)],
 [('angelica', 1)],
 [('marshall', 0)],
 [('bridget', 1)],
 [('tracey', 1)],
 [('bob', 0)],
 [('abraham', 0)],
 [('arianna', 1)],
 [('madelyn', 1)],
 [('adriana', 1)],
 [('andy', 0)],
 [('brady', 0)],
 [('guy', 0)],
 [('nicolas', 0)],
 [('jackie', 1)],
 [('candace', 1)],
 [('hope', 1)],
 [('karla', 1)],
 [('claude', 0)],
 [('pedro', 0)],
 [('jillian', 1)],
 [('brittney', 1)],
 [('rachael', 1)],
 [('damian', 0)],
 [('lola', 1)],
 [('ross', 0)],
 [('kate', 1)],
 [('layla', 1)],
 [('jade', 1)],
 [('harriet', 1)],
 [('bobbie', 1)],
 [('misty', 1)],
 [('cooper', 0)],
 [('kurt', 0)],
 [('kristine', 1)],
 [('aaliyah', 1)],
 [('geneva', 1)],
 [('desiree', 1)],
 [('dakota', 0)],
 [('shelly', 1)],
 [('becky', 1)],
 [('jacquelyn', 1)],
 [('kelly', 0)],
 [('blanche', 1)],
 [('velma', 1)],
 [('krystal', 1)],
 [('raul', 0)],
 [('brad', 0)],
 [('ben', 0)],
 [('sherri', 1)],
 [('andres', 0)],
 [('susie', 1)],
 [('fannie', 1)],
 [('sidney', 0)],
 [('zoey', 1)],
 [('miles', 0)],
 [('breanna', 1)],
 [('monique', 1)],
 [('hugh', 0)],
 [('lula', 1)],
 [('iris', 1)],
 [('mathew', 0)],
 [('byron', 0)],
 [('jodi', 1)],
 [('casey', 1)],
 [('tim', 0)],
 [('elias', 0)],
 [('rick', 0)],
 [('wallace', 0)],
 [('harper', 1)],
 [('summer', 1)],
 [('grayson', 0)],
 [('dalton', 0)],
 [('lynda', 1)],
 [('harrison', 0)],
 [('krista', 1)],
 [('hilda', 1)],
 [('tyrone', 0)],
 [('jaxon', 0)],
 [('rafael', 0)],
 [('gabriela', 1)],
 [('nevaeh', 1)],
 [('sheryl', 1)],
 [('drew', 0)],
 [('kristi', 1)],
 [('rosie', 1)],
 [('elena', 1)],
 [('angelo', 0)],
 [('eunice', 1)],
 [('shelley', 1)],
 [('nelson', 0)],
 [('antoinette', 1)],
 [('dwayne', 0)],
 [('dwight', 0)],
 [('kelli', 1)],
 [('julius', 0)],
 [('jackie', 0)],
 [('trinity', 1)],
 [('shaun', 0)],
 [('meredith', 1)],
 [('kaleb', 0)],
 [('sergio', 0)],
 [('collin', 0)],
 [('rebekah', 1)],
 [('greg', 0)],
 [('emmanuel', 0)],
 [('mamie', 1)],
 [('willard', 0)],
 [('ramon', 0)],
 [('perry', 0)],
 [('bianca', 1)],
 [('kristy', 1)],
 [('candice', 1)],
 [('jaden', 0)],
 [('belinda', 1)],
 [('gracie', 1)],
 [('devon', 0)],
 [('ted', 0)],
 [('terrence', 0)],
 [('janie', 1)],
 [('stuart', 0)],
 [('armando', 0)],
 [('rosalie', 1)],
 [('marco', 0)],
 [('cesar', 0)],
 [('ayden', 0)],
 [('ashton', 0)],
 [('irma', 1)],
 [('peyton', 1)],
 [('wade', 0)],
 [('terrance', 0)],
 [('erick', 0)],
 [('freddie', 0)],
 [('beulah', 1)],
 [('felix', 0)],
 [('kennedy', 1)],
 [('marion', 0)],
 [('ariel', 1)],
 [('brody', 0)],
 [('virgil', 0)],
 [('adrienne', 1)],
 [('roman', 0)],
 [('morris', 0)],
 [('robyn', 1)],
 [('clifton', 0)],
 [('kent', 0)],
 [('jonathon', 0)],
 [('jaime', 0)],
 [('kirk', 0)],
 [('sandy', 1)],
 [('jeannette', 1)],
 [('alberta', 1)],
 [('elise', 1)],
 [('verna', 1)],
 [('giovanni', 0)],
 [('camila', 1)],
 [('simon', 0)],
 [('carly', 1)],
 [('faye', 1)],
 [('sonia', 1)],
 [('camille', 1)],
 [('opal', 1)],
 [('nichole', 1)],
 [('ramona', 1)],
 [('cheyenne', 1)],
 [('scarlett', 1)],
 [('flora', 1)],
 [('sonya', 1)],
 [('jace', 0)],
 [('della', 1)],
 [('leonardo', 0)],
 [('penelope', 1)],
 [('lorenzo', 0)],
 [('genesis', 1)],
 [('jonah', 0)],
 [('daryl', 0)],
 [('lila', 1)],
 [('kristopher', 0)],
 [('natalia', 1)],
 [('malcolm', 0)],
 [('gianna', 1)],
 [('inez', 1)],
 [('skylar', 1)],
 [('valeria', 1)],
 [('marianne', 1)],
 [('damon', 0)],
 [('lincoln', 0)],
 [('luther', 0)],
 [('ellie', 1)],
 [('guadalupe', 1)],
 [('fredrick', 0)],
 [('jada', 1)],
 [('yvette', 1)],
 [('dillon', 0)],
 [('dallas', 0)],
 [('alexis', 0)],
 [('marcella', 1)],
 [('geoffrey', 0)],
 [('dave', 0)],
 [('hudson', 0)],
 [('dominick', 0)],
 [('bryson', 0)],
 [('angie', 1)],
 [('lynne', 1)],
 [('lee', 1)],
 [('kari', 1)],
 [('bella', 1)],
 [('cristian', 0)],
 [('maryann', 1)],
 [('gayle', 1)],
 [('tabitha', 1)],
 [('sheri', 1)],
 [('patty', 1)],
 [('olga', 1)],
 [('rickey', 0)],
 [('israel', 0)],
 [('alisha', 1)],
 [('alberto', 0)],
 [('santiago', 0)],
 [('tracy', 0)],
 [('julio', 0)],
 [('kaden', 0)],
 [('abby', 1)],
 [('alana', 1)],
 [('daniela', 1)],
 [('kaitlin', 1)],
 [('myra', 1)],
 [('roxanne', 1)],
 [('caden', 0)],
 [('damien', 0)],
 [('annabelle', 1)],
 [('karina', 1)],
 [('donnie', 0)],
 [('kendall', 1)],
 [('homer', 0)],
 [('lyle', 0)],
 [('mallory', 1)],
 [('callie', 1)],
 [('juliana', 1)],
 [('josie', 1)],
 [('celeste', 1)],
 [('mckenzie', 1)],
 [('adeline', 1)],
 [('cassidy', 1)],
 [('gerard', 0)],
 [('aurora', 1)],
 [('rex', 0)],
 [('enrique', 0)],
 [('otis', 0)],
 [('lilly', 1)],
 [('gage', 0)],
 [('jody', 1)],
 [('earnest', 0)],
 [('donovan', 0)],
 [('janelle', 1)],
 [('serenity', 1)],
 [('trenton', 0)],
 [('aimee', 1)],
 [('kirsten', 1)],
 [('asher', 0)],
 [('hubert', 0)],
 [('dianna', 1)],
 [('avery', 0)],
 [('cecelia', 1)],
 [('dominique', 1)],
 [('mya', 1)],
 [('emmett', 0)],
 [('olive', 1)],
 [('wilbur', 0)],
 [('lacey', 1)],
 [('liliana', 1)],
 [('mateo', 0)],
 [('salvatore', 0)],
 [('cara', 1)],
 [('muriel', 1)],
 [('alfredo', 0)],
 [('neal', 0)],
 [('mikayla', 1)],
 [('eliza', 1)],
 [('hayley', 1)],
 [('nadine', 1)],
 [('bernadette', 1)],
 [('celia', 1)],
 [('arturo', 0)],
 [('cristina', 1)],
 [('jan', 1)],
 [('jordyn', 1)],
 [('lana', 1)],
 [('erma', 1)],
 [('dana', 0)],
 [('jaclyn', 1)],
 [('vicky', 1)],
 [('caitlyn', 1)],
 [('alec', 0)],
 [('gretchen', 1)],
 [('leland', 0)],
 [('johanna', 1)],
 [('horace', 0)],
 [('shannon', 0)],
 [('jaime', 1)],
 [('colby', 0)],
 [('joey', 0)],
 [('abel', 0)],
 [('traci', 1)],
 [('kellie', 1)],
 [('estelle', 1)],
 [('kerry', 1)],
 [('ira', 0)],
 [('conner', 0)],
 [('payton', 1)],
 [('wendell', 0)],
 [('ezra', 0)],
 [('trent', 0)],
 [('eloise', 1)],
 [('rudolph', 0)],
 [('aria', 1)],
 [('ivy', 1)],
 [('graham', 0)],
 ...]

In [218]:
name_gender_exp_flat = series_to_1D_array(name_gender_exp)
name_gender_exp_flat

[('james', 0),
 ('john', 0),
 ('robert', 0),
 ('michael', 0),
 ('william', 0),
 ('mary', 1),
 ('david', 0),
 ('joseph', 0),
 ('richard', 0),
 ('charles', 0),
 ('thomas', 0),
 ('christopher', 0),
 ('daniel', 0),
 ('matthew', 0),
 ('elizabeth', 1),
 ('patricia', 1),
 ('jennifer', 1),
 ('anthony', 0),
 ('george', 0),
 ('linda', 1),
 ('barbara', 1),
 ('donald', 0),
 ('paul', 0),
 ('mark', 0),
 ('andrew', 0),
 ('steven', 0),
 ('kenneth', 0),
 ('edward', 0),
 ('joshua', 0),
 ('margaret', 1),
 ('brian', 0),
 ('kevin', 0),
 ('jessica', 1),
 ('sarah', 1),
 ('susan', 1),
 ('timothy', 0),
 ('dorothy', 1),
 ('jason', 0),
 ('ronald', 0),
 ('helen', 1),
 ('ryan', 0),
 ('jeffrey', 0),
 ('karen', 1),
 ('nancy', 1),
 ('betty', 1),
 ('lisa', 1),
 ('jacob', 0),
 ('nicholas', 0),
 ('ashley', 1),
 ('eric', 0),
 ('frank', 0),
 ('gary', 0),
 ('anna', 1),
 ('stephen', 0),
 ('jonathan', 0),
 ('sandra', 1),
 ('emily', 1),
 ('amanda', 1),
 ('kimberly', 1),
 ('michelle', 1),
 ('donna', 1),
 ('justin', 0),
 ('laura', 1),
 ('ruth', 1),
 ('carol', 1),
 ('brandon', 0),
 ('larry', 0),
 ('scott', 0),
 ('melissa', 1),
 ('stephanie', 1),
 ('benjamin', 0),
 ('raymond', 0),
 ('samuel', 0),
 ('rebecca', 1),
 ('deborah', 1),
 ('gregory', 0),
 ('sharon', 1),
 ('kathleen', 1),
 ('amy', 1),
 ('cynthia', 1),
 ('alexander', 0),
 ('patrick', 0),
 ('jack', 0),
 ('henry', 0),
 ('angela', 1),
 ('shirley', 1),
 ('emma', 1),
 ('catherine', 1),
 ('katherine', 1),
 ('virginia', 1),
 ('nicole', 1),
 ('dennis', 0),
 ('walter', 0),
 ('tyler', 0),
 ('peter', 0),
 ('brenda', 1),
 ('aaron', 0),
 ('jerry', 0),
 ('christine', 1),
 ('samantha', 1),
 ('adam', 0),
 ('rachel', 1),
 ('pamela', 1),
 ('frances', 1),
 ('nathan', 0),
 ('douglas', 0),
 ('heather', 1),
 ('evelyn', 1),
 ('jose', 0),
 ('alice', 1),
 ('janet', 1),
 ('maria', 1),
 ('zachary', 0),
 ('carolyn', 1),
 ('debra', 1),
 ('harold', 0),
 ('martha', 1),
 ('marie', 1),
 ('arthur', 0),
 ('julie', 1),
 ('kyle', 0),
 ('diane', 1),
 ('christina', 1),
 ('victoria', 1),
 ('joyce', 1),
 ('carl', 0),
 ('lauren', 1),
 ('grace', 1),
 ('kelly', 1),
 ('albert', 0),
 ('rose', 1),
 ('megan', 1),
 ('joan', 1),
 ('jeremy', 0),
 ('ann', 1),
 ('julia', 1),
 ('kathryn', 1),
 ('lawrence', 0),
 ('olivia', 1),
 ('judith', 1),
 ('doris', 1),
 ('jean', 1),
 ('andrea', 1),
 ('gerald', 0),
 ('sean', 0),
 ('joe', 0),
 ('keith', 0),
 ('sara', 1),
 ('cheryl', 1),
 ('hannah', 1),
 ('mildred', 1),
 ('willie', 0),
 ('lillian', 1),
 ('roger', 0),
 ('jesse', 0),
 ('jacqueline', 1),
 ('ethan', 0),
 ('terry', 0),
 ('christian', 0),
 ('harry', 0),
 ('teresa', 1),
 ('austin', 0),
 ('gloria', 1),
 ('ralph', 0),
 ('janice', 1),
 ('roy', 0),
 ('theresa', 1),
 ('amber', 1),
 ('danielle', 1),
 ('noah', 0),
 ('bryan', 0),
 ('jordan', 0),
 ('louis', 0),
 ('brittany', 1),
 ('bruce', 0),
 ('madison', 1),
 ('judy', 1),
 ('billy', 0),
 ('dylan', 0),
 ('denise', 1),
 ('beverly', 1),
 ('eugene', 0),
 ('jane', 1),
 ('marilyn', 1),
 ('abigail', 1),
 ('diana', 1),
 ('charlotte', 1),
 ('natalie', 1),
 ('tiffany', 1),
 ('wayne', 0),
 ('russell', 0),
 ('alan', 0),
 ('crystal', 1),
 ('sophia', 1),
 ('irene', 1),
 ('juan', 0),
 ('ruby', 1),
 ('gabriel', 0),
 ('philip', 0),
 ('annie', 1),
 ('kayla', 1),
 ('vincent', 0),
 ('lori', 1),
 ('howard', 0),
 ('alexis', 1),
 ('erin', 1),
 ('fred', 0),
 ('logan', 0),
 ('isabella', 1),
 ('tammy', 1),
 ('louise', 1),
 ('florence', 1),
 ('randy', 0),
 ('bradley', 0),
 ('kathy', 1),
 ('lois', 1),
 ('anne', 1),
 ('bonnie', 1),
 ('victor', 0),
 ('taylor', 1),
 ('travis', 0),
 ('phyllis', 1),
 ('shawn', 0),
 ('phillip', 0),
 ('shannon', 1),
 ('martin', 0),
 ('johnny', 0),
 ('craig', 0),
 ('allison', 1),
 ('bobby', 0),
 ('alyssa', 1),
 ('ella', 1),
 ('josephine', 1),
 ('ernest', 0),
 ('stanley', 0),
 ('cody', 0),
 ('clarence', 0),
 ('tina', 1),
 ('elijah', 0),
 ('leonard', 0),
 ('carlos', 0),
 ('dawn', 1),
 ('robin', 1),
 ('edna', 1),
 ('cameron', 0),
 ('peggy', 1),
 ('caleb', 0),
 ('eleanor', 1),
 ('isaac', 0),
 ('todd', 0),
 ('jamie', 1),
 ('earl', 0),
 ('francis', 0),
 ('jimmy', 0),
 ('mason', 0),
 ('danny', 0),
 ('audrey', 1),
 ('rita', 1),
 ('luke', 0),
 ('dale', 0),
 ('alex', 0),
 ('paula', 1),
 ('clara', 1),
 ('wanda', 1),
 ('joel', 0),
 ('evan', 0),
 ('norma', 1),
 ('luis', 0),
 ('courtney', 1),
 ('ethel', 1),
 ('nathaniel', 0),
 ('wendy', 1),
 ('ellen', 1),
 ('leslie', 1),
 ('marjorie', 1),
 ('vanessa', 1),
 ('allen', 0),
 ('valerie', 1),
 ('carrie', 1),
 ('ava', 1),
 ('eva', 1),
 ('frederick', 0),
 ('curtis', 0),
 ('edith', 1),
 ('connie', 1),
 ('lucas', 0),
 ('gladys', 1),
 ('cindy', 1),
 ('tracy', 1),
 ('elaine', 1),
 ('hazel', 1),
 ('monica', 1),
 ('norman', 0),
 ('esther', 1),
 ('melanie', 1),
 ('brianna', 1),
 ('antonio', 0),
 ('jasmine', 1),
 ('chad', 0),
 ('katie', 1),
 ('tony', 0),
 ('rodney', 0),
 ('glenn', 0),
 ('marvin', 0),
 ('april', 1),
 ('derek', 0),
 ('erica', 1),
 ('ian', 0),
 ('adrian', 0),
 ('theodore', 0),
 ('alexandra', 1),
 ('marcus', 0),
 ('alfred', 0),
 ('jackson', 0),
 ('edwin', 0),
 ('melvin', 0),
 ('sylvia', 1),
 ('sheila', 1),
 ('alicia', 1),
 ('steve', 0),
 ('leah', 1),
 ('hunter', 0),
 ('lee', 0),
 ('jeffery', 0),
 ('kristen', 1),
 ('caroline', 1),
 ('mia', 1),
 ('sherry', 1),
 ('angel', 0),
 ('jesus', 0),
 ('dustin', 0),
 ('herbert', 0),
 ('pauline', 1),
 ('michele', 1),
 ('veronica', 1),
 ('ricky', 0),
 ('liam', 0),
 ('wesley', 0),
 ('thelma', 1),
 ('suzanne', 1),
 ('lucille', 1),
 ('morgan', 1),
 ('joanne', 1),
 ('troy', 0),
 ('chloe', 1),
 ('anita', 1),
 ('connor', 0),
 ('isaiah', 0),
 ('julian', 0),
 ('jared', 0),
 ('holly', 1),
 ('lorraine', 1),
 ('jayden', 0),
 ('jill', 1),
 ('geraldine', 1),
 ('rhonda', 1),
 ('dolores', 1),
 ('eddie', 0),
 ('vivian', 1),
 ('darlene', 1),
 ('aiden', 0),
 ('calvin', 0),
 ('shane', 0),
 ('leo', 0),
 ('juanita', 1),
 ('sally', 1),
 ('lucy', 1),
 ('bertha', 1),
 ('gail', 1),
 ('oscar', 0),
 ('mike', 0),
 ('randall', 0),
 ('ray', 0),
 ('bernard', 0),
 ('jeremiah', 0),
 ('dana', 1),
 ('brooke', 1),
 ('leroy', 0),
 ('amelia', 1),
 ('corey', 0),
 ('june', 1),
 ('owen', 0),
 ('claire', 1),
 ('jay', 0),
 ('kristin', 1),
 ('beatrice', 1),
 ('clifford', 0),
 ('marion', 1),
 ('renee', 1),
 ('tara', 1),
 ('madeline', 1),
 ('barry', 0),
 ('debbie', 1),
 ('eileen', 1),
 ('manuel', 0),
 ('ida', 1),
 ('lynn', 1),
 ('blake', 0),
 ('dean', 0),
 ('kim', 1),
 ('bernice', 1),
 ('ronnie', 0),
 ('warren', 0),
 ('gavin', 0),
 ('miguel', 0),
 ('cassandra', 1),
 ('regina', 1),
 ('elsie', 1),
 ('jo', 1),
 ('tommy', 0),
 ('trevor', 0),
 ('stella', 1),
 ('gertrude', 1),
 ('loretta', 1),
 ('rosa', 1),
 ('sydney', 1),
 ('oliver', 0),
 ('chelsea', 1),
 ('roberta', 1),
 ('savannah', 1),
 ('lindsey', 1),
 ('brett', 0),
 ('colleen', 1),
 ('gordon', 0),
 ('mitchell', 0),
 ('charlie', 0),
 ('dominic', 0),
 ('jessie', 1),
 ('annette', 1),
 ('molly', 1),
 ('cathy', 1),
 ('stacy', 1),
 ('laurie', 1),
 ('lydia', 1),
 ('jon', 0),
 ('chase', 0),
 ('leon', 0),
 ('bessie', 1),
 ('seth', 0),
 ('kaitlyn', 1),
 ('don', 0),
 ('naomi', 1),
 ('jeanette', 1),
 ('hailey', 1),
 ('jeanne', 1),
 ('darrell', 0),
 ('lloyd', 0),
 ('carter', 0),
 ('jerome', 0),
 ('erik', 0),
 ('alvin', 0),
 ('beth', 1),
 ('jenna', 1),
 ('yvonne', 1),
 ('rosemary', 1),
 ('landon', 0),
 ('bill', 0),
 ('haley', 1),
 ('alma', 1),
 ('wyatt', 0),
 ('micheal', 0),
 ('agnes', 1),
 ('gina', 1),
 ('minnie', 1),
 ('sebastian', 0),
 ('devin', 0),
 ('georgia', 1),
 ('stacey', 1),
 ('pearl', 1),
 ('vicki', 1),
 ('joann', 1),
 ('max', 0),
 ('kelsey', 1),
 ('lillie', 1),
 ('levi', 0),
 ('lily', 1),
 ('floyd', 0),
 ('carla', 1),
 ('edgar', 0),
 ('lewis', 0),
 ('jim', 0),
 ('nora', 1),
 ('maureen', 1),
 ('brent', 0),
 ('heidi', 1),
 ('derrick', 0),
 ('mario', 0),
 ('nellie', 1),
 ('lindsay', 1),
 ('kristina', 1),
 ('shelby', 1),
 ('terri', 1),
 ('destiny', 1),
 ('vernon', 0),
 ('paige', 1),
 ('chris', 0),
 ('marc', 0),
 ('violet', 1),
 ('willie', 1),
 ('arlene', 1),
 ('sue', 1),
 ('cole', 0),
 ('daisy', 1),
 ('sabrina', 1),
 ('ricardo', 0),
 ('carmen', 1),
 ('clyde', 0),
 ('marian', 1),
 ('vera', 1),
 ('constance', 1),
 ('deanna', 1),
 ('wilma', 1),
 ('colin', 0),
 ('melinda', 1),
 ('tom', 0),
 ('lena', 1),
 ('tamara', 1),
 ('joy', 1),
 ('faith', 1),
 ('clayton', 0),
 ('maurice', 0),
 ('gabrielle', 1),
 ('cory', 0),
 ('franklin', 0),
 ('ivan', 0),
 ('xavier', 0),
 ('charlene', 1),
 ('katelyn', 1),
 ('francisco', 0),
 ('sofia', 1),
 ('garrett', 0),
 ('myrtle', 1),
 ('cora', 1),
 ('jordan', 1),
 ('alejandro', 0),
 ('herman', 0),
 ('mabel', 1),
 ('jorge', 0),
 ('marcia', 1),
 ('grant', 0),
 ('marlene', 1),
 ('erika', 1),
 ('zoe', 1),
 ('mackenzie', 1),
 ('glen', 0),
 ('viola', 1),
 ('gilbert', 0),
 ('jake', 0),
 ('mattie', 1),
 ('nina', 1),
 ('claudia', 1),
 ('lester', 0),
 ('kaylee', 1),
 ('avery', 1),
 ('elmer', 0),
 ('tanya', 1),
 ('andre', 0),
 ('alexa', 1),
 ('jennie', 1),
 ('autumn', 1),
 ('sadie', 1),
 ('gene', 0),
 ('sam', 0),
 ('marissa', 1),
 ('colton', 0),
 ('spencer', 0),
 ('eli', 0),
 ('alison', 1),
 ('caitlin', 1),
 ('harvey', 0),
 ('tonya', 1),
 ('priscilla', 1),
 ('addison', 1),
 ('isabel', 1),
 ('angelina', 1),
 ('brayden', 0),
 ('sophie', 1),
 ('chester', 0),
 ('jeff', 0),
 ('gwendolyn', 1),
 ('casey', 0),
 ('bryce', 0),
 ('patsy', 1),
 ('tristan', 0),
 ('gabriella', 1),
 ('taylor', 0),
 ('leslie', 0),
 ('maggie', 1),
 ('miranda', 1),
 ('darren', 0),
 ('delores', 1),
 ('milton', 0),
 ('duane', 0),
 ('preston', 0),
 ('kylie', 1),
 ('reginald', 0),
 ('genevieve', 1),
 ('ruben', 0),
 ('aidan', 0),
 ('brandy', 1),
 ('yolanda', 1),
 ('maxine', 1),
 ('aubrey', 1),
 ('jessie', 0),
 ('roberto', 0),
 ('carole', 1),
 ('jimmie', 0),
 ('joanna', 1),
 ('neil', 0),
 ('miriam', 1),
 ('natasha', 1),
 ('carson', 0),
 ('katrina', 1),
 ('leona', 1),
 ('glenda', 1),
 ('lance', 0),
 ('mae', 1),
 ('mariah', 1),
 ('vickie', 1),
 ('brandi', 1),
 ('whitney', 1),
 ('jocelyn', 1),
 ('josiah', 0),
 ('everett', 0),
 ('riley', 1),
 ('diego', 0),
 ('parker', 0),
 ('cecil', 0),
 ('kara', 1),
 ('dan', 0),
 ('meghan', 1),
 ('dora', 1),
 ('brooklyn', 1),
 ('margie', 1),
 ('allan', 0),
 ('bethany', 1),
 ('eduardo', 0),
 ('ana', 1),
 ('hector', 0),
 ('arnold', 0),
 ('marsha', 1),
 ('karl', 0),
 ('nolan', 0),
 ('makayla', 1),
 ('hayden', 0),
 ('toni', 1),
 ('riley', 0),
 ('christy', 1),
 ('clinton', 0),
 ('billie', 1),
 ('johnnie', 0),
 ('dianne', 1),
 ('ariana', 1),
 ('kendra', 1),
 ('alexandria', 1),
 ('sierra', 1),
 ('bailey', 1),
 ('javier', 0),
 ('penny', 1),
 ('maya', 1),
 ('melody', 1),
 ('angel', 1),
 ('roland', 0),
 ('omar', 0),
 ('hattie', 1),
 ('johnathan', 0),
 ('kay', 1),
 ('cecilia', 1),
 ('fernando', 0),
 ('terry', 1),
 ('darryl', 0),
 ('brendan', 0),
 ('felicia', 1),
 ('maxwell', 0),
 ('jenny', 1),
 ('micah', 0),
 ('isabelle', 1),
 ('ada', 1),
 ('briana', 1),
 ('tanner', 0),
 ('marguerite', 1),
 ('jamie', 0),
 ('lonnie', 0),
 ('angelica', 1),
 ('marshall', 0),
 ('bridget', 1),
 ('tracey', 1),
 ('bob', 0),
 ('abraham', 0),
 ('arianna', 1),
 ('madelyn', 1),
 ('adriana', 1),
 ('andy', 0),
 ('brady', 0),
 ('guy', 0),
 ('nicolas', 0),
 ('jackie', 1),
 ('candace', 1),
 ('hope', 1),
 ('karla', 1),
 ('claude', 0),
 ('pedro', 0),
 ('jillian', 1),
 ('brittney', 1),
 ('rachael', 1),
 ('damian', 0),
 ('lola', 1),
 ('ross', 0),
 ('kate', 1),
 ('layla', 1),
 ('jade', 1),
 ('harriet', 1),
 ('bobbie', 1),
 ('misty', 1),
 ('cooper', 0),
 ('kurt', 0),
 ('kristine', 1),
 ('aaliyah', 1),
 ('geneva', 1),
 ('desiree', 1),
 ('dakota', 0),
 ('shelly', 1),
 ('becky', 1),
 ('jacquelyn', 1),
 ('kelly', 0),
 ('blanche', 1),
 ('velma', 1),
 ('krystal', 1),
 ('raul', 0),
 ('brad', 0),
 ('ben', 0),
 ('sherri', 1),
 ('andres', 0),
 ('susie', 1),
 ('fannie', 1),
 ('sidney', 0),
 ('zoey', 1),
 ('miles', 0),
 ('breanna', 1),
 ('monique', 1),
 ('hugh', 0),
 ('lula', 1),
 ('iris', 1),
 ('mathew', 0),
 ('byron', 0),
 ('jodi', 1),
 ('casey', 1),
 ('tim', 0),
 ('elias', 0),
 ('rick', 0),
 ('wallace', 0),
 ('harper', 1),
 ('summer', 1),
 ('grayson', 0),
 ('dalton', 0),
 ('lynda', 1),
 ('harrison', 0),
 ('krista', 1),
 ('hilda', 1),
 ('tyrone', 0),
 ('jaxon', 0),
 ('rafael', 0),
 ('gabriela', 1),
 ('nevaeh', 1),
 ('sheryl', 1),
 ('drew', 0),
 ('kristi', 1),
 ('rosie', 1),
 ('elena', 1),
 ('angelo', 0),
 ('eunice', 1),
 ('shelley', 1),
 ('nelson', 0),
 ('antoinette', 1),
 ('dwayne', 0),
 ('dwight', 0),
 ('kelli', 1),
 ('julius', 0),
 ('jackie', 0),
 ('trinity', 1),
 ('shaun', 0),
 ('meredith', 1),
 ('kaleb', 0),
 ('sergio', 0),
 ('collin', 0),
 ('rebekah', 1),
 ('greg', 0),
 ('emmanuel', 0),
 ('mamie', 1),
 ('willard', 0),
 ('ramon', 0),
 ('perry', 0),
 ('bianca', 1),
 ('kristy', 1),
 ('candice', 1),
 ('jaden', 0),
 ('belinda', 1),
 ('gracie', 1),
 ('devon', 0),
 ('ted', 0),
 ('terrence', 0),
 ('janie', 1),
 ('stuart', 0),
 ('armando', 0),
 ('rosalie', 1),
 ('marco', 0),
 ('cesar', 0),
 ('ayden', 0),
 ('ashton', 0),
 ('irma', 1),
 ('peyton', 1),
 ('wade', 0),
 ('terrance', 0),
 ('erick', 0),
 ('freddie', 0),
 ('beulah', 1),
 ('felix', 0),
 ('kennedy', 1),
 ('marion', 0),
 ('ariel', 1),
 ('brody', 0),
 ('virgil', 0),
 ('adrienne', 1),
 ('roman', 0),
 ('morris', 0),
 ('robyn', 1),
 ('clifton', 0),
 ('kent', 0),
 ('jonathon', 0),
 ('jaime', 0),
 ('kirk', 0),
 ('sandy', 1),
 ('jeannette', 1),
 ('alberta', 1),
 ('elise', 1),
 ('verna', 1),
 ('giovanni', 0),
 ('camila', 1),
 ('simon', 0),
 ('carly', 1),
 ('faye', 1),
 ('sonia', 1),
 ('camille', 1),
 ('opal', 1),
 ('nichole', 1),
 ('ramona', 1),
 ('cheyenne', 1),
 ('scarlett', 1),
 ('flora', 1),
 ('sonya', 1),
 ('jace', 0),
 ('della', 1),
 ('leonardo', 0),
 ('penelope', 1),
 ('lorenzo', 0),
 ('genesis', 1),
 ('jonah', 0),
 ('daryl', 0),
 ('lila', 1),
 ('kristopher', 0),
 ('natalia', 1),
 ('malcolm', 0),
 ('gianna', 1),
 ('inez', 1),
 ('skylar', 1),
 ('valeria', 1),
 ('marianne', 1),
 ('damon', 0),
 ('lincoln', 0),
 ('luther', 0),
 ('ellie', 1),
 ('guadalupe', 1),
 ('fredrick', 0),
 ('jada', 1),
 ('yvette', 1),
 ('dillon', 0),
 ('dallas', 0),
 ('alexis', 0),
 ('marcella', 1),
 ('geoffrey', 0),
 ('dave', 0),
 ('hudson', 0),
 ('dominick', 0),
 ('bryson', 0),
 ('angie', 1),
 ('lynne', 1),
 ('lee', 1),
 ('kari', 1),
 ('bella', 1),
 ('cristian', 0),
 ('maryann', 1),
 ('gayle', 1),
 ('tabitha', 1),
 ('sheri', 1),
 ('patty', 1),
 ('olga', 1),
 ('rickey', 0),
 ('israel', 0),
 ('alisha', 1),
 ('alberto', 0),
 ('santiago', 0),
 ('tracy', 0),
 ('julio', 0),
 ('kaden', 0),
 ('abby', 1),
 ('alana', 1),
 ('daniela', 1),
 ('kaitlin', 1),
 ('myra', 1),
 ('roxanne', 1),
 ('caden', 0),
 ('damien', 0),
 ('annabelle', 1),
 ('karina', 1),
 ('donnie', 0),
 ('kendall', 1),
 ('homer', 0),
 ('lyle', 0),
 ('mallory', 1),
 ('callie', 1),
 ('juliana', 1),
 ('josie', 1),
 ('celeste', 1),
 ('mckenzie', 1),
 ('adeline', 1),
 ('cassidy', 1),
 ('gerard', 0),
 ('aurora', 1),
 ('rex', 0),
 ('enrique', 0),
 ('otis', 0),
 ('lilly', 1),
 ('gage', 0),
 ('jody', 1),
 ('earnest', 0),
 ('donovan', 0),
 ('janelle', 1),
 ('serenity', 1),
 ('trenton', 0),
 ('aimee', 1),
 ('kirsten', 1),
 ('asher', 0),
 ('hubert', 0),
 ('dianna', 1),
 ('avery', 0),
 ('cecelia', 1),
 ('dominique', 1),
 ('mya', 1),
 ('emmett', 0),
 ('olive', 1),
 ('wilbur', 0),
 ('lacey', 1),
 ('liliana', 1),
 ('mateo', 0),
 ('salvatore', 0),
 ('cara', 1),
 ('muriel', 1),
 ('alfredo', 0),
 ('neal', 0),
 ('mikayla', 1),
 ('eliza', 1),
 ('hayley', 1),
 ('nadine', 1),
 ('bernadette', 1),
 ('celia', 1),
 ('arturo', 0),
 ('cristina', 1),
 ('jan', 1),
 ('jordyn', 1),
 ('lana', 1),
 ('erma', 1),
 ('dana', 0),
 ('jaclyn', 1),
 ('vicky', 1),
 ('caitlyn', 1),
 ('alec', 0),
 ('gretchen', 1),
 ('leland', 0),
 ('johanna', 1),
 ('horace', 0),
 ('shannon', 0),
 ('jaime', 1),
 ('colby', 0),
 ('joey', 0),
 ('abel', 0),
 ('traci', 1),
 ('kellie', 1),
 ('estelle', 1),
 ('kerry', 1),
 ('ira', 0),
 ('conner', 0),
 ('payton', 1),
 ('wendell', 0),
 ('ezra', 0),
 ('trent', 0),
 ('eloise', 1),
 ('rudolph', 0),
 ('aria', 1),
 ('ivy', 1),
 ('graham', 0),
 ...]

#### Checking if there are still rows/names with '-' char

In [219]:
list(filter(lambda row: '-' in row[0], name_gender_exp))[:20]

[]

#### checking if there are still items in the `name_gender_exp_flat` that are lists

In [220]:
list(filter(lambda item: len(item) > 1, name_gender_exp))[:20]

[[('jo', 1), ('anne', 1)],
 [('jo', 1), ('ann', 1)],
 [('anne', 1), ('marie', 1)],
 [('zo', 1), ('', 1)],
 [('lee', 1), ('anne', 1)],
 [('lee', 1), ('ann', 1)],
 [('smt', 1), ('', 1)],
 [('ann', 1), ('marie', 1)],
 [('chlo', 1), ('', 1)],
 [('julie', 1), ('anne', 1)],
 [('mary', 1), ('ann', 1)],
 [('julie', 1), ('ann', 1)],
 [('am', 1), ('lie', 1)],
 [('lori', 1), ('ann', 1)],
 [('d', 0), ('arcy', 0)],
 [('mary', 1), ('anne', 1)],
 [('ma', 1), ('lle', 1)],
 [('emma', 1), ('lee', 1)],
 [('sarah', 1), ('jane', 1)],
 [('anna', 1), ('marie', 1)]]

In [221]:
list(filter(lambda item: type(item) == list, name_gender_exp_flat))[:20]

[]

In [222]:
name_gender_exp_flat

[('james', 0),
 ('john', 0),
 ('robert', 0),
 ('michael', 0),
 ('william', 0),
 ('mary', 1),
 ('david', 0),
 ('joseph', 0),
 ('richard', 0),
 ('charles', 0),
 ('thomas', 0),
 ('christopher', 0),
 ('daniel', 0),
 ('matthew', 0),
 ('elizabeth', 1),
 ('patricia', 1),
 ('jennifer', 1),
 ('anthony', 0),
 ('george', 0),
 ('linda', 1),
 ('barbara', 1),
 ('donald', 0),
 ('paul', 0),
 ('mark', 0),
 ('andrew', 0),
 ('steven', 0),
 ('kenneth', 0),
 ('edward', 0),
 ('joshua', 0),
 ('margaret', 1),
 ('brian', 0),
 ('kevin', 0),
 ('jessica', 1),
 ('sarah', 1),
 ('susan', 1),
 ('timothy', 0),
 ('dorothy', 1),
 ('jason', 0),
 ('ronald', 0),
 ('helen', 1),
 ('ryan', 0),
 ('jeffrey', 0),
 ('karen', 1),
 ('nancy', 1),
 ('betty', 1),
 ('lisa', 1),
 ('jacob', 0),
 ('nicholas', 0),
 ('ashley', 1),
 ('eric', 0),
 ('frank', 0),
 ('gary', 0),
 ('anna', 1),
 ('stephen', 0),
 ('jonathan', 0),
 ('sandra', 1),
 ('emily', 1),
 ('amanda', 1),
 ('kimberly', 1),
 ('michelle', 1),
 ('donna', 1),
 ('justin', 0),
 ('laura', 1),
 ('ruth', 1),
 ('carol', 1),
 ('brandon', 0),
 ('larry', 0),
 ('scott', 0),
 ('melissa', 1),
 ('stephanie', 1),
 ('benjamin', 0),
 ('raymond', 0),
 ('samuel', 0),
 ('rebecca', 1),
 ('deborah', 1),
 ('gregory', 0),
 ('sharon', 1),
 ('kathleen', 1),
 ('amy', 1),
 ('cynthia', 1),
 ('alexander', 0),
 ('patrick', 0),
 ('jack', 0),
 ('henry', 0),
 ('angela', 1),
 ('shirley', 1),
 ('emma', 1),
 ('catherine', 1),
 ('katherine', 1),
 ('virginia', 1),
 ('nicole', 1),
 ('dennis', 0),
 ('walter', 0),
 ('tyler', 0),
 ('peter', 0),
 ('brenda', 1),
 ('aaron', 0),
 ('jerry', 0),
 ('christine', 1),
 ('samantha', 1),
 ('adam', 0),
 ('rachel', 1),
 ('pamela', 1),
 ('frances', 1),
 ('nathan', 0),
 ('douglas', 0),
 ('heather', 1),
 ('evelyn', 1),
 ('jose', 0),
 ('alice', 1),
 ('janet', 1),
 ('maria', 1),
 ('zachary', 0),
 ('carolyn', 1),
 ('debra', 1),
 ('harold', 0),
 ('martha', 1),
 ('marie', 1),
 ('arthur', 0),
 ('julie', 1),
 ('kyle', 0),
 ('diane', 1),
 ('christina', 1),
 ('victoria', 1),
 ('joyce', 1),
 ('carl', 0),
 ('lauren', 1),
 ('grace', 1),
 ('kelly', 1),
 ('albert', 0),
 ('rose', 1),
 ('megan', 1),
 ('joan', 1),
 ('jeremy', 0),
 ('ann', 1),
 ('julia', 1),
 ('kathryn', 1),
 ('lawrence', 0),
 ('olivia', 1),
 ('judith', 1),
 ('doris', 1),
 ('jean', 1),
 ('andrea', 1),
 ('gerald', 0),
 ('sean', 0),
 ('joe', 0),
 ('keith', 0),
 ('sara', 1),
 ('cheryl', 1),
 ('hannah', 1),
 ('mildred', 1),
 ('willie', 0),
 ('lillian', 1),
 ('roger', 0),
 ('jesse', 0),
 ('jacqueline', 1),
 ('ethan', 0),
 ('terry', 0),
 ('christian', 0),
 ('harry', 0),
 ('teresa', 1),
 ('austin', 0),
 ('gloria', 1),
 ('ralph', 0),
 ('janice', 1),
 ('roy', 0),
 ('theresa', 1),
 ('amber', 1),
 ('danielle', 1),
 ('noah', 0),
 ('bryan', 0),
 ('jordan', 0),
 ('louis', 0),
 ('brittany', 1),
 ('bruce', 0),
 ('madison', 1),
 ('judy', 1),
 ('billy', 0),
 ('dylan', 0),
 ('denise', 1),
 ('beverly', 1),
 ('eugene', 0),
 ('jane', 1),
 ('marilyn', 1),
 ('abigail', 1),
 ('diana', 1),
 ('charlotte', 1),
 ('natalie', 1),
 ('tiffany', 1),
 ('wayne', 0),
 ('russell', 0),
 ('alan', 0),
 ('crystal', 1),
 ('sophia', 1),
 ('irene', 1),
 ('juan', 0),
 ('ruby', 1),
 ('gabriel', 0),
 ('philip', 0),
 ('annie', 1),
 ('kayla', 1),
 ('vincent', 0),
 ('lori', 1),
 ('howard', 0),
 ('alexis', 1),
 ('erin', 1),
 ('fred', 0),
 ('logan', 0),
 ('isabella', 1),
 ('tammy', 1),
 ('louise', 1),
 ('florence', 1),
 ('randy', 0),
 ('bradley', 0),
 ('kathy', 1),
 ('lois', 1),
 ('anne', 1),
 ('bonnie', 1),
 ('victor', 0),
 ('taylor', 1),
 ('travis', 0),
 ('phyllis', 1),
 ('shawn', 0),
 ('phillip', 0),
 ('shannon', 1),
 ('martin', 0),
 ('johnny', 0),
 ('craig', 0),
 ('allison', 1),
 ('bobby', 0),
 ('alyssa', 1),
 ('ella', 1),
 ('josephine', 1),
 ('ernest', 0),
 ('stanley', 0),
 ('cody', 0),
 ('clarence', 0),
 ('tina', 1),
 ('elijah', 0),
 ('leonard', 0),
 ('carlos', 0),
 ('dawn', 1),
 ('robin', 1),
 ('edna', 1),
 ('cameron', 0),
 ('peggy', 1),
 ('caleb', 0),
 ('eleanor', 1),
 ('isaac', 0),
 ('todd', 0),
 ('jamie', 1),
 ('earl', 0),
 ('francis', 0),
 ('jimmy', 0),
 ('mason', 0),
 ('danny', 0),
 ('audrey', 1),
 ('rita', 1),
 ('luke', 0),
 ('dale', 0),
 ('alex', 0),
 ('paula', 1),
 ('clara', 1),
 ('wanda', 1),
 ('joel', 0),
 ('evan', 0),
 ('norma', 1),
 ('luis', 0),
 ('courtney', 1),
 ('ethel', 1),
 ('nathaniel', 0),
 ('wendy', 1),
 ('ellen', 1),
 ('leslie', 1),
 ('marjorie', 1),
 ('vanessa', 1),
 ('allen', 0),
 ('valerie', 1),
 ('carrie', 1),
 ('ava', 1),
 ('eva', 1),
 ('frederick', 0),
 ('curtis', 0),
 ('edith', 1),
 ('connie', 1),
 ('lucas', 0),
 ('gladys', 1),
 ('cindy', 1),
 ('tracy', 1),
 ('elaine', 1),
 ('hazel', 1),
 ('monica', 1),
 ('norman', 0),
 ('esther', 1),
 ('melanie', 1),
 ('brianna', 1),
 ('antonio', 0),
 ('jasmine', 1),
 ('chad', 0),
 ('katie', 1),
 ('tony', 0),
 ('rodney', 0),
 ('glenn', 0),
 ('marvin', 0),
 ('april', 1),
 ('derek', 0),
 ('erica', 1),
 ('ian', 0),
 ('adrian', 0),
 ('theodore', 0),
 ('alexandra', 1),
 ('marcus', 0),
 ('alfred', 0),
 ('jackson', 0),
 ('edwin', 0),
 ('melvin', 0),
 ('sylvia', 1),
 ('sheila', 1),
 ('alicia', 1),
 ('steve', 0),
 ('leah', 1),
 ('hunter', 0),
 ('lee', 0),
 ('jeffery', 0),
 ('kristen', 1),
 ('caroline', 1),
 ('mia', 1),
 ('sherry', 1),
 ('angel', 0),
 ('jesus', 0),
 ('dustin', 0),
 ('herbert', 0),
 ('pauline', 1),
 ('michele', 1),
 ('veronica', 1),
 ('ricky', 0),
 ('liam', 0),
 ('wesley', 0),
 ('thelma', 1),
 ('suzanne', 1),
 ('lucille', 1),
 ('morgan', 1),
 ('joanne', 1),
 ('troy', 0),
 ('chloe', 1),
 ('anita', 1),
 ('connor', 0),
 ('isaiah', 0),
 ('julian', 0),
 ('jared', 0),
 ('holly', 1),
 ('lorraine', 1),
 ('jayden', 0),
 ('jill', 1),
 ('geraldine', 1),
 ('rhonda', 1),
 ('dolores', 1),
 ('eddie', 0),
 ('vivian', 1),
 ('darlene', 1),
 ('aiden', 0),
 ('calvin', 0),
 ('shane', 0),
 ('leo', 0),
 ('juanita', 1),
 ('sally', 1),
 ('lucy', 1),
 ('bertha', 1),
 ('gail', 1),
 ('oscar', 0),
 ('mike', 0),
 ('randall', 0),
 ('ray', 0),
 ('bernard', 0),
 ('jeremiah', 0),
 ('dana', 1),
 ('brooke', 1),
 ('leroy', 0),
 ('amelia', 1),
 ('corey', 0),
 ('june', 1),
 ('owen', 0),
 ('claire', 1),
 ('jay', 0),
 ('kristin', 1),
 ('beatrice', 1),
 ('clifford', 0),
 ('marion', 1),
 ('renee', 1),
 ('tara', 1),
 ('madeline', 1),
 ('barry', 0),
 ('debbie', 1),
 ('eileen', 1),
 ('manuel', 0),
 ('ida', 1),
 ('lynn', 1),
 ('blake', 0),
 ('dean', 0),
 ('kim', 1),
 ('bernice', 1),
 ('ronnie', 0),
 ('warren', 0),
 ('gavin', 0),
 ('miguel', 0),
 ('cassandra', 1),
 ('regina', 1),
 ('elsie', 1),
 ('jo', 1),
 ('tommy', 0),
 ('trevor', 0),
 ('stella', 1),
 ('gertrude', 1),
 ('loretta', 1),
 ('rosa', 1),
 ('sydney', 1),
 ('oliver', 0),
 ('chelsea', 1),
 ('roberta', 1),
 ('savannah', 1),
 ('lindsey', 1),
 ('brett', 0),
 ('colleen', 1),
 ('gordon', 0),
 ('mitchell', 0),
 ('charlie', 0),
 ('dominic', 0),
 ('jessie', 1),
 ('annette', 1),
 ('molly', 1),
 ('cathy', 1),
 ('stacy', 1),
 ('laurie', 1),
 ('lydia', 1),
 ('jon', 0),
 ('chase', 0),
 ('leon', 0),
 ('bessie', 1),
 ('seth', 0),
 ('kaitlyn', 1),
 ('don', 0),
 ('naomi', 1),
 ('jeanette', 1),
 ('hailey', 1),
 ('jeanne', 1),
 ('darrell', 0),
 ('lloyd', 0),
 ('carter', 0),
 ('jerome', 0),
 ('erik', 0),
 ('alvin', 0),
 ('beth', 1),
 ('jenna', 1),
 ('yvonne', 1),
 ('rosemary', 1),
 ('landon', 0),
 ('bill', 0),
 ('haley', 1),
 ('alma', 1),
 ('wyatt', 0),
 ('micheal', 0),
 ('agnes', 1),
 ('gina', 1),
 ('minnie', 1),
 ('sebastian', 0),
 ('devin', 0),
 ('georgia', 1),
 ('stacey', 1),
 ('pearl', 1),
 ('vicki', 1),
 ('joann', 1),
 ('max', 0),
 ('kelsey', 1),
 ('lillie', 1),
 ('levi', 0),
 ('lily', 1),
 ('floyd', 0),
 ('carla', 1),
 ('edgar', 0),
 ('lewis', 0),
 ('jim', 0),
 ('nora', 1),
 ('maureen', 1),
 ('brent', 0),
 ('heidi', 1),
 ('derrick', 0),
 ('mario', 0),
 ('nellie', 1),
 ('lindsay', 1),
 ('kristina', 1),
 ('shelby', 1),
 ('terri', 1),
 ('destiny', 1),
 ('vernon', 0),
 ('paige', 1),
 ('chris', 0),
 ('marc', 0),
 ('violet', 1),
 ('willie', 1),
 ('arlene', 1),
 ('sue', 1),
 ('cole', 0),
 ('daisy', 1),
 ('sabrina', 1),
 ('ricardo', 0),
 ('carmen', 1),
 ('clyde', 0),
 ('marian', 1),
 ('vera', 1),
 ('constance', 1),
 ('deanna', 1),
 ('wilma', 1),
 ('colin', 0),
 ('melinda', 1),
 ('tom', 0),
 ('lena', 1),
 ('tamara', 1),
 ('joy', 1),
 ('faith', 1),
 ('clayton', 0),
 ('maurice', 0),
 ('gabrielle', 1),
 ('cory', 0),
 ('franklin', 0),
 ('ivan', 0),
 ('xavier', 0),
 ('charlene', 1),
 ('katelyn', 1),
 ('francisco', 0),
 ('sofia', 1),
 ('garrett', 0),
 ('myrtle', 1),
 ('cora', 1),
 ('jordan', 1),
 ('alejandro', 0),
 ('herman', 0),
 ('mabel', 1),
 ('jorge', 0),
 ('marcia', 1),
 ('grant', 0),
 ('marlene', 1),
 ('erika', 1),
 ('zoe', 1),
 ('mackenzie', 1),
 ('glen', 0),
 ('viola', 1),
 ('gilbert', 0),
 ('jake', 0),
 ('mattie', 1),
 ('nina', 1),
 ('claudia', 1),
 ('lester', 0),
 ('kaylee', 1),
 ('avery', 1),
 ('elmer', 0),
 ('tanya', 1),
 ('andre', 0),
 ('alexa', 1),
 ('jennie', 1),
 ('autumn', 1),
 ('sadie', 1),
 ('gene', 0),
 ('sam', 0),
 ('marissa', 1),
 ('colton', 0),
 ('spencer', 0),
 ('eli', 0),
 ('alison', 1),
 ('caitlin', 1),
 ('harvey', 0),
 ('tonya', 1),
 ('priscilla', 1),
 ('addison', 1),
 ('isabel', 1),
 ('angelina', 1),
 ('brayden', 0),
 ('sophie', 1),
 ('chester', 0),
 ('jeff', 0),
 ('gwendolyn', 1),
 ('casey', 0),
 ('bryce', 0),
 ('patsy', 1),
 ('tristan', 0),
 ('gabriella', 1),
 ('taylor', 0),
 ('leslie', 0),
 ('maggie', 1),
 ('miranda', 1),
 ('darren', 0),
 ('delores', 1),
 ('milton', 0),
 ('duane', 0),
 ('preston', 0),
 ('kylie', 1),
 ('reginald', 0),
 ('genevieve', 1),
 ('ruben', 0),
 ('aidan', 0),
 ('brandy', 1),
 ('yolanda', 1),
 ('maxine', 1),
 ('aubrey', 1),
 ('jessie', 0),
 ('roberto', 0),
 ('carole', 1),
 ('jimmie', 0),
 ('joanna', 1),
 ('neil', 0),
 ('miriam', 1),
 ('natasha', 1),
 ('carson', 0),
 ('katrina', 1),
 ('leona', 1),
 ('glenda', 1),
 ('lance', 0),
 ('mae', 1),
 ('mariah', 1),
 ('vickie', 1),
 ('brandi', 1),
 ('whitney', 1),
 ('jocelyn', 1),
 ('josiah', 0),
 ('everett', 0),
 ('riley', 1),
 ('diego', 0),
 ('parker', 0),
 ('cecil', 0),
 ('kara', 1),
 ('dan', 0),
 ('meghan', 1),
 ('dora', 1),
 ('brooklyn', 1),
 ('margie', 1),
 ('allan', 0),
 ('bethany', 1),
 ('eduardo', 0),
 ('ana', 1),
 ('hector', 0),
 ('arnold', 0),
 ('marsha', 1),
 ('karl', 0),
 ('nolan', 0),
 ('makayla', 1),
 ('hayden', 0),
 ('toni', 1),
 ('riley', 0),
 ('christy', 1),
 ('clinton', 0),
 ('billie', 1),
 ('johnnie', 0),
 ('dianne', 1),
 ('ariana', 1),
 ('kendra', 1),
 ('alexandria', 1),
 ('sierra', 1),
 ('bailey', 1),
 ('javier', 0),
 ('penny', 1),
 ('maya', 1),
 ('melody', 1),
 ('angel', 1),
 ('roland', 0),
 ('omar', 0),
 ('hattie', 1),
 ('johnathan', 0),
 ('kay', 1),
 ('cecilia', 1),
 ('fernando', 0),
 ('terry', 1),
 ('darryl', 0),
 ('brendan', 0),
 ('felicia', 1),
 ('maxwell', 0),
 ('jenny', 1),
 ('micah', 0),
 ('isabelle', 1),
 ('ada', 1),
 ('briana', 1),
 ('tanner', 0),
 ('marguerite', 1),
 ('jamie', 0),
 ('lonnie', 0),
 ('angelica', 1),
 ('marshall', 0),
 ('bridget', 1),
 ('tracey', 1),
 ('bob', 0),
 ('abraham', 0),
 ('arianna', 1),
 ('madelyn', 1),
 ('adriana', 1),
 ('andy', 0),
 ('brady', 0),
 ('guy', 0),
 ('nicolas', 0),
 ('jackie', 1),
 ('candace', 1),
 ('hope', 1),
 ('karla', 1),
 ('claude', 0),
 ('pedro', 0),
 ('jillian', 1),
 ('brittney', 1),
 ('rachael', 1),
 ('damian', 0),
 ('lola', 1),
 ('ross', 0),
 ('kate', 1),
 ('layla', 1),
 ('jade', 1),
 ('harriet', 1),
 ('bobbie', 1),
 ('misty', 1),
 ('cooper', 0),
 ('kurt', 0),
 ('kristine', 1),
 ('aaliyah', 1),
 ('geneva', 1),
 ('desiree', 1),
 ('dakota', 0),
 ('shelly', 1),
 ('becky', 1),
 ('jacquelyn', 1),
 ('kelly', 0),
 ('blanche', 1),
 ('velma', 1),
 ('krystal', 1),
 ('raul', 0),
 ('brad', 0),
 ('ben', 0),
 ('sherri', 1),
 ('andres', 0),
 ('susie', 1),
 ('fannie', 1),
 ('sidney', 0),
 ('zoey', 1),
 ('miles', 0),
 ('breanna', 1),
 ('monique', 1),
 ('hugh', 0),
 ('lula', 1),
 ('iris', 1),
 ('mathew', 0),
 ('byron', 0),
 ('jodi', 1),
 ('casey', 1),
 ('tim', 0),
 ('elias', 0),
 ('rick', 0),
 ('wallace', 0),
 ('harper', 1),
 ('summer', 1),
 ('grayson', 0),
 ('dalton', 0),
 ('lynda', 1),
 ('harrison', 0),
 ('krista', 1),
 ('hilda', 1),
 ('tyrone', 0),
 ('jaxon', 0),
 ('rafael', 0),
 ('gabriela', 1),
 ('nevaeh', 1),
 ('sheryl', 1),
 ('drew', 0),
 ('kristi', 1),
 ('rosie', 1),
 ('elena', 1),
 ('angelo', 0),
 ('eunice', 1),
 ('shelley', 1),
 ('nelson', 0),
 ('antoinette', 1),
 ('dwayne', 0),
 ('dwight', 0),
 ('kelli', 1),
 ('julius', 0),
 ('jackie', 0),
 ('trinity', 1),
 ('shaun', 0),
 ('meredith', 1),
 ('kaleb', 0),
 ('sergio', 0),
 ('collin', 0),
 ('rebekah', 1),
 ('greg', 0),
 ('emmanuel', 0),
 ('mamie', 1),
 ('willard', 0),
 ('ramon', 0),
 ('perry', 0),
 ('bianca', 1),
 ('kristy', 1),
 ('candice', 1),
 ('jaden', 0),
 ('belinda', 1),
 ('gracie', 1),
 ('devon', 0),
 ('ted', 0),
 ('terrence', 0),
 ('janie', 1),
 ('stuart', 0),
 ('armando', 0),
 ('rosalie', 1),
 ('marco', 0),
 ('cesar', 0),
 ('ayden', 0),
 ('ashton', 0),
 ('irma', 1),
 ('peyton', 1),
 ('wade', 0),
 ('terrance', 0),
 ('erick', 0),
 ('freddie', 0),
 ('beulah', 1),
 ('felix', 0),
 ('kennedy', 1),
 ('marion', 0),
 ('ariel', 1),
 ('brody', 0),
 ('virgil', 0),
 ('adrienne', 1),
 ('roman', 0),
 ('morris', 0),
 ('robyn', 1),
 ('clifton', 0),
 ('kent', 0),
 ('jonathon', 0),
 ('jaime', 0),
 ('kirk', 0),
 ('sandy', 1),
 ('jeannette', 1),
 ('alberta', 1),
 ('elise', 1),
 ('verna', 1),
 ('giovanni', 0),
 ('camila', 1),
 ('simon', 0),
 ('carly', 1),
 ('faye', 1),
 ('sonia', 1),
 ('camille', 1),
 ('opal', 1),
 ('nichole', 1),
 ('ramona', 1),
 ('cheyenne', 1),
 ('scarlett', 1),
 ('flora', 1),
 ('sonya', 1),
 ('jace', 0),
 ('della', 1),
 ('leonardo', 0),
 ('penelope', 1),
 ('lorenzo', 0),
 ('genesis', 1),
 ('jonah', 0),
 ('daryl', 0),
 ('lila', 1),
 ('kristopher', 0),
 ('natalia', 1),
 ('malcolm', 0),
 ('gianna', 1),
 ('inez', 1),
 ('skylar', 1),
 ('valeria', 1),
 ('marianne', 1),
 ('damon', 0),
 ('lincoln', 0),
 ('luther', 0),
 ('ellie', 1),
 ('guadalupe', 1),
 ('fredrick', 0),
 ('jada', 1),
 ('yvette', 1),
 ('dillon', 0),
 ('dallas', 0),
 ('alexis', 0),
 ('marcella', 1),
 ('geoffrey', 0),
 ('dave', 0),
 ('hudson', 0),
 ('dominick', 0),
 ('bryson', 0),
 ('angie', 1),
 ('lynne', 1),
 ('lee', 1),
 ('kari', 1),
 ('bella', 1),
 ('cristian', 0),
 ('maryann', 1),
 ('gayle', 1),
 ('tabitha', 1),
 ('sheri', 1),
 ('patty', 1),
 ('olga', 1),
 ('rickey', 0),
 ('israel', 0),
 ('alisha', 1),
 ('alberto', 0),
 ('santiago', 0),
 ('tracy', 0),
 ('julio', 0),
 ('kaden', 0),
 ('abby', 1),
 ('alana', 1),
 ('daniela', 1),
 ('kaitlin', 1),
 ('myra', 1),
 ('roxanne', 1),
 ('caden', 0),
 ('damien', 0),
 ('annabelle', 1),
 ('karina', 1),
 ('donnie', 0),
 ('kendall', 1),
 ('homer', 0),
 ('lyle', 0),
 ('mallory', 1),
 ('callie', 1),
 ('juliana', 1),
 ('josie', 1),
 ('celeste', 1),
 ('mckenzie', 1),
 ('adeline', 1),
 ('cassidy', 1),
 ('gerard', 0),
 ('aurora', 1),
 ('rex', 0),
 ('enrique', 0),
 ('otis', 0),
 ('lilly', 1),
 ('gage', 0),
 ('jody', 1),
 ('earnest', 0),
 ('donovan', 0),
 ('janelle', 1),
 ('serenity', 1),
 ('trenton', 0),
 ('aimee', 1),
 ('kirsten', 1),
 ('asher', 0),
 ('hubert', 0),
 ('dianna', 1),
 ('avery', 0),
 ('cecelia', 1),
 ('dominique', 1),
 ('mya', 1),
 ('emmett', 0),
 ('olive', 1),
 ('wilbur', 0),
 ('lacey', 1),
 ('liliana', 1),
 ('mateo', 0),
 ('salvatore', 0),
 ('cara', 1),
 ('muriel', 1),
 ('alfredo', 0),
 ('neal', 0),
 ('mikayla', 1),
 ('eliza', 1),
 ('hayley', 1),
 ('nadine', 1),
 ('bernadette', 1),
 ('celia', 1),
 ('arturo', 0),
 ('cristina', 1),
 ('jan', 1),
 ('jordyn', 1),
 ('lana', 1),
 ('erma', 1),
 ('dana', 0),
 ('jaclyn', 1),
 ('vicky', 1),
 ('caitlyn', 1),
 ('alec', 0),
 ('gretchen', 1),
 ('leland', 0),
 ('johanna', 1),
 ('horace', 0),
 ('shannon', 0),
 ('jaime', 1),
 ('colby', 0),
 ('joey', 0),
 ('abel', 0),
 ('traci', 1),
 ('kellie', 1),
 ('estelle', 1),
 ('kerry', 1),
 ('ira', 0),
 ('conner', 0),
 ('payton', 1),
 ('wendell', 0),
 ('ezra', 0),
 ('trent', 0),
 ('eloise', 1),
 ('rudolph', 0),
 ('aria', 1),
 ('ivy', 1),
 ('graham', 0),
 ...]

In [223]:
names, genders = list(zip(*name_gender_exp_flat))
names

('james',
 'john',
 'robert',
 'michael',
 'william',
 'mary',
 'david',
 'joseph',
 'richard',
 'charles',
 'thomas',
 'christopher',
 'daniel',
 'matthew',
 'elizabeth',
 'patricia',
 'jennifer',
 'anthony',
 'george',
 'linda',
 'barbara',
 'donald',
 'paul',
 'mark',
 'andrew',
 'steven',
 'kenneth',
 'edward',
 'joshua',
 'margaret',
 'brian',
 'kevin',
 'jessica',
 'sarah',
 'susan',
 'timothy',
 'dorothy',
 'jason',
 'ronald',
 'helen',
 'ryan',
 'jeffrey',
 'karen',
 'nancy',
 'betty',
 'lisa',
 'jacob',
 'nicholas',
 'ashley',
 'eric',
 'frank',
 'gary',
 'anna',
 'stephen',
 'jonathan',
 'sandra',
 'emily',
 'amanda',
 'kimberly',
 'michelle',
 'donna',
 'justin',
 'laura',
 'ruth',
 'carol',
 'brandon',
 'larry',
 'scott',
 'melissa',
 'stephanie',
 'benjamin',
 'raymond',
 'samuel',
 'rebecca',
 'deborah',
 'gregory',
 'sharon',
 'kathleen',
 'amy',
 'cynthia',
 'alexander',
 'patrick',
 'jack',
 'henry',
 'angela',
 'shirley',
 'emma',
 'catherine',
 'katherine',
 'virginia',
 'nicole',
 'dennis',
 'walter',
 'tyler',
 'peter',
 'brenda',
 'aaron',
 'jerry',
 'christine',
 'samantha',
 'adam',
 'rachel',
 'pamela',
 'frances',
 'nathan',
 'douglas',
 'heather',
 'evelyn',
 'jose',
 'alice',
 'janet',
 'maria',
 'zachary',
 'carolyn',
 'debra',
 'harold',
 'martha',
 'marie',
 'arthur',
 'julie',
 'kyle',
 'diane',
 'christina',
 'victoria',
 'joyce',
 'carl',
 'lauren',
 'grace',
 'kelly',
 'albert',
 'rose',
 'megan',
 'joan',
 'jeremy',
 'ann',
 'julia',
 'kathryn',
 'lawrence',
 'olivia',
 'judith',
 'doris',
 'jean',
 'andrea',
 'gerald',
 'sean',
 'joe',
 'keith',
 'sara',
 'cheryl',
 'hannah',
 'mildred',
 'willie',
 'lillian',
 'roger',
 'jesse',
 'jacqueline',
 'ethan',
 'terry',
 'christian',
 'harry',
 'teresa',
 'austin',
 'gloria',
 'ralph',
 'janice',
 'roy',
 'theresa',
 'amber',
 'danielle',
 'noah',
 'bryan',
 'jordan',
 'louis',
 'brittany',
 'bruce',
 'madison',
 'judy',
 'billy',
 'dylan',
 'denise',
 'beverly',
 'eugene',
 'jane',
 'marilyn',
 'abigail',
 'diana',
 'charlotte',
 'natalie',
 'tiffany',
 'wayne',
 'russell',
 'alan',
 'crystal',
 'sophia',
 'irene',
 'juan',
 'ruby',
 'gabriel',
 'philip',
 'annie',
 'kayla',
 'vincent',
 'lori',
 'howard',
 'alexis',
 'erin',
 'fred',
 'logan',
 'isabella',
 'tammy',
 'louise',
 'florence',
 'randy',
 'bradley',
 'kathy',
 'lois',
 'anne',
 'bonnie',
 'victor',
 'taylor',
 'travis',
 'phyllis',
 'shawn',
 'phillip',
 'shannon',
 'martin',
 'johnny',
 'craig',
 'allison',
 'bobby',
 'alyssa',
 'ella',
 'josephine',
 'ernest',
 'stanley',
 'cody',
 'clarence',
 'tina',
 'elijah',
 'leonard',
 'carlos',
 'dawn',
 'robin',
 'edna',
 'cameron',
 'peggy',
 'caleb',
 'eleanor',
 'isaac',
 'todd',
 'jamie',
 'earl',
 'francis',
 'jimmy',
 'mason',
 'danny',
 'audrey',
 'rita',
 'luke',
 'dale',
 'alex',
 'paula',
 'clara',
 'wanda',
 'joel',
 'evan',
 'norma',
 'luis',
 'courtney',
 'ethel',
 'nathaniel',
 'wendy',
 'ellen',
 'leslie',
 'marjorie',
 'vanessa',
 'allen',
 'valerie',
 'carrie',
 'ava',
 'eva',
 'frederick',
 'curtis',
 'edith',
 'connie',
 'lucas',
 'gladys',
 'cindy',
 'tracy',
 'elaine',
 'hazel',
 'monica',
 'norman',
 'esther',
 'melanie',
 'brianna',
 'antonio',
 'jasmine',
 'chad',
 'katie',
 'tony',
 'rodney',
 'glenn',
 'marvin',
 'april',
 'derek',
 'erica',
 'ian',
 'adrian',
 'theodore',
 'alexandra',
 'marcus',
 'alfred',
 'jackson',
 'edwin',
 'melvin',
 'sylvia',
 'sheila',
 'alicia',
 'steve',
 'leah',
 'hunter',
 'lee',
 'jeffery',
 'kristen',
 'caroline',
 'mia',
 'sherry',
 'angel',
 'jesus',
 'dustin',
 'herbert',
 'pauline',
 'michele',
 'veronica',
 'ricky',
 'liam',
 'wesley',
 'thelma',
 'suzanne',
 'lucille',
 'morgan',
 'joanne',
 'troy',
 'chloe',
 'anita',
 'connor',
 'isaiah',
 'julian',
 'jared',
 'holly',
 'lorraine',
 'jayden',
 'jill',
 'geraldine',
 'rhonda',
 'dolores',
 'eddie',
 'vivian',
 'darlene',
 'aiden',
 'calvin',
 'shane',
 'leo',
 'juanita',
 'sally',
 'lucy',
 'bertha',
 'gail',
 'oscar',
 'mike',
 'randall',
 'ray',
 'bernard',
 'jeremiah',
 'dana',
 'brooke',
 'leroy',
 'amelia',
 'corey',
 'june',
 'owen',
 'claire',
 'jay',
 'kristin',
 'beatrice',
 'clifford',
 'marion',
 'renee',
 'tara',
 'madeline',
 'barry',
 'debbie',
 'eileen',
 'manuel',
 'ida',
 'lynn',
 'blake',
 'dean',
 'kim',
 'bernice',
 'ronnie',
 'warren',
 'gavin',
 'miguel',
 'cassandra',
 'regina',
 'elsie',
 'jo',
 'tommy',
 'trevor',
 'stella',
 'gertrude',
 'loretta',
 'rosa',
 'sydney',
 'oliver',
 'chelsea',
 'roberta',
 'savannah',
 'lindsey',
 'brett',
 'colleen',
 'gordon',
 'mitchell',
 'charlie',
 'dominic',
 'jessie',
 'annette',
 'molly',
 'cathy',
 'stacy',
 'laurie',
 'lydia',
 'jon',
 'chase',
 'leon',
 'bessie',
 'seth',
 'kaitlyn',
 'don',
 'naomi',
 'jeanette',
 'hailey',
 'jeanne',
 'darrell',
 'lloyd',
 'carter',
 'jerome',
 'erik',
 'alvin',
 'beth',
 'jenna',
 'yvonne',
 'rosemary',
 'landon',
 'bill',
 'haley',
 'alma',
 'wyatt',
 'micheal',
 'agnes',
 'gina',
 'minnie',
 'sebastian',
 'devin',
 'georgia',
 'stacey',
 'pearl',
 'vicki',
 'joann',
 'max',
 'kelsey',
 'lillie',
 'levi',
 'lily',
 'floyd',
 'carla',
 'edgar',
 'lewis',
 'jim',
 'nora',
 'maureen',
 'brent',
 'heidi',
 'derrick',
 'mario',
 'nellie',
 'lindsay',
 'kristina',
 'shelby',
 'terri',
 'destiny',
 'vernon',
 'paige',
 'chris',
 'marc',
 'violet',
 'willie',
 'arlene',
 'sue',
 'cole',
 'daisy',
 'sabrina',
 'ricardo',
 'carmen',
 'clyde',
 'marian',
 'vera',
 'constance',
 'deanna',
 'wilma',
 'colin',
 'melinda',
 'tom',
 'lena',
 'tamara',
 'joy',
 'faith',
 'clayton',
 'maurice',
 'gabrielle',
 'cory',
 'franklin',
 'ivan',
 'xavier',
 'charlene',
 'katelyn',
 'francisco',
 'sofia',
 'garrett',
 'myrtle',
 'cora',
 'jordan',
 'alejandro',
 'herman',
 'mabel',
 'jorge',
 'marcia',
 'grant',
 'marlene',
 'erika',
 'zoe',
 'mackenzie',
 'glen',
 'viola',
 'gilbert',
 'jake',
 'mattie',
 'nina',
 'claudia',
 'lester',
 'kaylee',
 'avery',
 'elmer',
 'tanya',
 'andre',
 'alexa',
 'jennie',
 'autumn',
 'sadie',
 'gene',
 'sam',
 'marissa',
 'colton',
 'spencer',
 'eli',
 'alison',
 'caitlin',
 'harvey',
 'tonya',
 'priscilla',
 'addison',
 'isabel',
 'angelina',
 'brayden',
 'sophie',
 'chester',
 'jeff',
 'gwendolyn',
 'casey',
 'bryce',
 'patsy',
 'tristan',
 'gabriella',
 'taylor',
 'leslie',
 'maggie',
 'miranda',
 'darren',
 'delores',
 'milton',
 'duane',
 'preston',
 'kylie',
 'reginald',
 'genevieve',
 'ruben',
 'aidan',
 'brandy',
 'yolanda',
 'maxine',
 'aubrey',
 'jessie',
 'roberto',
 'carole',
 'jimmie',
 'joanna',
 'neil',
 'miriam',
 'natasha',
 'carson',
 'katrina',
 'leona',
 'glenda',
 'lance',
 'mae',
 'mariah',
 'vickie',
 'brandi',
 'whitney',
 'jocelyn',
 'josiah',
 'everett',
 'riley',
 'diego',
 'parker',
 'cecil',
 'kara',
 'dan',
 'meghan',
 'dora',
 'brooklyn',
 'margie',
 'allan',
 'bethany',
 'eduardo',
 'ana',
 'hector',
 'arnold',
 'marsha',
 'karl',
 'nolan',
 'makayla',
 'hayden',
 'toni',
 'riley',
 'christy',
 'clinton',
 'billie',
 'johnnie',
 'dianne',
 'ariana',
 'kendra',
 'alexandria',
 'sierra',
 'bailey',
 'javier',
 'penny',
 'maya',
 'melody',
 'angel',
 'roland',
 'omar',
 'hattie',
 'johnathan',
 'kay',
 'cecilia',
 'fernando',
 'terry',
 'darryl',
 'brendan',
 'felicia',
 'maxwell',
 'jenny',
 'micah',
 'isabelle',
 'ada',
 'briana',
 'tanner',
 'marguerite',
 'jamie',
 'lonnie',
 'angelica',
 'marshall',
 'bridget',
 'tracey',
 'bob',
 'abraham',
 'arianna',
 'madelyn',
 'adriana',
 'andy',
 'brady',
 'guy',
 'nicolas',
 'jackie',
 'candace',
 'hope',
 'karla',
 'claude',
 'pedro',
 'jillian',
 'brittney',
 'rachael',
 'damian',
 'lola',
 'ross',
 'kate',
 'layla',
 'jade',
 'harriet',
 'bobbie',
 'misty',
 'cooper',
 'kurt',
 'kristine',
 'aaliyah',
 'geneva',
 'desiree',
 'dakota',
 'shelly',
 'becky',
 'jacquelyn',
 'kelly',
 'blanche',
 'velma',
 'krystal',
 'raul',
 'brad',
 'ben',
 'sherri',
 'andres',
 'susie',
 'fannie',
 'sidney',
 'zoey',
 'miles',
 'breanna',
 'monique',
 'hugh',
 'lula',
 'iris',
 'mathew',
 'byron',
 'jodi',
 'casey',
 'tim',
 'elias',
 'rick',
 'wallace',
 'harper',
 'summer',
 'grayson',
 'dalton',
 'lynda',
 'harrison',
 'krista',
 'hilda',
 'tyrone',
 'jaxon',
 'rafael',
 'gabriela',
 'nevaeh',
 'sheryl',
 'drew',
 'kristi',
 'rosie',
 'elena',
 'angelo',
 'eunice',
 'shelley',
 'nelson',
 'antoinette',
 'dwayne',
 'dwight',
 'kelli',
 'julius',
 'jackie',
 'trinity',
 'shaun',
 'meredith',
 'kaleb',
 'sergio',
 'collin',
 'rebekah',
 'greg',
 'emmanuel',
 'mamie',
 'willard',
 'ramon',
 'perry',
 'bianca',
 'kristy',
 'candice',
 'jaden',
 'belinda',
 'gracie',
 'devon',
 'ted',
 'terrence',
 'janie',
 'stuart',
 'armando',
 'rosalie',
 'marco',
 'cesar',
 'ayden',
 'ashton',
 'irma',
 'peyton',
 'wade',
 'terrance',
 'erick',
 'freddie',
 'beulah',
 'felix',
 'kennedy',
 'marion',
 'ariel',
 'brody',
 'virgil',
 'adrienne',
 'roman',
 'morris',
 'robyn',
 'clifton',
 'kent',
 'jonathon',
 'jaime',
 'kirk',
 'sandy',
 'jeannette',
 'alberta',
 'elise',
 'verna',
 'giovanni',
 'camila',
 'simon',
 'carly',
 'faye',
 'sonia',
 'camille',
 'opal',
 'nichole',
 'ramona',
 'cheyenne',
 'scarlett',
 'flora',
 'sonya',
 'jace',
 'della',
 'leonardo',
 'penelope',
 'lorenzo',
 'genesis',
 'jonah',
 'daryl',
 'lila',
 'kristopher',
 'natalia',
 'malcolm',
 'gianna',
 'inez',
 'skylar',
 'valeria',
 'marianne',
 'damon',
 'lincoln',
 'luther',
 'ellie',
 'guadalupe',
 'fredrick',
 'jada',
 'yvette',
 'dillon',
 'dallas',
 'alexis',
 'marcella',
 'geoffrey',
 'dave',
 'hudson',
 'dominick',
 'bryson',
 'angie',
 'lynne',
 'lee',
 'kari',
 'bella',
 'cristian',
 'maryann',
 'gayle',
 'tabitha',
 'sheri',
 'patty',
 'olga',
 'rickey',
 'israel',
 'alisha',
 'alberto',
 'santiago',
 'tracy',
 'julio',
 'kaden',
 'abby',
 'alana',
 'daniela',
 'kaitlin',
 'myra',
 'roxanne',
 'caden',
 'damien',
 'annabelle',
 'karina',
 'donnie',
 'kendall',
 'homer',
 'lyle',
 'mallory',
 'callie',
 'juliana',
 'josie',
 'celeste',
 'mckenzie',
 'adeline',
 'cassidy',
 'gerard',
 'aurora',
 'rex',
 'enrique',
 'otis',
 'lilly',
 'gage',
 'jody',
 'earnest',
 'donovan',
 'janelle',
 'serenity',
 'trenton',
 'aimee',
 'kirsten',
 'asher',
 'hubert',
 'dianna',
 'avery',
 'cecelia',
 'dominique',
 'mya',
 'emmett',
 'olive',
 'wilbur',
 'lacey',
 'liliana',
 'mateo',
 'salvatore',
 'cara',
 'muriel',
 'alfredo',
 'neal',
 'mikayla',
 'eliza',
 'hayley',
 'nadine',
 'bernadette',
 'celia',
 'arturo',
 'cristina',
 'jan',
 'jordyn',
 'lana',
 'erma',
 'dana',
 'jaclyn',
 'vicky',
 'caitlyn',
 'alec',
 'gretchen',
 'leland',
 'johanna',
 'horace',
 'shannon',
 'jaime',
 'colby',
 'joey',
 'abel',
 'traci',
 'kellie',
 'estelle',
 'kerry',
 'ira',
 'conner',
 'payton',
 'wendell',
 'ezra',
 'trent',
 'eloise',
 'rudolph',
 'aria',
 'ivy',
 'graham',
 ...)

In [224]:
new_name_gender_df = pd.DataFrame({'name': names, 'gender': genders})
new_name_gender_df

           name  gender
0         james       0
1          john       0
2        robert       0
3       michael       0
4       william       0
...         ...     ...
155125   zylenn       0
155126   zymeon       0
155127   zyndel       0
155128   zyshan       0
155129    zyton       0

[155130 rows x 2 columns]

In [242]:
# split into training and testing
trains, tests = train_test_split(new_name_gender_df, test_size=0.2, random_state=0)
trains

            name  gender
58421     enrike       0
44132       karo       0
6768       donna       0
104257   taimani       1
38115     abrial       1
...          ...     ...
97639   braizlee       1
95939      quali       0
152315    shivji       0
117952       amy       1
43567    dylanie       1

[124104 rows x 2 columns]

#### dataset indicates a slight imbalance therefore it may be useful to use AUC and F1 as a metric rather than accuracy

In [244]:
# what we should do is encode each name we have into a numerical value
unique_train_names = trains['name'].unique().tolist()
unique_train_names

['enrike',
 'karo',
 'donna',
 'taimani',
 'abrial',
 'etrulia',
 'mandria',
 'aciel',
 'nhial',
 'lavie',
 'shawnae',
 'pramil',
 'shaquon',
 'aitlin',
 'editha',
 'siohban',
 'atyanna',
 'izidor',
 'rossieanna',
 'sherwyn',
 'tays',
 'sienne',
 'radvin',
 'klea',
 'genene',
 'aarish',
 'tyia',
 'dyneshia',
 'imoghen',
 'briellen',
 'shaney',
 'nikylja',
 'jayne',
 'kathy',
 'taitoko',
 'tyler',
 'meera',
 'crystalmarie',
 'quilla',
 'azrya',
 'olisia',
 'aubriona',
 'cranstone',
 'atilla',
 'neddy',
 'attis',
 'reegen',
 'aleeka',
 'conya',
 'emir',
 'tana',
 'kashmir',
 'ayasha',
 'dejene',
 'brianna',
 'shakida',
 'marie',
 'jhared',
 'jaiquez',
 'saelah',
 'dao',
 'gillard',
 'ammaar',
 'leonor',
 'evelynrose',
 'garnet',
 'jeffrey',
 'herodotus',
 'markya',
 'henrick',
 'iniyan',
 'greysyn',
 'naufahu',
 'arliene',
 'deryon',
 'vear',
 'trella',
 'milei',
 'jamine',
 'majok',
 'wilmar',
 'heysam',
 'antares',
 'lourena',
 'odell',
 'glentyn',
 'musfirah',
 'neiva',
 'loreley',
 'marlean',
 'jade',
 'pravena',
 'finnian',
 'hunner',
 'emileena',
 'rhyann',
 'loulou',
 'vyvy',
 'stuard',
 'genai',
 'theola',
 'jadyne',
 'jaquata',
 'kymbree',
 'zacc',
 'raider',
 'alyca',
 'oliver',
 'peni',
 'vendula',
 'sirjna',
 'renzzo',
 'kymisha',
 'vedanti',
 'sheniece',
 'bracelyn',
 'anarahy',
 'rashadd',
 'gabrieal',
 'shinobi',
 'ineisha',
 'mandy',
 'issac',
 'devaya',
 'leacia',
 'daurice',
 'neissen',
 'georgeann',
 'razin',
 'seti',
 'mellita',
 'jane',
 'juanye',
 'gerard',
 'khmari',
 'lucile',
 'seth',
 'mujibu',
 'ahkari',
 'lakischa',
 'delaya',
 'griffin',
 'guage',
 'yasha',
 'sabhya',
 'kendie',
 'avanti',
 'jarni',
 'jadeusk',
 'rashidat',
 'j',
 'segundo',
 'aidan',
 'lynnde',
 'vedehi',
 'kyire',
 'gwanji',
 'isharn',
 'murrianna',
 'gisely',
 'essex',
 'anterrion',
 'kavnoor',
 'rayner',
 'brantleigh',
 'demika',
 'jenevi',
 'chancellor',
 'daljit',
 'sejan',
 'misayo',
 'grace',
 'hughlon',
 'kalder',
 'annmarie',
 'adly',
 'shelleeya',
 'avital',
 'demetris',
 'naol',
 'vol',
 'kamsi',
 'duriel',
 'daryanna',
 'havala',
 'samara',
 'mutahira',
 'jaylanie',
 'shunita',
 'mckensy',
 'tacory',
 'lakisa',
 'kye',
 'melissha',
 'yang',
 'kandus',
 'khaliek',
 'gilliam',
 'sairah',
 'novaley',
 'sayeh',
 'amanti',
 'muadz',
 'maryln',
 'jesley',
 'lysia',
 'wyllys',
 'vern',
 'maddex',
 'ai',
 'hade',
 'isai',
 'abrik',
 'dewyne',
 'akashdeep',
 'sapphyre',
 'armoni',
 'lemmie',
 'tyson',
 'laquesta',
 'kalyra',
 'chiyo',
 'dekodah',
 'lenear',
 'kage',
 'yasmim',
 'theral',
 'gricell',
 'every',
 'shaparis',
 'jobi',
 'tamboura',
 'artice',
 'tuly',
 'devonta',
 'aeyla',
 'penny',
 'tyease',
 'tami',
 'lamani',
 'leigh',
 'deontez',
 'raechal',
 'mathieson',
 'dameron',
 'alexsis',
 'yasmin',
 'dana',
 'joelly',
 'karna',
 'anzie',
 'chrisly',
 'kailei',
 'unnnamed',
 'marik',
 'demosthenes',
 'darle',
 'twylla',
 'bridge',
 'jarrell',
 'jamykal',
 'alexzandria',
 'meshia',
 'lee',
 'linca',
 'nnamdi',
 'jhue',
 'thady',
 'roxani',
 'viany',
 'bayden',
 'malvine',
 'clavon',
 'silviana',
 'naomi',
 'chaela',
 'joenell',
 'tamere',
 'pejman',
 'aureon',
 'greg',
 'loreele',
 'makhaya',
 'aisel',
 'joshua',
 'arienette',
 'cieylah',
 'auviana',
 'shemicka',
 'equasha',
 'kavika',
 'desira',
 'deeon',
 'nyaisha',
 'taitua',
 'elga',
 'sardhu',
 'agol',
 'jeromie',
 'kendan',
 'taci',
 'harriot',
 'diyanah',
 'nasair',
 'hixon',
 'celestina',
 'rowynn',
 'anjelyna',
 'rodel',
 'grahem',
 'kalysta',
 'miabella',
 'warrenetta',
 'balynda',
 'maci',
 'nairn',
 'cashius',
 'tosheeb',
 'pietronella',
 'mateah',
 'sandeep',
 'mclane',
 'dominic',
 'toynelle',
 'merrell',
 'semone',
 'tequlia',
 'krishnan',
 'nam',
 'allister',
 'lyndsy',
 'ashalee',
 'hsiang',
 'zeo',
 'cheila',
 'bobbye',
 'alaiiah',
 'gordhanlal',
 'najar',
 'shunte',
 'uwain',
 'jaemir',
 'ailen',
 'dover',
 'jimmye',
 'adalai',
 'venavir',
 'meleta',
 'amarjit',
 'huxley',
 'aila',
 'rochele',
 'jovette',
 'jynelle',
 'diamondique',
 'blasa',
 'lashunna',
 'le',
 'rhyden',
 'bunthida',
 'marianita',
 'elainer',
 'claudia',
 'keekee',
 'jalei',
 'yarithza',
 'sayesha',
 'yangzom',
 'blayne',
 'amzi',
 'antoneo',
 'duy',
 'kallo',
 'donterrious',
 'malwina',
 'ann',
 'toscha',
 'tania',
 'chritina',
 'ruchoma',
 'melodey',
 'adwiti',
 'meryk',
 'greyton',
 'aldus',
 'carizma',
 'lequisha',
 'silva',
 'darrica',
 'tri',
 'cherakee',
 'cassandera',
 'kawonna',
 'karlis',
 'orden',
 'nakeem',
 'paul',
 'kenette',
 'jency',
 'muoch',
 'narae',
 'coffy',
 'knightly',
 'shahdina',
 'taiton',
 'stamatia',
 'lain',
 'silah',
 'mickenzy',
 'krishnal',
 'tykenya',
 'yarrol',
 'angelo',
 'jareliz',
 'benni',
 'saddham',
 'neale',
 'renitia',
 'meko',
 'ashgan',
 'eibhleann',
 'elizia',
 'chevahn',
 'pollyanne',
 'jovita',
 'cim',
 'atara',
 'kwan',
 'sherryll',
 'suwhil',
 'yusayrah',
 'khloi',
 'gray',
 'rajaram',
 'tyme',
 'penney',
 'carilynn',
 'alfa',
 'jorunn',
 'aneesa',
 'colum',
 'rhonda',
 'kazzira',
 'steph',
 'paisly',
 'lacandice',
 'sayge',
 'chayanne',
 'yollanda',
 'ludy',
 'takesa',
 'luella',
 'kordell',
 'zariella',
 'markey',
 'eulia',
 'galen',
 'thanh',
 'emmalleen',
 'nabil',
 'mary',
 'jaiteg',
 'latham',
 'depaul',
 'donshay',
 'lumen',
 'chanpreet',
 'sandhya',
 'griff',
 'kesten',
 'ericka',
 'dedrek',
 'danyan',
 'elwyn',
 'erminia',
 'an',
 'kyonte',
 'yalia',
 'svetislav',
 'thaily',
 'mashawnda',
 'juanesha',
 'tyriel',
 'lanis',
 'chamel',
 'aracelie',
 'herick',
 'dyonisios',
 'jind',
 'dorpha',
 'makida',
 'glenn',
 'iseral',
 'sokol',
 'sumesh',
 'pippini',
 'reshelle',
 'yeremiah',
 'japnoor',
 'marbeth',
 'maanmati',
 'joy',
 'katerina',
 'korri',
 'houwach',
 'shawnette',
 'chasia',
 'makon',
 'seirsha',
 'tjyreik',
 'faraaz',
 'rumiao',
 'ana',
 'lovly',
 'makenzy',
 'gisela',
 'kotomi',
 'caroline',
 'olivia',
 'gibram',
 'jaliel',
 'teonie',
 'mekeisha',
 'milam',
 'tyraji',
 'bisa',
 'stacie',
 'ambor',
 'maxina',
 'kyndle',
 'mabiok',
 'tharan',
 'neven',
 'kealoha',
 'leandrea',
 'akaylia',
 'williene',
 'rohan',
 'rainna',
 'cosandra',
 'trisco',
 'jennelle',
 'mutsuko',
 'toapaz',
 'johnathon',
 'wong',
 'burdette',
 'kiyuana',
 'laerica',
 'munnadevi',
 'shardai',
 'emina',
 'reygan',
 'areon',
 'sabrie',
 'miccah',
 'aithna',
 'randon',
 'mohd',
 'sydney',
 'haize',
 'samsuddin',
 'laurance',
 'somil',
 'dmauri',
 'hanaya',
 'valon',
 'zakori',
 'eisley',
 'hooda',
 'amarii',
 'keysi',
 'tanuna',
 'rusafa',
 'genneth',
 'ashaley',
 'ellary',
 'natassha',
 'nargesh',
 'helena',
 'maria',
 'peterus',
 'serul',
 'ariyauna',
 'harsidak',
 'siera',
 'joscelyne',
 'aras',
 'jianis',
 'robertine',
 'shazleen',
 'narisah',
 'kisha',
 'daveed',
 'levester',
 'mady',
 'shawnell',
 'tytrell',
 'antonnette',
 'anne',
 'avionna',
 'brooke',
 'efmorphia',
 'jermelle',
 'monika',
 'derquan',
 'swain',
 'ronaya',
 'tayah',
 'fynnlay',
 'nyikok',
 'e',
 'arkisha',
 'chen',
 'dinnie',
 'tahyah',
 'krittiya',
 'giuseppino',
 'linh',
 'zachoria',
 'sarmed',
 'gia',
 'maqsood',
 'kmaya',
 'jaso',
 'terico',
 'khallil',
 'sharlize',
 'taziah',
 'raaya',
 'ashaunti',
 'charitha',
 'makeeba',
 'raynor',
 'ariyaan',
 'brizeth',
 'keeralee',
 'germanos',
 'sopourn',
 'katya',
 'jda',
 'stevie',
 'sogna',
 'jeeya',
 'm',
 'khen',
 'suse',
 'mikalie',
 'simreet',
 'zamari',
 'toshiaki',
 'tamara',
 'siana',
 'amen',
 'victorene',
 'niccolas',
 'valentinna',
 'colynn',
 'kerlyht',
 'keijon',
 'aubren',
 'sherrylyn',
 'luvell',
 'arnna',
 'altonette',
 'tymika',
 'mamdoh',
 'farrow',
 'magic',
 'haleena',
 'amarpreet',
 'cher',
 'larri',
 'lacree',
 'rae',
 'babbu',
 'ahleah',
 'wlliam',
 'riliegh',
 'ghanshayam',
 'leighlynn',
 'sahana',
 'makenlei',
 'tiayana',
 'traetyn',
 'labelle',
 'carlyon',
 'rathan',
 'chanin',
 'frewen',
 'easther',
 'falene',
 'mellina',
 'sangit',
 'yuneisy',
 'jareb',
 'aceson',
 'irita',
 'atheena',
 'vicey',
 'vaness',
 'manojkumar',
 'janvier',
 'brytanie',
 'kendell',
 'sivert',
 'keidi',
 'fattimah',
 'domonick',
 'sharel',
 'anishia',
 'sheletta',
 'thailah',
 'ngoc',
 'raamkishore',
 'davy',
 'teyanna',
 'pista',
 'kamillia',
 'jackomino',
 'tommas',
 'deke',
 'lip',
 'miki',
 'kameryn',
 'spurgeon',
 'jessica',
 'lavoyce',
 'anon',
 'daana',
 'herrel',
 'ivoryana',
 'alduin',
 'wednesday',
 'burdene',
 'beckham',
 'toluwani',
 'october',
 'erka',
 'jori',
 'lukan',
 'gesel',
 'lillyona',
 'jeisy',
 'akelius',
 'zyrek',
 'aarthi',
 'squire',
 'zyden',
 'pariti',
 'tommey',
 'nollie',
 'rihanna',
 'ramayah',
 'huntington',
 'sarahlynn',
 'madalyn',
 'teagin',
 'sellers',
 'yaxel',
 'peydon',
 'rey',
 'jaxsen',
 'telisha',
 'yosuke',
 'aleander',
 'taylene',
 'lanashia',
 'matteo',
 'panayiotis',
 'jaquesha',
 'zolee',
 'darris',
 'jessikah',
 'elsie',
 'tanaya',
 'lehan',
 'jaxson',
 'faylynn',
 'sumanalatha',
 'alonia',
 'delvia',
 'tytin',
 'kesaun',
 'noelleen',
 'bonanza',
 'khiari',
 'karmi',
 'waldean',
 'dayquan',
 'akil',
 'jacaiden',
 'hoffman',
 'alana',
 'cassius',
 'fredia',
 'enna',
 'laela',
 'ozell',
 'athziri',
 'zyesha',
 'fayerene',
 'tang',
 'brijido',
 'shaeley',
 'anthem',
 'michelangela',
 'therea',
 'yomari',
 'jaydis',
 'labrina',
 'telayne',
 'antonio',
 'solash',
 'yanixan',
 'charmaine',
 'kateryna',
 'kym',
 'lenyce',
 'damilola',
 'sharal',
 'rayma',
 'chevette',
 'parmanand',
 'rabiah',
 'bentli',
 'halina',
 'akeyra',
 'samad',
 'tyndall',
 'imraaj',
 'kamrulnisha',
 'tarlee',
 'johnattan',
 'ericanthony',
 'sky',
 'fiora',
 'tristam',
 'beddie',
 'donivee',
 'gadiel',
 'catuzza',
 'yohanan',
 'keema',
 'melissa',
 'eiva',
 'murle',
 'ange',
 'aniello',
 'kinza',
 'ranii',
 'karilynn',
 'joleigha',
 'dhanvin',
 'darl',
 'manroven',
 'dennell',
 'yoenis',
 'shivank',
 'isara',
 'payslee',
 'taskirat',
 'calisse',
 'zyvon',
 'arvey',
 'nesly',
 'formeka',
 'berthel',
 'kiomara',
 'heinz',
 'tabatha',
 'teena',
 'leshun',
 'shiniya',
 'monicia',
 'hatton',
 'koreyon',
 'theodore',
 'onyekachukwu',
 'lakim',
 'joye',
 'keshini',
 'tarlisha',
 'mantalena',
 'sharielle',
 'kimber',
 'tammy',
 'aliyaan',
 'stayroyla',
 'xavia',
 'tinh',
 'casidhe',
 'arifa',
 'alilet',
 'd',
 'vandan',
 'thelma',
 'tiaz',
 'idalou',
 'jishnu',
 'mikkenzi',
 'mccauley',
 'zelma',
 'myona',
 'graziella',
 'naquita',
 'chotan',
 'locky',
 'juvencio',
 'ludell',
 'kovi',
 'oresto',
 'guanlin',
 'safir',
 'trail',
 'heyden',
 'vloutis',
 'isalei',
 'akanni',
 'dionta',
 'taylor',
 'cody',
 'akie',
 'dharambir',
 'sashah',
 'leylan',
 'marry',
 'katarena',
 'layne',
 'quaylin',
 'hung',
 'content',
 'maguerite',
 'marquieta',
 'deangel',
 'curran',
 'ugo',
 'miaamor',
 'asil',
 'pati',
 'tasheen',
 'lealo',
 'sumra',
 'patretar',
 'lashondria',
 'denaija',
 'janel',
 'savanah',
 'chesa',
 'bone',
 'greame',
 'therese',
 'lakedrick',
 'cypris',
 'cahlin',
 'rekiya',
 'melio',
 'tambrey',
 'gaitano',
 'ameire',
 'lapearl',
 'summa',
 'laborn',
 'yehonatan',
 'gwanda',
 'kashum',
 'emarlie',
 'shamrin',
 'ambrosia',
 'thuyvy',
 'tawan',
 'kevonna',
 'tangina',
 'frankin',
 'torrian',
 'marcellius',
 'mikayah',
 'vasilou',
 'marelyne',
 'mimmo',
 'lagenia',
 'nasly',
 'ipapandi',
 'dayshana',
 'jeccica',
 'theana',
 'aikam',
 'miajah',
 'khayri',
 'kobain',
 'cuyler',
 'raveena',
 'haroldine',
 'symari',
 'xu',
 'anna',
 'herika',
 'kacy',
 'vivy',
 'adore',
 ...]

In [245]:
# what we should do is encode each name we have into a numerical value
unique_test_names = tests['name'].unique().tolist()
unique_test_names

['monique',
 'brishae',
 'jaimison',
 'labasse',
 'neilina',
 'linda',
 'fakir',
 'syriah',
 'leigh',
 'samela',
 'jatziry',
 'kirstie',
 'teeya',
 'waverly',
 'kedrian',
 'haq',
 'comekia',
 'juanne',
 'juniel',
 'deshna',
 'dilynn',
 'harce',
 'jurij',
 'allan',
 'kahle',
 'azemara',
 'brasia',
 'navi',
 'tobey',
 'weslie',
 'mandi',
 'dataar',
 'sherrica',
 'ayudia',
 'dimitris',
 'pasqualine',
 'malika',
 'mary',
 'luie',
 'sanaii',
 'phillipos',
 'cynai',
 'caileen',
 'tracy',
 'jenniya',
 'seta',
 'jakailyn',
 'elverta',
 'may',
 'jaecyon',
 'jackaline',
 'tamina',
 'bernadeth',
 'antigone',
 'caua',
 'rhodney',
 'grosvenor',
 'keili',
 'ayoob',
 'mesut',
 'mckeyla',
 'kiera',
 'trome',
 'brienne',
 'jabree',
 'charndy',
 'ellisen',
 'jeromey',
 'annesha',
 'analysse',
 'kiaash',
 'maria',
 'nishanth',
 'khusbhoo',
 'amandarose',
 'amanie',
 'dejanai',
 'carya',
 'khalial',
 'aelianna',
 'basra',
 'armetha',
 'tennell',
 'leara',
 'johnbenedict',
 'neana',
 'hansraj',
 'jamaria',
 'dren',
 'jakyriah',
 'shyaire',
 'nirvi',
 'rae',
 'iyali',
 'zahro',
 'darynne',
 'pole',
 'vihsal',
 'caire',
 'federick',
 'namirah',
 'valeigh',
 'malkit',
 'shaheen',
 'elosia',
 'tahlik',
 'laci',
 'nahriah',
 'lilly',
 'andjelija',
 'ezell',
 'haron',
 'rell',
 'nenad',
 'xia',
 'tri',
 'edin',
 'mimose',
 'hermelinda',
 'viola',
 'prabhmehar',
 'catia',
 'siale',
 'sethius',
 'gabriela',
 'jamesthomas',
 'chidozie',
 'bryce',
 'marelys',
 'emerie',
 'dawnelle',
 'lateefa',
 'miiking',
 'shanonn',
 'tyrane',
 'toby',
 'fain',
 'raeharn',
 'diipali',
 'jaslinn',
 'nilynn',
 'jervontae',
 'ladale',
 'carolos',
 'shukri',
 'keldric',
 'krithika',
 'phineus',
 'e',
 'shurman',
 'brenlei',
 'jane',
 'baelin',
 'nicole',
 'marayah',
 'joseph',
 'delnia',
 'alissia',
 'sabika',
 'izalea',
 'terriann',
 'tarrus',
 'eldro',
 'zoye',
 'jiles',
 'micah',
 'trung',
 'reyhan',
 'dhanwanti',
 'arpit',
 'tiyonna',
 'aubreyanna',
 'reka',
 'deannette',
 'brytanni',
 'masyn',
 'so',
 'siesta',
 'ngan',
 'kannon',
 'kateleya',
 'bill',
 'taylia',
 'jahvel',
 'zevia',
 'stephenie',
 'easter',
 'cheniya',
 'dreyse',
 'davanie',
 'yutong',
 'kumari',
 'lee',
 'tahjia',
 'mishal',
 'dalane',
 'anni',
 'sharnell',
 'jaymen',
 'ann',
 'heatherbell',
 'rasheedah',
 'burkley',
 'darrellyn',
 'osmund',
 'severio',
 'ellington',
 'sinitta',
 'raines',
 'giorgie',
 'rileyn',
 'eldean',
 'maeson',
 'javeion',
 'leszek',
 'thalen',
 'tuscany',
 'itzuri',
 'janiia',
 'scott',
 'clydell',
 'audriauna',
 'lorance',
 'franciska',
 'royanne',
 'breeya',
 'jeffie',
 'schneur',
 'kvin',
 'jessie',
 'imad',
 'yerenia',
 'dub',
 'eddysen',
 'angenette',
 'mukhlisa',
 'jasmine',
 'yessenya',
 'zanab',
 'ethelynn',
 'kelly',
 'leonor',
 'kiryn',
 'shataura',
 'bailye',
 'belle',
 'heiko',
 'arne',
 'rebecca',
 'deepender',
 'vjollca',
 'trysten',
 'arvetta',
 'anacelia',
 'verayna',
 'aliakbar',
 'reyner',
 'bryttnii',
 'nicholle',
 'nichloas',
 'schnelle',
 'arseniye',
 'cheville',
 'rasheena',
 'tamiana',
 'maddon',
 'sigfredo',
 'tiit',
 'damne',
 'dekita',
 'pascalino',
 'harsha',
 'frane',
 'trinidee',
 'musra',
 'ryze',
 'jamarkus',
 'mika',
 'say',
 'vicki',
 'chisum',
 'kinara',
 'radosav',
 'arlethea',
 'cheenou',
 'carradean',
 'nerita',
 'cadillac',
 'tifney',
 'evemarie',
 'monifa',
 'shatisha',
 'raffa',
 'ahlayah',
 'kwasi',
 'rozalind',
 'lyllia',
 'lolamae',
 'adrianne',
 'kylar',
 'horrace',
 'truong',
 'kelvontae',
 'hertis',
 'tanya',
 'corinthia',
 'lynnaire',
 'leabraksa',
 'cartier',
 'luberta',
 'jai',
 'kendrix',
 'aiesha',
 'zer',
 'fabrice',
 'selihom',
 'kaanan',
 'shetera',
 'karena',
 'panauota',
 'jataveon',
 'onorato',
 'kuan',
 'lea',
 'giacoma',
 'gencie',
 'nakaria',
 'junxiang',
 'sarahkate',
 'aldana',
 'korrin',
 'aldrin',
 'kold',
 'kienna',
 'nara',
 'euclid',
 'rhoman',
 'natayja',
 'krystaline',
 'tonn',
 'yiasmin',
 'anna',
 'kristi',
 'set',
 'bobyier',
 'rishi',
 'fahed',
 'treven',
 'glee',
 'patia',
 'ruhu',
 'domarion',
 'teodulo',
 'sylveen',
 'zanijah',
 'reefe',
 'destine',
 'kieona',
 'sherna',
 'loyalti',
 'anmol',
 'rimonda',
 'lauda',
 'kamala',
 'seanagh',
 'karle',
 'azile',
 'bherav',
 'amiah',
 'binhnart',
 'azaruddin',
 'madisynn',
 'amajae',
 'rollie',
 'shayenne',
 'masaji',
 'tazmae',
 'sameia',
 'regae',
 'bryin',
 'asharia',
 'kanasia',
 'kendall',
 'tamanna',
 'ita',
 'chieu',
 'youyu',
 'barrett',
 'chuy',
 'mariah',
 'rainey',
 'vera',
 'princetin',
 'varnell',
 'lised',
 'naria',
 'arpine',
 'daralene',
 'tazmin',
 'arean',
 'jayarna',
 'leisy',
 'dimya',
 'joshua',
 'keelyn',
 'aunisty',
 'dyllan',
 'veneranda',
 'jlyn',
 'daniello',
 'jaquir',
 'jahmiere',
 'yadram',
 'siddaqmeet',
 'arwin',
 'nilia',
 'merima',
 'tywanda',
 'zhaviyah',
 'amie',
 'babe',
 'rakho',
 'jeconan',
 'tawn',
 'kyshon',
 'brackston',
 'shamario',
 'leart',
 'aeris',
 'tylarna',
 'lilyann',
 'premier',
 'niccoli',
 'ainara',
 'daphnie',
 'sudiksha',
 'mehan',
 'rodarius',
 'timouthy',
 'kejaia',
 'coco',
 'elayjah',
 'teasha',
 'nayelis',
 'yarin',
 'cedrik',
 'puspha',
 'tamzin',
 'yenuli',
 'avriana',
 'bogart',
 'adji',
 'lorreen',
 'alnisa',
 'lurton',
 'cloy',
 'jillanne',
 'cailynn',
 'graham',
 'evonia',
 'andan',
 'ashima',
 'gulwasha',
 'brandom',
 'dacorion',
 'bianca',
 'nema',
 'maggiemae',
 'shige',
 'eldo',
 'shielah',
 'azalyn',
 'yakira',
 'auril',
 'hilma',
 'hoyte',
 'amir',
 'devinee',
 'errin',
 'eithne',
 'maris',
 'clarrie',
 'minh',
 'kamarion',
 'keltan',
 'aryella',
 'johnoliver',
 'leverda',
 'rouhana',
 'jilliann',
 'dannah',
 'deonda',
 'panni',
 'morissa',
 'talaia',
 'alyssa',
 'susan',
 'quade',
 'kiare',
 'ji',
 'jedian',
 'saziya',
 'uver',
 'laura',
 'fayre',
 'chateise',
 'kary',
 'kaedym',
 'donathon',
 'jasna',
 'earna',
 'sora',
 'eric',
 'jihad',
 'abegayle',
 'karmon',
 'chloe',
 'tonesia',
 'thaliya',
 'kensy',
 'zaher',
 'elyssa',
 'latece',
 'kennede',
 'yusra',
 'yuh',
 'zacarey',
 'linza',
 'punkaj',
 'fernand',
 'janiya',
 'delroy',
 'ceferino',
 'helen',
 'malanhi',
 'leontre',
 'saliha',
 'viance',
 'hideko',
 'zoeyjane',
 'qotrunnada',
 'sumedh',
 'roben',
 'morton',
 'samantah',
 'demetra',
 'cheresa',
 'lakeeta',
 'casyn',
 'wendolee',
 'breten',
 'oluwapelumi',
 'leila',
 'peja',
 'javone',
 'mineesha',
 'kynzlei',
 'veloria',
 'jacobi',
 'keyry',
 'gerwyn',
 'shafter',
 'romilly',
 'polyanna',
 'fender',
 'daisjah',
 'eilzabeth',
 'willett',
 'abhaki',
 'pontaleo',
 'silvestra',
 'leovardo',
 'oreste',
 'macara',
 'paiten',
 'ashma',
 'sebastyn',
 'benika',
 'azuredee',
 'truce',
 'jayansh',
 'chali',
 'rahniya',
 'peru',
 'paule',
 'parvej',
 'canary',
 'jacksonjames',
 'shilee',
 'saadiya',
 'lindzy',
 'roshonna',
 'rebeccah',
 'gwennan',
 'shevaughn',
 'markel',
 'matika',
 'yasmina',
 'billison',
 'sadler',
 'donay',
 'frederik',
 'jru',
 'aaqil',
 'geet',
 'katiana',
 'deshoney',
 'deaun',
 'taquita',
 'charilyn',
 'bakary',
 'amren',
 'aarow',
 'thi',
 'kaijah',
 'yuliana',
 'macauly',
 'jacelynn',
 'najia',
 'braisley',
 'raif',
 'hemleta',
 'adelphia',
 'clinnie',
 'jerriel',
 'corday',
 'tiffany',
 'yehudis',
 'quanna',
 'najis',
 'kamrynn',
 'chavounne',
 'meraneah',
 'sharlet',
 'petah',
 'laveen',
 'azurdee',
 'rommell',
 'regard',
 'ramina',
 'nixin',
 'charmae',
 'patsey',
 'cadhan',
 'shakahna',
 'esta',
 'yanielis',
 'kahneil',
 'adrienn',
 'darrick',
 'joyceline',
 'karris',
 'jaiton',
 'shambhvi',
 'sievpior',
 'cordae',
 'traeton',
 'severino',
 'jabeer',
 'hang',
 'mesak',
 'long',
 'mare',
 'sharen',
 'chadwin',
 'dylaan',
 'quaashie',
 'shauntel',
 'kelila',
 'jarai',
 'rehansh',
 'anamar',
 'leikolo',
 'dwyn',
 'nyeim',
 'kingstin',
 'hyrell',
 'jameion',
 'waylen',
 'joule',
 'venisa',
 'ngozichukwu',
 'daiza',
 'james',
 'sunil',
 'ophia',
 'jozalyn',
 'zarrion',
 'latiah',
 'elisabetta',
 'chato',
 'javieah',
 'marjorie',
 'jahwan',
 'kymarley',
 'def',
 'bryana',
 'daon',
 'daylen',
 'benton',
 'tristiano',
 'aba',
 'kerren',
 'jailah',
 'omaryon',
 'khubi',
 'nyx',
 'dharini',
 'shernard',
 'meranda',
 'sophiamarie',
 'tammye',
 'tayleah',
 'keelen',
 'darionne',
 'anne',
 'bardo',
 'alamar',
 'athlee',
 'irini',
 'sanat',
 'aissia',
 'mckaleb',
 'aryann',
 'taissa',
 'kerry',
 'greenlee',
 'paisynn',
 'patrisia',
 'rashid',
 'cayle',
 'jarhonda',
 'woodroe',
 'anshjit',
 'biru',
 'turiya',
 'lakenya',
 'martien',
 'elman',
 'enio',
 'tydarrius',
 'martavious',
 'wedad',
 'talayiah',
 'callin',
 'ah',
 'shamsudin',
 'stepahanie',
 'kabriel',
 'jarryd',
 'amrie',
 'jahoor',
 'ryusei',
 'brendaly',
 'sanil',
 'shael',
 'dequon',
 'ashanti',
 'saiunie',
 'kennyth',
 'sispal',
 'alterik',
 'maree',
 'shelanda',
 'lehana',
 'cherrill',
 'elspeth',
 'minal',
 'safinn',
 'schlinda',
 'jacon',
 'grabiel',
 'paraskevoula',
 'milferd',
 'dilraj',
 'vina',
 'robann',
 'redell',
 'pens',
 'dyian',
 'zymere',
 'jeadon',
 'nochum',
 'novali',
 'dumani',
 'rubylee',
 'damerion',
 'maks',
 'ishu',
 'thaliah',
 'maythel',
 'susanne',
 'marlyin',
 'leana',
 'gerritje',
 'yien',
 'alveta',
 'letterio',
 'lulia',
 'gumesindo',
 'tahneekah',
 'aavin',
 'raushan',
 'teri',
 'nichos',
 'brookelyne',
 'carmelo',
 'chalsey',
 'yasin',
 'buyli',
 'aubaney',
 'shara',
 'abdiqadir',
 'vasa',
 'madicyn',
 'nanthana',
 'ethelann',
 'khamal',
 'zytavious',
 'markavion',
 'kiler',
 'trishika',
 'mayra',
 'verlaine',
 'sydnee',
 'yerzy',
 'rivva',
 'charmon',
 'jayliz',
 'dianca',
 'sprague',
 'ashor',
 'jaylece',
 'chinue',
 'akide',
 'hilda',
 'smaragdi',
 'marjie',
 'idean',
 'jesean',
 'desare',
 'drej',
 'kashala',
 'ersell',
 'kierat',
 'gideon',
 'warwich',
 'meral',
 'donatina',
 'tasmia',
 'brindin',
 'shaoen',
 'ramee',
 'kayanda',
 'pantju',
 'archana',
 'milagro',
 'tamin',
 'shalyn',
 'takudzwanashe',
 'sivad',
 'rapheal',
 'elfriede',
 'juwahn',
 'mersine',
 'alexica',
 'abhinash',
 'pryor',
 'tagen',
 'ardis',
 'nagi',
 'hao',
 'tazewell',
 'kim',
 'brhianna',
 'haben',
 'jameisha',
 'rishvik',
 'bunda',
 'erfan',
 'benjamyn',
 'simpson',
 'vrisa',
 'baley',
 'sigh',
 'kayvon',
 'mardell',
 'acer',
 'melvynn',
 'phinley',
 'thomaz',
 'haiti',
 'oktober',
 'chandelle',
 'sehboob',
 'emilia',
 'jacine',
 'joanis',
 'nikkia',
 'makynleigh',
 'lawsen',
 'dennis',
 'callison',
 'sharrika',
 'marlianna',
 'mckynlee',
 'antonyo',
 'daravone',
 'glenton',
 'onassis',
 'vuthy',
 'ragnhild',
 'blaize',
 'hurlee',
 'tayri',
 'lourd',
 'shoshannah',
 'ellenmarie',
 'jotavious',
 'tasharnna',
 'elizabet',
 'fahd',
 'tyshay',
 'cassyann',
 'aodhan',
 'abedalrahman',
 'ryliegh',
 'learah',
 'halen',
 'akkni',
 'nymeria',
 'ajada',
 'eutimia',
 'melaki',
 'taijanae',
 'miriya',
 'elhadj',
 'trimaine',
 'dekiya',
 'tyneesha',
 'cael',
 'levie',
 'romellow',
 'lorelee',
 'aachal',
 'arianah',
 'fernetta',
 'marjuerite',
 'jeanett',
 'montasia',
 'nevaya',
 'brionie',
 'earmon',
 'kamaron',
 'jadenn',
 'yanaiza',
 'zenley',
 'ikechi',
 'drene',
 'westan',
 'bijon',
 'brenisha',
 'rhyson',
 'yanie',
 'polley',
 'taiyab',
 'laster',
 'lenise',
 'katilynn',
 'arein',
 'jennaka',
 'kalara',
 'jodeen',
 'upender',
 'minha',
 'cassonia',
 'azadeh',
 'dannen',
 'erdi',
 'margaret',
 'sharaya',
 'yiani',
 'kadafi',
 'trudie',
 'marechale',
 'diamond',
 'baylii',
 'johnda',
 'chynia',
 'doren',
 'rivaan',
 'catherine',
 'maye',
 'meaza',
 'readie',
 'tenayha',
 'joquita',
 'adirah',
 'muslimah',
 'sarah',
 ...]

In [246]:
# before joining again get array in df with longest length first
name_with_max = max(unique_train_names, key=len)
name_with_max

'polyentolyekmongtainh'

In [247]:
train_max_len = len(name_with_max)
train_max_len

21

In [248]:
num_unique_train_names = len(unique_train_names)
num_unique_train_names

104133

In [249]:
num_unique_test_names = len(unique_test_names)
num_unique_test_names

28467

In [250]:
X_trains

            name  gender
58421     enrike       0
44132       karo       0
6768       donna       0
104257   taimani       1
38115     abrial       1
...          ...     ...
97639   braizlee       1
95939      quali       0
152315    shivji       0
117952       amy       1
43567    dylanie       1

[124104 rows x 2 columns]

In [251]:
chars, counts = np.unique(series_to_1D_array(trains['name']), return_counts=True)
chars

array(['0', '8', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k',
       'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x',
       'y', 'z'], dtype='<U1')

In [252]:
counts

array([     5,      1, 132036,  10235,  16158,  23618,  86492,   4017,
         8368,  34523,  67789,  13292,  18557,  50257,  24788,  70348,
        31672,   5332,   2100,  52198,  36766,  29576,  16261,   9096,
         4236,   1587,  29658,   6837])

#### mapping each character to their respective indeces

In [253]:
char_to_idx = map_value_to_index(chars)
idx_to_char = map_value_to_index(chars, inverted=True)

In [254]:
char_to_idx('a')

In [255]:
char_to_idx('b')

#### Unknown or 'UNK' characters are mapped to 0

In [256]:
char_to_idx('#')

In [ ]:
trains['name'].apply(lambda name: [char_to_idx(char) for char in name])

In [24]:
# post means place padding of 0's on the tail or ending of the sequence
# and truncating removes the values of a sequence that is greater than the max length given
train_seqs_padded = pad_sequences(train_seqs, maxlen=train_max_len, padding='post', truncating='post')
train_seqs_padded

array([[  1865,      0,      0,      0],
       [ 10249,      0,      0,      0],
       [ 10250,      0,      0,      0],
       ...,
       [104215,      0,      0,      0],
       [104216,      0,      0,      0],
       [104217,      0,      0,      0]], dtype=int32)

In [25]:
# post means place padding of 0's on the tail or ending of the sequence
# and truncating removes the values of a sequence that is greater than the max length given
test_seqs_padded = pad_sequences(test_seqs, maxlen=train_max_len, padding='post', truncating='post')
test_seqs_padded

array([[  417,   548,     0,     0],
       [    0,     0,     0,     0],
       [18700,     0,     0,     0],
       ...,
       [    0,     0,     0,     0],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0]], dtype=int32)

In [26]:
Y_trains

2853      0
143300    0
111302    1
27499     0
84175     1
         ..
41993     0
97639     1
95939     0
117952    1
43567     1
Name: Gender, Length: 117815, dtype: int64

In [27]:
# at the same time one hot encode the y labels/classes
# and retrieve the number of unique labels of y
train_unique_labels = Y_trains.unique()
len_train_unique_labels = len(train_unique_labels)
len_train_unique_labels
# train_Y_oh = one_hot(Y_trains, depth=len_train_unique_labels).numpy()
# train_Y_oh

2

In [28]:
# at the same time one hot encode the y labels/classes
# and retrieve the number of unique labels of y
test_unique_labels = Y_tests.unique()
len_test_unique_labels = len(test_unique_labels)
len_test_unique_labels
# test_Y_oh = one_hot(Y_tests, depth=len_test_unique_labels).numpy()
# test_Y_oh

2

In [36]:
test_unique_labels

array([0, 1])

In [99]:
# includes oov words
vocab_len = len(word_to_index) + 1
# emb_dict, emb_vec_len = construct_embedding_dict('./embeddings/glove.twitter.27B.50d.txt', word_to_index)
# emb_matrix = construct_embedding_matrix(word_to_index, emb_dict, emb_vec_len)
lstm_model = load_lstm_model(train_max_len, vocab_len)

input shape: 4

In [100]:
# emb_matrix.shape

In [101]:
# emb_matrix.any(axis=1).sum()

In [102]:
lstm_model.summary()

Model: "fil-name-gender-lstm"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding-layer (Embedding)     │ (None, 4, 256)         │    26,679,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_20                │ (None, 256)            │       394,240 │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_20 (Dropout)            │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │           257 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_20 (Activation)      │ (None, 1)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 27,074,305 (103.28 MB)

 Trainable params: 27,074,305 (103.28 MB)

 Non-trainable params: 0 (0.00 B)

In [103]:
lstm_model.get_layer('embedding-layer').trainable

True

In [104]:
train_seqs_padded

array([[  1865,      0,      0,      0],
       [ 10249,      0,      0,      0],
       [ 10250,      0,      0,      0],
       ...,
       [104215,      0,      0,      0],
       [104216,      0,      0,      0],
       [104217,      0,      0,      0]], dtype=int32)

https://www.kaggle.com/code/shrikrishnaparab/gender-prediction-based-on-name-using-lstm

In [106]:
lstm_history = lstm_model.fit(
    train_seqs_padded, Y_trains,
    batch_size=64,
    epochs=10,
    validation_split=0.2,
)

Epoch 1/10
 110/1473 ━━━━━━━━━━━━━━━━━━━━ 2:45 121ms/step - auc_9: 0.5000 - binary_accuracy: 0.6077 - binary_crossentropy: 9.7545 - f1_score: 0.7560 - loss: 0.2464 - precision_9: 0.6077 - recall_9: 1.0000

KeyboardInterrupt:

In [ ]:
lstm_history