In [13]:
import pandas as pd
from utilities.preprocessors import preprocess, assign_gender
from utilities.visualizers import view_rows
from utilities.loaders import load_file

import os
from dotenv import load_dotenv
from pathlib import Path

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [14]:
# load environment variables path
env_dir = Path('../').resolve()
load_dotenv(os.path.join(env_dir, '.env'))

True

# load dataframe

In [15]:
profiles_dump = pd.read_csv('../documents/profiles_dump.csv', index_col=0)
profiles_dump.tail()

,conn_link,conn_name,gender,salutation,email,mobile_no,company_name
635,https://www.linkedin.com/in/gealynpafin/,Gealyn Pafin,NaN,NaN,NaN,0.0,NaN
636,https://www.linkedin.com/in/mitche-ajesta-rpm-...,"Mitche Ajesta, RPm",NaN,NaN,NaN,0.0,NaN
637,https://www.linkedin.com/in/katrina-leyva-997b...,Katrina Leyva,NaN,NaN,NaN,0.0,NaN
638,https://www.linkedin.com/in/archie-laranang-54...,Archie Laranang,NaN,NaN,NaN,0.0,NaN
639,https://www.linkedin.com/in/aloicius-justine-k...,Aloicius Justine Kochensparger,NaN,NaN,NaN,0.0,NaN

In [16]:
profiles_dump['conn_name'] = profiles_dump['conn_name'].apply(preprocess)
profiles_dump.head()

Dianna Marie Platero
Cams Cabungcal
Danniel Tongol
Kristia C.
Lorena Baez
Roma Doria Panaligan
Bryan O
Jose Marie Mangalino
Christopher Gonzalez
Rodella "Leng" Tolentino
John Marin Moreno Clsswb
Ma. Joyce Armia
Jemel Lovino
Elaine Marion Edaño
Renel Tibo
Regine Calibay
Kams Casas Rodriguez
Gem Anonuevo
Lisette Jane Lumberio
Aubrey Lou Maldonado
Maria Zarina Antonio
Ella Tariman
Audrea Marie Boto
Baby Jean Arandia
Abegail Jean Bañez
Jill Marian
John Dominic Ocampo
Oliver Sison
Jessica Galang
Kiara Aldover
Ariel Cole
Rodolfo Cantongos
Kei Bryan Dusaban
Krissia Geramie Mapatac
Reselyn Jane Alonzo
Sarra Joy Del Rosario
Colene Joice De Leon
Siara Sangalang
Eunice Pamela Canilang
Karl Monteclaro
Catherine Lavadia
Anna Carmela Macam
Lovely Lamptey
Elvin Eligado
Janine Erika Manzala
Sarrah Dulguime
Zaira Cadampog
Jema Flor Basilio
Elaiza Wileman
Kean Jardin
Kenneth Ramil
Camille Catigay
Jael Nisay
Zen Athena Magdasoc
Angeline Nicole Sicup Tura
Jazeinka Isabella Valdez Pineda
Ma. Katrina Gracia Sedanto
El Batuna
Mark Kevin Garcia
Arissa Miles Rodriguez
Quincy Erika Ramos
Marco Caspillan
Lawrence Gatpandan
Anabelle Millena
Leila Isabel Villamor
Charisse Ivan De Leon
Raphael Ventura
Joylyn Agan
Rodalyn Orale
Tine Kris
Mac Gilfred Uy
Christine Mae Linatoc
Jackie Belmonte
Julian Eric Damian
Robert Jethro Enriquez
Mikaela Leigh Padrelanan
Jhon Remilyn Unciano
Jamie Jane Quijano Boneo
Prince Angelo Torres
Roselyn Achas
Badj Cañero
Beatriz Paula Oronan
Enrisa Lara
Jade Ancajas
Currie Orpiano
Anjelica Joice Pantig Amparo
Marlon De Mesa
Mary Ruth Sanchez Benzon
Tin Salmurin
Russell Rogan
Karl Marx Galado
Danielle Castillo
Mikee Torre
Kate Collie Santos
Trexx Gan
Az Cabrera Msp Chrp
John Bendix Mendoza
Rain Acuesta Chrp
Ashley Sadine Djandaghi Bautista
Nowrine Shiena Hossen
John Patrick Sasan Clsswb Cspe
Carlo Estoconing
Simon Kim Hirondo
Carmelo P. Litanon Ii
Kako Usi
Claire Montiel
Justine Cunanan
Jorge Pitong
Cherry Lou Haluag
Tristan Jerick Reyes
Patrick Malibunas
Cess Balbuena
Maria Christinapaz Parker
Don Refuerzo
Glenn De Guzman
Jv Nebres
Pol Tahoynon
Justin Edward Fernandez
John Laurence Sarmiento
Janeen Lei Nell Alar
Ralph John Mijares
Christian Joseph Garlitos
Alyssa Palamiano
Nukie Germanotta
Paulene Hazelen Gornes
Patricia Billones
Marianne Diocares
Louisze Jhaede Sanchez
Ryssel Joy Tumayan
April Pie Tayong
Revin Aves Naing
Kenn Dominic Macarat
Erika Ray Ramirez
Angelica Salandanan
Remegio Madarang Jr
Meliza Anne Kionisala
Pamela Pamonag
Ralph Marwin Loyola
Emilyn Alonsagay
Jayrah Cruzado
Helen Wong
Clarisse Buenconsejo
Ma. Sophia Victoria Mizon
Angelica Mamaid
Blessilda Catap
Equel N.
Kryzel Ann Oja
Princess Miñon
Justine Dela Peña
Christian Gabriel Villegas
Kyle Maverick Schaefer
Maricar B.
Kamille Gonzales
Joy Solana
Hannah Alteza
Anthony Louissetien Morales
Marjorie Fonseca
Rochelle Miguela Angeles
Mikhaela Malabanan
Rizamae Milet Austria
Tel Cadiang
Trisha Marie Flores
Jace Villamor
Abigail Lyle Arquero
Mary Grace Munoz
Stefhanie Sapeda
Shiena Saballo
Maria Katrina Cuenca
Yvette Lacson
Katrina Angela Espiritu
Rc Malubo
Kristian Riz Canama
Lyndon Ramo Jr
Leslie Saspa
Kristine Castilla
Nina Lanante
Wilma Isidro
Rizziane Frago
Angelica Marie Wida
Tina Caluya
Elaine Villa Balatero
Kristelle Ann Villalobos
Angel Amosin
Angely May Parel
Dhea Pineda
Karina Manzanilla
Kristine Obsioma
Joemari Rios
Angelika Barriga
Jerrome Alcarmen
Maria Althea Espinosa
Oliver Gabuna
Mae Mira
Megan Rivera
Mary Andrea Jugo
Cheska Tolosa
Zhaira Andrea Manglo
Zoan Cris Acaso
Jayson Lugtu
Ricamay Ballad
Marvic Marbb Calindro
Veronica De Leon
Rodny Selorio
Madelaine Ann Bengero
Anne Mariano
Mary Lou Gobrin
Glaiza Español
Micol Maglalang
Rochemey Ortiga
Jenny Magsino
Francis Mah
Yhing Miranda Manundo
Rhuskine Dimla
Kathleen Kate Odulio
Maria Rouchelle Manaig
Sueshem Tudtud
Xavier Pascual
Ana Kathleen Adoc
Rizza Indig
Anton Roxas
Judy Cayabyab
Aby Aquino
Nancy Niu
Khaye Banguis
Joy Rivera
Chaster Joy Leones
Romina Morallos
Jem Roche Ballesteros
Harsha Bachani
Jess Soriao
Daryl Anne Centura
Kristine G.
Icko Perez
Beatrice Umila
Roseann Cisnero
Reggie Pascual
Julia Villaos
Princess Dalumpines
Triescia Capinpin
Airene Ramilo
Trischia Mae Cabatuan
Alyssa Marie Lansangan
Joshua Kyle S.
Wilma David
Arline Joannah Suniga
Kamilah Del Rosario
Ann Josenen Regencia
Jayson Callejo
Kyle Dominique Agramon
Ayla Paguio
Renz Cristina Garbin
Maricel Torres
Allexa Contreras
Joshua Juta
Anna Paulyn Pagunsan
Mj Visitacion
Romel Sayomac
Gerald Jetro Abuyan
Mary Rose Balingit
Ian Añonuevo
Herbert Joey Tuazon
Ma. Thelma Flores
Kimberly Montillano
Marie Centural
Jan Marie Beltran
Franki
Jonalyn Ebit
Del V.
Paolo Galve
Michelle Recaña
Joey Rose Briñes
Hazel Kelley
Roma Ramilo
Celine F
Karisse Bernille Labarda
Alvin Troy Catacutan
Claire Anne Oliman
Mark Florian Solano
Therese Ayra Malones
Mark Andrew Mercado
Leo Rueda
Eliza Joy Fran
Ma. Danica Camacho
Zhaira Cosep
Ann Marimar Porquez
Casey Grandeza
Richard Justine Corporal
Joy Amio
Jeff Macapobre
Diane Grace Dayap
Hannah Camille Santos
Angelica Kolambil
Ed Patco
Roy Alegado
Amor Maligat
Ivy Paragas
Czayra Gabrielle Reyes
Liz Cruz
Christine Joy Embodo
Sergius Paulo Vidallon
Paula Marie Gallian
Marissa Esmeria
Princess Helen Delos Santos
Cherry Lou Quicoy
John Louie Del Rosario
Lovelyn Madriaga
Jan De Guzman
Rica Niña Camangyan
Gian Karlo Legaspi
Diana Atienza
Catherine Mariano
Angelo Dipay
John Carlo Lim
Angeline Bona Naron
Loralie Felin
Darwin Gasacao
Kim Malibiran
Elyssa Joy Peraz
Claire Chavez
Hector Sumaoang
Aira Magallon
Tito Pascual
Andrea Vasily Gallardo
Aldrin Astrande
Niela Centeno
Ben Trapal
Kit Solis
Florence Hipolito
Ma. Elda Lorca
Francis Charles Damondamon
Francesca Moralejo
Peter Jr. Hizon
Raquel Villafuerte
John Emil Adriano
Wendell Villareal Guidoriagao
Ron Richard Ramirez
Raven Isaac
Kristianne Ysabele Capiral
Mac Adornado
Dianne Kristine Ansula
Paul Andrew Taboada
Jeryl Delaganar
Beverly Lariosa
Patricia Amor Pam
Maria Anneli Rose Suarez
Khim Mariez Geronimo
Beverly Monungolh
Rhina Hipolito
Nina Graye Sean Lanante
Khris Jan Larce
Diane Olano
Ana Marie Simbajon
Jb Dela Cruz
Bernadette Esteban
Randell Cortez
Maze Enrile Rivera
Marialyn Real
Nicole Capales
April Mimi Marcelo
Eric Jayson Fombo
Juan De Leon
Richmond Babasa
Regan Villacastin
Ishmael Joshua Tungol
Al Christian Agngarayngay
John Carlo Sarcia
Faye Emerald Dela Cruz
Kijo Menor
Gerald Renz Sevilla
Niña Katrina Coronel
Allan Repalda
Paola Teopiz
Quin Lawrence Sibonga
Ivan Acuna
Joan Sakuma
Venus Ozarraga
Alyssa Kirra Macarilay
Clarissa Meneses Chrp
John Jason Odquier
Rochelle Bulan
Van Cayabat
Noel Gamalindo
Ameera Valdez
Shiela Roaring
Patrick Jovie Alaban
Ericka Mae Tubog
Patricia Kate Concepcion
John Vincent Tan
Leroid Manahan
Silviya Georgieva
Jam Marquez Diola
Kate Santos
Christian Lumanog
Mary Genova
Dexter Tiamzon
Elizabeth Anne Cuvin King
Jhunelle Erica Abrigo
Giza Marie Miciano
Camille Gandol
Ma Samantha Nicole Villanueva
Bryan Pattaui
John Reneeric Hernandez
Entee Casanova
Jex Ashley Antonio
Rae Ramirez Chrp
Samantha Ma. Geriline Bagorio
Jenevieve Daz
Alfred Tolentino
Christopher Villareal
Raymond De Vera
Joshua Santiago
Michelle Morales
Aiza Ricohermoso
Sam S.A. Sornito
Rommel Yumang
Roselyn Montances
Tristan Ivan Chong
Regent Sula Gacusan
Jhomer Diaz
Emmanuel Alfonso Ciencia
Mary Ann Leonida
Christine Dianne Ortiz
Ciara Domingo
John Paul Bandong
Miks Yalong
Hp Diaz
Marie Nazareno Reyes
Alyssa Jean Sonza
Camille Inovio
Thea Marivee Rivera
Marc Stephen Reyes
Meredith Nichole Escario
Christian Alicog
Florence Benette Gallego
Diosdado Hawang
Racel Leihart Patricio
Karl Laurezo
Jeanne Jessan Aguilar
Max Evangelista
John Leignard Ragasa
Ma. Messy Carmona
Hannah Coleen Nacion
Marlyn Mag Isa
Toty Ross Peregrino
Dyan Marie Bautista
Al D.
Ma. Faye Roz
Louise Faeldonea
Thomas Bernabe
Niño July Mabilangan
Dianne Ruth Malinao
Princess Morfe
Jc Digamon
Lady Charo Cadiz
Mp Baba
Noelle Noey Pangilinan
John Kervee Samonte
Cristell Dioneda
Pamela Nadine Alvaro Baldovino
Leslie Aquino
Joanna Custodio Estrada
Gilberly Joy Ablao
Steffi Jan Padilla
May Buendia Palabrica
Mark Daniel Povadora
Jona Torres Benzon
Elaine Rose Malayo
Krizzia Aldovino
Angelica Fernandez
Carla Mico
Joanna Isabel Montealegre
Michelle C.
Rhoivin Mendoza Ilagan
Ron Mulleda
Rinna Lizza
Maria Arabelle Olegario
Lester John Pacaco
Pamela Bianca Co
Alyanna Monica Coladilla
Arguelito Solpico Jr.
Angello Poblete
Quincey Jugo
Severly Suzie Oka
Angela Alcantara
Maria Lourdes Des Gomez Alem Chrp
Carl Javier
Aira Danielle Cacho
Nickie Rose Arpon
Mikee Del Prado
Kathrina Telan
Andrea Nicole Odones
Leoric Pabila
Tricia Gayle Famadico
Jomar Lerios
Krizzia Mercado
Noel Tarranco
Kimberly Jane Marcial
Ina Buena
Marvee Juan
Clint Villanueva
Gybon Bajada
Jerome Soriano
Sarah Jane Migueh
Cindy Caseda
Margarett Racho
Dale Gilbert Galindez
John Vincent Sy
Marc Jacob Artajos
Katreena Marisse Dueñas
Meng Raymundo
Nikko De La Cerna
Jezreel Czarina Saygo
Janine Alexis Javier
Marie Rhona Maleen Carandang
Elaine Padilla
Jessica Louise Saldaña
Ivan Villaflor
Don Manongsong
Paula Del Rosario Casas
Lloyd Bathan
Gela Ga Ang
Marc Christian Palisoc
Krystel Marie Santiago
Andrea Bianca Punzal
Queenie Onipa
Philip Azur
Natasha Myrtle Sasaki
Sherilyn Bejar
Frederick Almacen
Maries Tan
David Hofer
Franchesca Oliman
Jogar Bathan
Charina Ibo
Sophia Ysabela Angeles
Tobit Ibañez
Ericka Joyce Bea
John Panganoron
Kimberly Buena
Maria Clarissa Felipe
Geroel James Salvador
Andrea Justiniano
Christian Glendale Fernandez
Dee Marie Joy Dada
Aloha Ferrer
Cel Rodriguez
Mirachael Mendoza
Miggy Sy
Arianne Faith Pagapulan
Gillian Adria Caballero
Jamaica Marie Gaytano
Paolo Rafael Hulog
Eumir Mondok
Cheryl Dela Cruz
Lovely San Juan
Pamela Yasmin Buluran
Deanne Fernando
Joey A.
Micka Alcovindas
Fernchesca Aquino
Diojam Etcobanez
Jose Maria Galang
Coleen Gapas
Bran Cruz
Mary Joy Pagulayan
Mabel Perez
Marvin Samaniego
Shane Calub
Wilma Isidro
Shae Bernabe
Carlo Angelo Baniaga
Ilyn Oso
Hasel Francisco
Raleen Aguilar
Aira Batang
Aaron Mitchel Ancheta
Janine Espanol
James Madriaga
Jhayz Gratuito
Sean Paolo Elarco
Jera Aira Santiago
Romel Buenavista
Christell Nicole Barquin
Shainna Delgado
Sarheene Khattab
Joseph Joshua Donato
Marcus Ace Gaitan
Marih Jomoc
Kristine Angela Caguiat
Gine Garcia
Mia Baylon
Al Valencia
Michelle Matanguihan
Danesa Sotomayor Pulido
John Carlo Martinez
Jan Maureen Ariota
Liza Margaret Caraos
Carla Chavez
Demirene Hentoloro
Arthel Espiritu Santo
Arvin Joseph De Leon
Beejey Jarabe
Jobelyn Estrella
Arvin Bajar
Maan Sestona
John Christian Mateo
Nerissa Anne Palo
Diana Hilario
Lady Joan Cabilino
Trish Teodosio
Nairie Solante
Johanna Perez
Cristien Angel Mae Bernabe
Gene Reinier Nieto
Christine Joyce Sapoco
Kaye Peña
John Padua
Khyle Zybille De Leon
Greg Canillas Reyes
Mehjebin Khan
Dagami Padillo
Nina Stephanie Tanawit
Christian Cachola Chrp
Benilda Diaz
Yohan Nicole Aroja
Julius Lee Bacani
Angelicca Sadanguel
Avi O
Raul Badon
Cyril Garcia
Jason Palinis
Efren Flores
Mary Joy Zamudio
James Topacio
Grace Ysabelle Pascual
Gealyn Pafin
Mitche Ajesta
Katrina Leyva
Archie Laranang
Aloicius Justine Kochensparger

,conn_link,conn_name,gender,salutation,email,mobile_no,company_name
0,https://www.linkedin.com/in/diannamarieplatero/,Dianna Marie Platero,NaN,NaN,NaN,0.0,NaN
1,https://www.linkedin.com/in/cams-cabungcal-865...,Cams Cabungcal,NaN,NaN,NaN,0.0,NaN
2,https://www.linkedin.com/in/danniel-tongol-440...,Danniel Tongol,NaN,NaN,NaN,0.0,NaN
3,https://www.linkedin.com/in/kristia-c-92858b135/,Kristia C.,NaN,NaN,NaN,0.0,NaN
4,https://www.linkedin.com/in/lorenapanganibanbaez/,Lorena Baez,NaN,NaN,NaN,0.0,NaN

In [17]:
profiles_dump.iloc[2]

conn_link       https://www.linkedin.com/in/danniel-tongol-440...
conn_name                                          Danniel Tongol
gender                                                        NaN
salutation                                                    NaN
email                                                         NaN
mobile_no                                                     0.0
company_name                                                  NaN
Name: 2, dtype: object

In [18]:
view_rows(profiles_dump, 'conn_name')

Dianna Marie Platero
Cams Cabungcal
Danniel Tongol
Kristia C.
Lorena Baez
Roma Doria Panaligan
Bryan O
Jose Marie Mangalino
Christopher Gonzalez
Rodella "Leng" Tolentino
John Marin Moreno Clsswb
Ma. Joyce Armia
Jemel Lovino
Elaine Marion Edaño
Renel Tibo
Regine Calibay
Kams Casas Rodriguez
Gem Anonuevo
Lisette Jane Lumberio
Aubrey Lou Maldonado
Maria Zarina Antonio
Ella Tariman
Audrea Marie Boto
Baby Jean Arandia
Abegail Jean Bañez
Jill Marian
John Dominic Ocampo
Oliver Sison
Jessica Galang
Kiara Aldover
Ariel Cole
Rodolfo Cantongos
Kei Bryan Dusaban
Krissia Geramie Mapatac
Reselyn Jane Alonzo
Sarra Joy Del Rosario
Colene Joice De Leon
Siara Sangalang
Eunice Pamela Canilang
Karl Monteclaro
Catherine Lavadia
Anna Carmela Macam
Lovely Lamptey
Elvin Eligado
Janine Erika Manzala
Sarrah Dulguime
Zaira Cadampog
Jema Flor Basilio
Elaiza Wileman
Kean Jardin
Kenneth Ramil
Camille Catigay
Jael Nisay
Zen Athena Magdasoc
Angeline Nicole Sicup Tura
Jazeinka Isabella Valdez Pineda
Ma. Katrina Gracia Sedanto
El Batuna
Mark Kevin Garcia
Arissa Miles Rodriguez
Quincy Erika Ramos
Marco Caspillan
Lawrence Gatpandan
Anabelle Millena
Leila Isabel Villamor
Charisse Ivan De Leon
Raphael Ventura
Joylyn Agan
Rodalyn Orale
Tine Kris
Mac Gilfred Uy
Christine Mae Linatoc
Jackie Belmonte
Julian Eric Damian
Robert Jethro Enriquez
Mikaela Leigh Padrelanan
Jhon Remilyn Unciano
Jamie Jane Quijano Boneo
Prince Angelo Torres
Roselyn Achas
Badj Cañero
Beatriz Paula Oronan
Enrisa Lara
Jade Ancajas
Currie Orpiano
Anjelica Joice Pantig Amparo
Marlon De Mesa
Mary Ruth Sanchez Benzon
Tin Salmurin
Russell Rogan
Karl Marx Galado
Danielle Castillo
Mikee Torre
Kate Collie Santos
Trexx Gan
Az Cabrera Msp Chrp
John Bendix Mendoza
Rain Acuesta Chrp
Ashley Sadine Djandaghi Bautista
Nowrine Shiena Hossen
John Patrick Sasan Clsswb Cspe
Carlo Estoconing
Simon Kim Hirondo
Carmelo P. Litanon Ii
Kako Usi
Claire Montiel
Justine Cunanan
Jorge Pitong
Cherry Lou Haluag
Tristan Jerick Reyes
Patrick Malibunas
Cess Balbuena
Maria Christinapaz Parker
Don Refuerzo
Glenn De Guzman
Jv Nebres
Pol Tahoynon
Justin Edward Fernandez
John Laurence Sarmiento
Janeen Lei Nell Alar
Ralph John Mijares
Christian Joseph Garlitos
Alyssa Palamiano
Nukie Germanotta
Paulene Hazelen Gornes
Patricia Billones
Marianne Diocares
Louisze Jhaede Sanchez
Ryssel Joy Tumayan
April Pie Tayong
Revin Aves Naing
Kenn Dominic Macarat
Erika Ray Ramirez
Angelica Salandanan
Remegio Madarang Jr
Meliza Anne Kionisala
Pamela Pamonag
Ralph Marwin Loyola
Emilyn Alonsagay
Jayrah Cruzado
Helen Wong
Clarisse Buenconsejo
Ma. Sophia Victoria Mizon
Angelica Mamaid
Blessilda Catap
Equel N.
Kryzel Ann Oja
Princess Miñon
Justine Dela Peña
Christian Gabriel Villegas
Kyle Maverick Schaefer
Maricar B.
Kamille Gonzales
Joy Solana
Hannah Alteza
Anthony Louissetien Morales
Marjorie Fonseca
Rochelle Miguela Angeles
Mikhaela Malabanan
Rizamae Milet Austria
Tel Cadiang
Trisha Marie Flores
Jace Villamor
Abigail Lyle Arquero
Mary Grace Munoz
Stefhanie Sapeda
Shiena Saballo
Maria Katrina Cuenca
Yvette Lacson
Katrina Angela Espiritu
Rc Malubo
Kristian Riz Canama
Lyndon Ramo Jr
Leslie Saspa
Kristine Castilla
Nina Lanante
Wilma Isidro
Rizziane Frago
Angelica Marie Wida
Tina Caluya
Elaine Villa Balatero
Kristelle Ann Villalobos
Angel Amosin
Angely May Parel
Dhea Pineda
Karina Manzanilla
Kristine Obsioma
Joemari Rios
Angelika Barriga
Jerrome Alcarmen
Maria Althea Espinosa
Oliver Gabuna
Mae Mira
Megan Rivera
Mary Andrea Jugo
Cheska Tolosa
Zhaira Andrea Manglo
Zoan Cris Acaso
Jayson Lugtu
Ricamay Ballad
Marvic Marbb Calindro
Veronica De Leon
Rodny Selorio
Madelaine Ann Bengero
Anne Mariano
Mary Lou Gobrin
Glaiza Español
Micol Maglalang
Rochemey Ortiga
Jenny Magsino
Francis Mah
Yhing Miranda Manundo
Rhuskine Dimla
Kathleen Kate Odulio
Maria Rouchelle Manaig
Sueshem Tudtud
Xavier Pascual
Ana Kathleen Adoc
Rizza Indig
Anton Roxas
Judy Cayabyab
Aby Aquino
Nancy Niu
Khaye Banguis
Joy Rivera
Chaster Joy Leones
Romina Morallos
Jem Roche Ballesteros
Harsha Bachani
Jess Soriao
Daryl Anne Centura
Kristine G.
Icko Perez
Beatrice Umila
Roseann Cisnero
Reggie Pascual
Julia Villaos
Princess Dalumpines
Triescia Capinpin
Airene Ramilo
Trischia Mae Cabatuan
Alyssa Marie Lansangan
Joshua Kyle S.
Wilma David
Arline Joannah Suniga
Kamilah Del Rosario
Ann Josenen Regencia
Jayson Callejo
Kyle Dominique Agramon
Ayla Paguio
Renz Cristina Garbin
Maricel Torres
Allexa Contreras
Joshua Juta
Anna Paulyn Pagunsan
Mj Visitacion
Romel Sayomac
Gerald Jetro Abuyan
Mary Rose Balingit
Ian Añonuevo
Herbert Joey Tuazon
Ma. Thelma Flores
Kimberly Montillano
Marie Centural
Jan Marie Beltran
Franki
Jonalyn Ebit
Del V.
Paolo Galve
Michelle Recaña
Joey Rose Briñes
Hazel Kelley
Roma Ramilo
Celine F
Karisse Bernille Labarda
Alvin Troy Catacutan
Claire Anne Oliman
Mark Florian Solano
Therese Ayra Malones
Mark Andrew Mercado
Leo Rueda
Eliza Joy Fran
Ma. Danica Camacho
Zhaira Cosep
Ann Marimar Porquez
Casey Grandeza
Richard Justine Corporal
Joy Amio
Jeff Macapobre
Diane Grace Dayap
Hannah Camille Santos
Angelica Kolambil
Ed Patco
Roy Alegado
Amor Maligat
Ivy Paragas
Czayra Gabrielle Reyes
Liz Cruz
Christine Joy Embodo
Sergius Paulo Vidallon
Paula Marie Gallian
Marissa Esmeria
Princess Helen Delos Santos
Cherry Lou Quicoy
John Louie Del Rosario
Lovelyn Madriaga
Jan De Guzman
Rica Niña Camangyan
Gian Karlo Legaspi
Diana Atienza
Catherine Mariano
Angelo Dipay
John Carlo Lim
Angeline Bona Naron
Loralie Felin
Darwin Gasacao
Kim Malibiran
Elyssa Joy Peraz
Claire Chavez
Hector Sumaoang
Aira Magallon
Tito Pascual
Andrea Vasily Gallardo
Aldrin Astrande
Niela Centeno
Ben Trapal
Kit Solis
Florence Hipolito
Ma. Elda Lorca
Francis Charles Damondamon
Francesca Moralejo
Peter Jr. Hizon
Raquel Villafuerte
John Emil Adriano
Wendell Villareal Guidoriagao
Ron Richard Ramirez
Raven Isaac
Kristianne Ysabele Capiral
Mac Adornado
Dianne Kristine Ansula
Paul Andrew Taboada
Jeryl Delaganar
Beverly Lariosa
Patricia Amor Pam
Maria Anneli Rose Suarez
Khim Mariez Geronimo
Beverly Monungolh
Rhina Hipolito
Nina Graye Sean Lanante
Khris Jan Larce
Diane Olano
Ana Marie Simbajon
Jb Dela Cruz
Bernadette Esteban
Randell Cortez
Maze Enrile Rivera
Marialyn Real
Nicole Capales
April Mimi Marcelo
Eric Jayson Fombo
Juan De Leon
Richmond Babasa
Regan Villacastin
Ishmael Joshua Tungol
Al Christian Agngarayngay
John Carlo Sarcia
Faye Emerald Dela Cruz
Kijo Menor
Gerald Renz Sevilla
Niña Katrina Coronel
Allan Repalda
Paola Teopiz
Quin Lawrence Sibonga
Ivan Acuna
Joan Sakuma
Venus Ozarraga
Alyssa Kirra Macarilay
Clarissa Meneses Chrp
John Jason Odquier
Rochelle Bulan
Van Cayabat
Noel Gamalindo
Ameera Valdez
Shiela Roaring
Patrick Jovie Alaban
Ericka Mae Tubog
Patricia Kate Concepcion
John Vincent Tan
Leroid Manahan
Silviya Georgieva
Jam Marquez Diola
Kate Santos
Christian Lumanog
Mary Genova
Dexter Tiamzon
Elizabeth Anne Cuvin King
Jhunelle Erica Abrigo
Giza Marie Miciano
Camille Gandol
Ma Samantha Nicole Villanueva
Bryan Pattaui
John Reneeric Hernandez
Entee Casanova
Jex Ashley Antonio
Rae Ramirez Chrp
Samantha Ma. Geriline Bagorio
Jenevieve Daz
Alfred Tolentino
Christopher Villareal
Raymond De Vera
Joshua Santiago
Michelle Morales
Aiza Ricohermoso
Sam S.A. Sornito
Rommel Yumang
Roselyn Montances
Tristan Ivan Chong
Regent Sula Gacusan
Jhomer Diaz
Emmanuel Alfonso Ciencia
Mary Ann Leonida
Christine Dianne Ortiz
Ciara Domingo
John Paul Bandong
Miks Yalong
Hp Diaz
Marie Nazareno Reyes
Alyssa Jean Sonza
Camille Inovio
Thea Marivee Rivera
Marc Stephen Reyes
Meredith Nichole Escario
Christian Alicog
Florence Benette Gallego
Diosdado Hawang
Racel Leihart Patricio
Karl Laurezo
Jeanne Jessan Aguilar
Max Evangelista
John Leignard Ragasa
Ma. Messy Carmona
Hannah Coleen Nacion
Marlyn Mag Isa
Toty Ross Peregrino
Dyan Marie Bautista
Al D.
Ma. Faye Roz
Louise Faeldonea
Thomas Bernabe
Niño July Mabilangan
Dianne Ruth Malinao
Princess Morfe
Jc Digamon
Lady Charo Cadiz
Mp Baba
Noelle Noey Pangilinan
John Kervee Samonte
Cristell Dioneda
Pamela Nadine Alvaro Baldovino
Leslie Aquino
Joanna Custodio Estrada
Gilberly Joy Ablao
Steffi Jan Padilla
May Buendia Palabrica
Mark Daniel Povadora
Jona Torres Benzon
Elaine Rose Malayo
Krizzia Aldovino
Angelica Fernandez
Carla Mico
Joanna Isabel Montealegre
Michelle C.
Rhoivin Mendoza Ilagan
Ron Mulleda
Rinna Lizza
Maria Arabelle Olegario
Lester John Pacaco
Pamela Bianca Co
Alyanna Monica Coladilla
Arguelito Solpico Jr.
Angello Poblete
Quincey Jugo
Severly Suzie Oka
Angela Alcantara
Maria Lourdes Des Gomez Alem Chrp
Carl Javier
Aira Danielle Cacho
Nickie Rose Arpon
Mikee Del Prado
Kathrina Telan
Andrea Nicole Odones
Leoric Pabila
Tricia Gayle Famadico
Jomar Lerios
Krizzia Mercado
Noel Tarranco
Kimberly Jane Marcial
Ina Buena
Marvee Juan
Clint Villanueva
Gybon Bajada
Jerome Soriano
Sarah Jane Migueh
Cindy Caseda
Margarett Racho
Dale Gilbert Galindez
John Vincent Sy
Marc Jacob Artajos
Katreena Marisse Dueñas
Meng Raymundo
Nikko De La Cerna
Jezreel Czarina Saygo
Janine Alexis Javier
Marie Rhona Maleen Carandang
Elaine Padilla
Jessica Louise Saldaña
Ivan Villaflor
Don Manongsong
Paula Del Rosario Casas
Lloyd Bathan
Gela Ga Ang
Marc Christian Palisoc
Krystel Marie Santiago
Andrea Bianca Punzal
Queenie Onipa
Philip Azur
Natasha Myrtle Sasaki
Sherilyn Bejar
Frederick Almacen
Maries Tan
David Hofer
Franchesca Oliman
Jogar Bathan
Charina Ibo
Sophia Ysabela Angeles
Tobit Ibañez
Ericka Joyce Bea
John Panganoron
Kimberly Buena
Maria Clarissa Felipe
Geroel James Salvador
Andrea Justiniano
Christian Glendale Fernandez
Dee Marie Joy Dada
Aloha Ferrer
Cel Rodriguez
Mirachael Mendoza
Miggy Sy
Arianne Faith Pagapulan
Gillian Adria Caballero
Jamaica Marie Gaytano
Paolo Rafael Hulog
Eumir Mondok
Cheryl Dela Cruz
Lovely San Juan
Pamela Yasmin Buluran
Deanne Fernando
Joey A.
Micka Alcovindas
Fernchesca Aquino
Diojam Etcobanez
Jose Maria Galang
Coleen Gapas
Bran Cruz
Mary Joy Pagulayan
Mabel Perez
Marvin Samaniego
Shane Calub
Wilma Isidro
Shae Bernabe
Carlo Angelo Baniaga
Ilyn Oso
Hasel Francisco
Raleen Aguilar
Aira Batang
Aaron Mitchel Ancheta
Janine Espanol
James Madriaga
Jhayz Gratuito
Sean Paolo Elarco
Jera Aira Santiago
Romel Buenavista
Christell Nicole Barquin
Shainna Delgado
Sarheene Khattab
Joseph Joshua Donato
Marcus Ace Gaitan
Marih Jomoc
Kristine Angela Caguiat
Gine Garcia
Mia Baylon
Al Valencia
Michelle Matanguihan
Danesa Sotomayor Pulido
John Carlo Martinez
Jan Maureen Ariota
Liza Margaret Caraos
Carla Chavez
Demirene Hentoloro
Arthel Espiritu Santo
Arvin Joseph De Leon
Beejey Jarabe
Jobelyn Estrella
Arvin Bajar
Maan Sestona
John Christian Mateo
Nerissa Anne Palo
Diana Hilario
Lady Joan Cabilino
Trish Teodosio
Nairie Solante
Johanna Perez
Cristien Angel Mae Bernabe
Gene Reinier Nieto
Christine Joyce Sapoco
Kaye Peña
John Padua
Khyle Zybille De Leon
Greg Canillas Reyes
Mehjebin Khan
Dagami Padillo
Nina Stephanie Tanawit
Christian Cachola Chrp
Benilda Diaz
Yohan Nicole Aroja
Julius Lee Bacani
Angelicca Sadanguel
Avi O
Raul Badon
Cyril Garcia
Jason Palinis
Efren Flores
Mary Joy Zamudio
James Topacio
Grace Ysabelle Pascual
Gealyn Pafin
Mitche Ajesta
Katrina Leyva
Archie Laranang
Aloicius Justine Kochensparger

In [19]:
# gender_api_key = os.environ['GENDER_API_KEY']
# profiles_dump['gender'] = profiles_dump[['conn_name', 'gender']].apply(assign_gender, axis=1, args=(gender_api_key,))

In [20]:
# profiles_dump['salutation'] = profiles_dump['gender'].apply(lambda gender: 'Ms.' if gender == 'female' else 'Sir.' if gender == 'male' else '')

In [21]:
profiles_dump

,conn_link,conn_name,gender,salutation,email,mobile_no,company_name
0,https://www.linkedin.com/in/diannamarieplatero/,Dianna Marie Platero,NaN,NaN,NaN,0.0,NaN
1,https://www.linkedin.com/in/cams-cabungcal-865...,Cams Cabungcal,NaN,NaN,NaN,0.0,NaN
2,https://www.linkedin.com/in/danniel-tongol-440...,Danniel Tongol,NaN,NaN,NaN,0.0,NaN
3,https://www.linkedin.com/in/kristia-c-92858b135/,Kristia C.,NaN,NaN,NaN,0.0,NaN
4,https://www.linkedin.com/in/lorenapanganibanbaez/,Lorena Baez,NaN,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...
635,https://www.linkedin.com/in/gealynpafin/,Gealyn Pafin,NaN,NaN,NaN,0.0,NaN
636,https://www.linkedin.com/in/mitche-ajesta-rpm-...,Mitche Ajesta,NaN,NaN,NaN,0.0,NaN
637,https://www.linkedin.com/in/katrina-leyva-997b...,Katrina Leyva,NaN,NaN,NaN,0.0,NaN
638,https://www.linkedin.com/in/archie-laranang-54...,Archie Laranang,NaN,NaN,NaN,0.0,NaN
639,https://www.linkedin.com/in/aloicius-justine-k...,Aloicius Justine Kochensparger,NaN,NaN,NaN,0.0,NaN

In [22]:
view_rows(profiles_dump, 'gender')

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [23]:
# view_rows(profiles_dump, 'salutation')

In [24]:
profiles_dump.to_csv('../documents/profiles_dump.csv')

In [30]:
conn_info = pd.read_csv('../documents/conn_info.csv')

True

In [ ]:
pd.isnull(conn_info.loc[0, 'email'])

In [31]:
pd.isnull(conn_info.loc[0, 'mobile_no'])

False

In [33]:
conn_info.loc[0, 'mobile_no']

0

In [32]:
pd.isnull(conn_info.loc[0, 'company_name'])

True