In [57]:
import pandas as pd
from utilities.preprocessors import preprocess, assign_gender
from utilities.visualizers import view_rows
from utilities.loaders import load_file

import os
from dotenv import load_dotenv
from pathlib import Path

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [58]:
# load environment variables path
env_dir = Path('../').resolve()
load_dotenv(os.path.join(env_dir, '.env'))

True

# load dataframe

In [59]:
conn_info = pd.read_csv('../documents/conn_info.csv', index_col=0)
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,NaN,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,NaN,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,NaN,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,NaN,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,NaN,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,NaN,NaN,NaN,NaN,NaN
1066,NaN,0,NaN,NaN,NaN,NaN,NaN
1067,NaN,0,NaN,NaN,NaN,NaN,NaN
1068,NaN,0,NaN,NaN,NaN,NaN,NaN
1069,NaN,0,NaN,NaN,NaN,NaN,NaN

In [60]:
conn_info.dtypes

email            object
mobile_no        object
company_name     object
conn_link        object
conn_name        object
gender          float64
salutation      float64
dtype: object

In [61]:
conn_info = conn_info.astype('category')
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,NaN,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,NaN,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,NaN,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,NaN,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,NaN,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,NaN,NaN,NaN,NaN,NaN
1066,NaN,0,NaN,NaN,NaN,NaN,NaN
1067,NaN,0,NaN,NaN,NaN,NaN,NaN
1068,NaN,0,NaN,NaN,NaN,NaN,NaN
1069,NaN,0,NaN,NaN,NaN,NaN,NaN

In [62]:
conn_info['mobile_no'] == "0"

0        True
1       False
2       False
3        True
4       False
        ...
1065     True
1066     True
1067     True
1068     True
1069     True
Name: mobile_no, Length: 1070, dtype: bool

In [64]:
conn_info['gender'].dtype

CategoricalDtype(categories=[], ordered=False, categories_dtype=float64)

In [65]:
pd.isnull(conn_info['gender'])

0       True
1       True
2       True
3       True
4       True
        ...
1065    True
1066    True
1067    True
1068    True
1069    True
Name: gender, Length: 1070, dtype: bool

In [66]:
conn_info['conn_name'] = conn_info['conn_name'].apply(preprocess)
conn_info.head()

Aaron Penaco
Aaron Santos
Abegail Jean Bañez
Abigail Lyle Arquero
Adrian Joseph
Adriane Valderrama
Aerdan Joseph Lacson
Agot Reyes
Aimeh Grace Nono Lazaro
Airizh Criztal Santos
Aisha Locsin Red
Aishwarya Tanwar
Alecs Rodriguez
Allen Dionio
Allyssa Reyes
Alyssa Bela Ong
Alyssa Christa Cunanan
Alyssa Marie Reyes
Amiel Ayroso
Anabelle Millena
Andrea Jabat
Andrea Mae Austria
Andrea Martinez
Angel Amosin
Angel P. Figueras Lpt
Angelica Bula
Angelica Mamaid
Angelica Marie Wida
Angelica Salandanan
Angelika Barriga
Angelique Benemerito
Angelo Hernandez
Angely May Parel
Anjelica Joice Pantig Amparo
Anjelica Matabalan
Ann Caroline Tablada Domasin
Anna Carmela Macam
Anne Camino
Anthony Autor
Anthony Louissetien Morales
April Pie Tayong
Arbaz Hussain
Arci Glodove
Arden Caparas
Ariane Sampaga
Arianne Amio
Ariel Cole
Arissa Miles Rodriguez
Arra Thea Alagad
Ashley Sadine Djandaghi Bautista
Aubrey Lou Maldonado
Audrea Marie Boto
Ave May Mallari
Az Cabrera Chrp
Baby Jean Arandia
Beverly Hawksworth
Blessilda Catap
Bryan Drexler Azarcon
Calleene Gabe Pascual
Camelle Villarin
Camille Catigay
Camille Eloisa Mendoza
Camille Sunga
Cams Cabungcal
Carla Antonia Montelibano
Carlin Therese Tatad
Carlo Estoconing
Carmelo P. Litanon Ii
Catherine "Khite" Cruz
Catherine Jane Alhambra
Catherine Lavadia
Catherine Santos Magnaye
Celine Anne Buhain
Cess Balbuena
Charisse Ivan De Leon
Charlene Artes
Charles Aquino
Charmaine Joy Quito
Cherry Lou Haluag
Chesca Benito
Chester Symon Fetalcorin
Christabel San Gabriel Andres
Christian Gabriel Villegas
Christian Joseph Garlitos
Christian Mark Boñola
Christine Isip Arci
Christine Mae Linatoc
Christine Marie Mendoza
Christopher Gonzalez
Clarisa Tallada
Clarisse Buenconsejo
Claudine Des
Clyde Luis Tuazon
Colene Joice De Leon
Corinne Supangan
Cristine Valdez
Criza May Beriong
Currie Orpiano
Cyrelle Rongavilla
Daisy Jane Reas
Dale Schofield
Daniel Binos
Daniel Sebastian
Daniella Mae B.
Danielle Dela Cruz
Danniel Tongol
Dariel Latoza
Darille Galleros
Darrel Baliwag
Dea Cinco
Debbie Anne Marie Ebol
Dennis Concepcion
Dhea Pineda
Dianna Marie Platero
Dianne Zaira Pingcas
Doelsie Pagaran Torres
Don King Valdesco
Don Refuerzo
Ed Christian Barrientos
Eddie Jr Bacalla
Eduard Brazil
El Batuna
Elaine Marion Edaño
Elaine Villa Balatero
Elaiza Wileman
Elijah Gabrielle Malicdem
Ella Tariman
Ellaine Jara
Ellaine Villa
Ellen Faye Javier
Ellyka Kischa Williams
Elvin Eligado
Emilyn Alonsagay
Enrisa Lara
Equel N.
Erica Zhang
Ericson Ramos
Erika Ray Ramirez
Ermmellyn May Acupang
Ernell Carl Ampit
Ervic Jerel Japitana
Erwin Roy Lopez
Eunice Bernadette Javier
Eunice Medina
Eunice Pamela Canilang
Evan Jake Soriano Montano
Evangeline Panganiban
Faith Joyce Martinez
Felix Dulatre
Folusho Olaniyan
France Mercado
Francis Sicat
Francoise Bejasa
Frisian Acebo
Fritzie Claire Apale
Gabby Jusoy
Gem Anonuevo
Geraldine Mangune
Gerard Lorenzo Dizer Natividad
Giancarlo Tobias
Giandro Pardilla
Gianne Denise Dueñas
Gillian Cabello Laylo
Glaiza Luna
Glen Kier Garcia Peña
Glenn De Guzman
Grace Inosanto
Hannah Alteza
Hazelle Cenon
Hearthylyn Fiel
Helen Wong
Heljine E. Tusio
Herschel Zamir Laminero
Inez Alexandra Alvarez
Isabelita Wenceslao
Ivee Po
Ivern Bernales
Iza Elaine Rose Ellego
Jace Villamor
Jackie Belmonte
Jade Ancajas
Jaezelle Reyes
Jam Alcampado
James Fernandez
Jamie Jane Quijano Boneo
Jan Laurence Valerio
Jan Marvin Miranda
Jana Kristina Mendoza
Jane Bataan
Janice Alvarez Piastro
Janine Erika Manzala
Janna Tricia Gabriel
Jarrid Anne Remulta
Jay Panilag
Jaya Maia Alcantara
Jayrah Cruzado
Jazeinka Isabella Valdez Pineda
Jc Consuelo
Je Ann Cuerbo
Jealyn Duyag Ibo
Jean Carlo Mozo
Jeanette O
Jema Flor Basilio
Jemel Lovino
Jenn Dioquino Lsswb
Jennelyn Meñoso
Jeramie Jane Roc
Jeremi Anne Ramos
Jessica Galang
Jessicamae Mercado
Jethro Pamintuan
Jevelyn Borjal
Jewely Opon
Jhanina Inotorio
Jherick Sid Celestial
Jhon Remilyn Unciano
Jia Doble
Jiezzete Ignacio
Jijomer Dacoscos
Jill Marian
Joe Anne Donato
Joel Per
Joemari Rios
John Bendix Mendoza
John Carlo Tadeo
John Dominic Ocampo
John Laurence Sarmiento
John Luther Bondoc
John Manicent Codiniera
John Marin Moreno Clsswb
John Paul Pormento
John Paulo Arciaga
John Rodulph Camizola
Jon Axle Perez
Jophil Ann Perlado
Jorge Pitong
Jose Marie Mangalino
Josh Despuig
Joy Marie Villa
Joy Solana
Joyce Ann Calica
Joylyn Agan
Jules Macalalad
Julian Eric Damian
Julio Lecocq Chamorro
Julius Cesar Lomarda
Justin Edward Fernandez
Justin Navarette
Justine Cunanan
Justine Dela Peña
Jv Nebres
Kaiser Antenor
Kako Usi
Kamille Gonzales
Kams Casas Rodriguez
Karen Elysse Ulpindo
Karina Manzanilla
Karl Marx Galado
Karl Monteclaro
Kate Collie Santos
Kathleen Limon
Kathleen Punzalan
Kathlyn Pagdanganan
Kathrine Salvador
Katrina Angela Espiritu
Katt Villapando
Kean Jardin
Kei Bryan Dusaban
Kenn Dominic Macarat
Kennah Bea Cambari
Kenneth Joy Loteyro
Kenneth Ramil
Khea Ronette Noro
Kiara Aldover
Kim An Marie Yap
Kim Elijah Domingo
Kim Ferrer
Kim Loriel Reyes
Kim Villamor
Kimberly Maniti
Kimberly Pineda
Kirsten Effie Ezra Lachica
Kj Chavez
Krissia Geramie Mapatac
Kristelle Ann Villalobos
Kristia C.
Kristian Riz Canama
Kristine Castilla
Kristine Obsioma
Krystel Flores
Kryzel Ann Oja
Kyla Lalaine Hugo
Kyle Christopher Atilano
Kyle Maverick Schaefer
Kyra Marco Luicco De Ynchausti
Lancel Jhon Aris Foster
Lawrence Gatpandan
Leila Isabel Villamor
Lerry Aquino
Leslie Saspa
Lester Lacsina
Liana Rosette Ramos
Lisette Jane Lumberio
Lorena Baez
Lorenzo Depone Ii
Lorie Loguenario
Lorraine Jean Sequina
Louise Lozano
Louisze Jhaede Sanchez
Lovely Lamptey
Lyndon Ramo Jr
Ma. Angela Lozada
Ma. Carmela De Juan
Ma. Joyce Armia
Ma. Katrina Gracia Sedanto
Ma. Stephanie Nicole Lim
Mac Gilfred Uy
Mae Dionson
Mae Mira
Marc Daniel Melotindos
Marco Caspillan
Marcus Paulino
Marga Bonilla
Maria Christinapaz Parker
Maria Ignacia Quesada
Maria Katrina Cuenca
Maria Katrina Guiñares
Maria Zarina Antonio
Mariah Cristine Tamayo
Marianne Diocares
Maricar B.
Maricris Cenal
Marielle Toribio
Mariko Miranda
Marjorie Fonseca
Mark Aldrin Cose
Mark Elliah M. Sanchez
Mark Kevin Garcia
Marlon De Mesa
Martin Aguilar
Marvin Victoria
Mary Andrea Jugo
Mary Bernalyn Therese Ignacio
Mary Claire Cabanda
Mary Diane Alcala
Mary Grace Munoz
Mary Joy Antoc
Mary Joyce Avendano
Mary Nole Hazel Padagdag
Matthew De Catalina
Maurich Macatangay
Mayca Merencillo
Megan Rivera
Meliza Anne Kionisala
Melvin Peralta
Mia Alcantara
Mica Joy Remoquillo
Micah Viado
Mich Cendaña
Mico Louis Mañalac
Miggy Garcia
Miguel Arceo
Mikael John Paras
Mikaela Leigh Padrelanan
Mikee Torre
Mikhaela Malabanan
Moira Abesamis
Nadeth Marquez
Nadine Lacsamana
Nathaniel Sevilla
Neil Andrew Ynacis
Nemuel Pamplona
Nic Golipapa
Nicole Algire Demonteverde
Nicole Limbo
Nikka Faola Valle
Nilfe Mae Sumagaysay
Nina Cababa
Nirica Kathleen Mavotas
Noelle Barcenas
Nomer Calara
Nowrine Shiena Hossen
Oliver Gabuna
Oliver Sison
Pam Rico Map Cand.
Pamela Pamonag
Paolo Parayno
Patricia Berenguel
Patricia Marie Bobadilla
Patrick Malibunas
Patrixia Punzalan
Paul Gromglieng Grom Li Yeng
Paula Patricia Valentin
Paulene Hazelen Gornes
Paulo Gutierrez
Pearl D
Peejay Adlawon
Philip Mercado
Pol Tahoynon
Prince Angelo Torres
Princess Macatuggal
Princess Miñon
Princess Yobel Domingo
Quecel Therese Ordaniel
Quincy Erika Ramos
Rachelle Suico
Racquel Abadiez
Rafael Ryan Lloren
Raffy Jay Villapaña
Ragin Marie Baytan
Rain Acuesta Chrp
Ralph Marwin Loyola
Randy Marjalino
Raphael Bacaling
Raphael Ventura
Rebekah Mabaet
Reggielee Capio
Regine Calibay
Regine Orozco
Reina Yago
Reiner Arcilla
Remegio Madarang Jr
Rence Maynes
Renel Tibo
Renz Martinez
Renzcy Mendoza
Renzo Reyes
Reselyn Jane Alonzo
Revin Aves Naing
Rhuff Danica Gambong
Ricaport Casanayan
Rich Moscoso
Ricky Beatriz Agbanlog
Riza Fortunato
Rizamae Milet Austria
Rizamelle Estil
Rizza Villanueva
Rizziane Frago
Robert Jethro Enriquez
Rochelle Miguela Angeles
Rodalyn Orale
Rodella "Leng" Tolentino
Rodolfo Cantongos
Roma Doria Panaligan
Rome Benedicto
Ron Rachelle Catuiran
Ronald Ramas
Rory Rm
Roselle Allison Santiago
Roselyn Achas
Rosh Joseph Gador
Rosmel Oropesa
Ruel Casane
Russell Rogan
Ruzzel Coronado Clsswb
Ry Lope
Ryan Taboada
Rychelle Himongala
Rye Dizon
Ryssel Joy Tumayan
Samantha Gayle Lee
Sarah Jane Padayao
Sarah Mendoza
Sarrah Dulguime
Scott Vincent Nacua
Sheena Lee
Shekinah Cuevas
Shermie Louize Bryan Herrera
Shiena Saballo
Shierlyn Curitana Panlilio
Shirly Ann Larroder
Siara Sangalang
Simon Kim Hirondo
Sophia Mizon
Stefhanie Sapeda
Stephanie Anne Mariano
Stephany Orjuela
Tania Bondoc
Tedz Ligtvoet
Tel Cadiang
Teresa Hastings
Thea Martinez
Therisa May Bagona
Tin Salmurin
Tina Caluya
Tine Kris
Toni Monreal
Tonichi Lamsen
Tracy Gregore
Trexx Gan
Trisha Mae Borral
Trisha Marie Flores
Tristan Jerick Reyes
Via Lhiz Cecille Romualdez
Via Margaret Bumatayo
Vic Angelo Flores
Vin Escalante
Vin Mendoza
Vincent Dan Mijares
Vincent Trovela
Von Christian Saret
Yasmin Tubice
Ynah Serrano
Yuih Salvador
Yvette Lacson
Zaira Cadampog
Zedrick Ross Paz
Zen Athena Magdasoc
Zion Resurreccion

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,NaN,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,NaN,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,NaN,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,NaN,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,NaN,NaN

In [67]:
view_rows(conn_info, 'conn_name')

Marcus Paulino
Jherick Sid Celestial
Evan Jake Soriano Montano
Reggielee Capio
John Carlo Tadeo
Lorenzo Depone Ii
Jaya Maia Alcantara
Jan Laurence Valerio
Kimberly Pineda
nan
nan
Moira Abesamis
Rafael Ryan Lloren
Aishwarya Tanwar
Lerry Aquino
Camelle Villarin
Jules Macalalad
Bryan Drexler Azarcon
Christine Marie Mendoza
Nadine Lacsamana
Alecs Rodriguez
Gianne Denise Dueñas
Camille Eloisa Mendoza
Airizh Criztal Santos
Ericson Ramos
Felix Dulatre
Aaron Santos
Herschel Zamir Laminero
Corinne Supangan
Kathlyn Pagdanganan
Trisha Mae Borral
Noelle Barcenas
Ma. Angela Lozada
Vincent Dan Mijares
Kyle Christopher Atilano
Jhanina Inotorio
Giancarlo Tobias
nan
John Paul Pormento
Hazelle Cenon
Anne Camino
Arbaz Hussain
John Manicent Codiniera
Mia Alcantara
Allen Dionio
Erica Zhang
nan
Kenneth Joy Loteyro
Riza Fortunato
Aisha Locsin Red
Tedz Ligtvoet
Chesca Benito
Iza Elaine Rose Ellego
Kim Ferrer
Amiel Ayroso
Nicole Algire Demonteverde
Joy Marie Villa
Janna Tricia Gabriel
Ruzzel Coronado Clsswb
Ma. Stephanie Nicole Lim
nan
Tania Bondoc
Adriane Valderrama
Khea Ronette Noro
Kyla Lalaine Hugo
Kyra Marco Luicco De Ynchausti
France Mercado
Gabby Jusoy
Jethro Pamintuan
Inez Alexandra Alvarez
Rychelle Himongala
Ann Caroline Tablada Domasin
John Rodulph Camizola
nan
Paulo Gutierrez
Angelique Benemerito
Jenn Dioquino Lsswb
Eunice Medina
Alyssa Marie Reyes
Regine Orozco
Andrea Martinez
Agot Reyes
Rizza Villanueva
Maricris Cenal
Philip Mercado
Raphael Bacaling
Nirica Kathleen Mavotas
Ellen Faye Javier
Nicole Limbo
Nikka Faola Valle
Peejay Adlawon
Roselle Allison Santiago
Lorraine Jean Sequina
Scott Vincent Nacua
Kim Elijah Domingo
Paolo Parayno
Jean Carlo Mozo
Martin Aguilar
Jevelyn Borjal
Nemuel Pamplona
Randy Marjalino
nan
Isabelita Wenceslao
Francoise Bejasa
Zion Resurreccion
Chester Symon Fetalcorin
Evangeline Panganiban
Ermmellyn May Acupang
Daniel Sebastian
Heljine E. Tusio
Teresa Hastings
Gillian Cabello Laylo
Pearl D
Nilfe Mae Sumagaysay
Kaiser Antenor
Katt Villapando
Jophil Ann Perlado
nan
Jewely Opon
Angelica Bula
Nathaniel Sevilla
Catherine "Khite" Cruz
Kathleen Punzalan
Reina Yago
Ragin Marie Baytan
Maria Ignacia Quesada
Sarah Jane Padayao
Ellyka Kischa Williams
Jam Alcampado
Francis Sicat
Ruel Casane
Arden Caparas
Toni Monreal
Criza May Beriong
Angel P. Figueras Lpt
Mica Joy Remoquillo
John Luther Bondoc
Danielle Dela Cruz
Aimeh Grace Nono Lazaro
Doelsie Pagaran Torres
Karen Elysse Ulpindo
Jaezelle Reyes
Marvin Victoria
Daisy Jane Reas
Sheena Lee
Calleene Gabe Pascual
Fritzie Claire Apale
Maurich Macatangay
Aaron Penaco
Anjelica Matabalan
Melvin Peralta
Jia Doble
Nina Cababa
Arianne Amio
Ivee Po
Cyrelle Rongavilla
Rhuff Danica Gambong
Vin Mendoza
Arci Glodove
Reiner Arcilla
Paula Patricia Valentin
Geraldine Mangune
Charles Aquino
Jon Axle Perez
Shierlyn Curitana Panlilio
nan
Julius Cesar Lomarda
Rich Moscoso
Nadeth Marquez
Von Christian Saret
Andrea Mae Austria
Mark Aldrin Cose
Tracy Gregore
Justin Navarette
nan
Tonichi Lamsen
Ernell Carl Ampit
Mariko Miranda
Beverly Hawksworth
Carlin Therese Tatad
Clyde Luis Tuazon
Daniel Binos
Kathleen Limon
Rye Dizon
Renzo Reyes
Nic Golipapa
Faith Joyce Martinez
Jijomer Dacoscos
Mico Louis Mañalac
Renzcy Mendoza
Darille Galleros
Lancel Jhon Aris Foster
Julio Lecocq Chamorro
Anthony Autor
Mary Nole Hazel Padagdag
Angelo Hernandez
Kirsten Effie Ezra Lachica
Joyce Ann Calica
Samantha Gayle Lee
Glen Kier Garcia Peña
Marielle Toribio
Louise Lozano
Kim An Marie Yap
Pam Rico Map Cand.
Sarah Mendoza
Joe Anne Donato
Eddie Jr Bacalla
Jiezzete Ignacio
nan
Mary Diane Alcala
Ricky Beatriz Agbanlog
Glaiza Luna
Jc Consuelo
Mich Cendaña
Therisa May Bagona
Alyssa Bela Ong
Darrel Baliwag
Andrea Jabat
Erwin Roy Lopez
Debbie Anne Marie Ebol
Frisian Acebo
nan
Ellaine Villa
Celine Anne Buhain
Dianne Zaira Pingcas
Jane Bataan
Via Lhiz Cecille Romualdez
Joel Per
Jeremi Anne Ramos
Mary Bernalyn Therese Ignacio
Stephany Orjuela
Vincent Trovela
Grace Inosanto
Eunice Bernadette Javier
Patricia Marie Bobadilla
Hearthylyn Fiel
Catherine Santos Magnaye
Zedrick Ross Paz
Elijah Gabrielle Malicdem
Vic Angelo Flores
Mary Joy Antoc
Claudine Des
Jarrid Anne Remulta
Jana Kristina Mendoza
Dennis Concepcion
Liana Rosette Ramos
Mae Dionson
Thea Martinez
Kim Loriel Reyes
Ervic Jerel Japitana
Rizamelle Estil
Kathrine Salvador
Ed Christian Barrientos
Ron Rachelle Catuiran
Clarisa Tallada
Charmaine Joy Quito
Eduard Brazil
Jay Panilag
Miggy Garcia
Mark Elliah M. Sanchez
Paul Gromglieng Grom Li Yeng
Aerdan Joseph Lacson
Jennelyn Meñoso
Ma. Carmela De Juan
Racquel Abadiez
James Fernandez
Dariel Latoza
Mary Joyce Avendano
Ave May Mallari
Carla Antonia Montelibano
Micah Viado
Alyssa Christa Cunanan
Marga Bonilla
Allyssa Reyes
Charlene Artes
Raffy Jay Villapaña
Matthew De Catalina
Adrian Joseph
Mikael John Paras
Mariah Cristine Tamayo
Camille Sunga
Camille Sunga
Quecel Therese Ordaniel
Je Ann Cuerbo
Daniella Mae B.
Miguel Arceo
Vin Escalante
Josh Despuig
Rachelle Suico
Janice Alvarez Piastro
Kennah Bea Cambari
Kimberly Maniti
Jeramie Jane Roc
nan
Lester Lacsina
Maria Katrina Guiñares
Rome Benedicto
Rebekah Mabaet
Kim Villamor
Ariane Sampaga
Jealyn Duyag Ibo
Ryan Taboada
Nomer Calara
Don King Valdesco
Mayca Merencillo
nan
Christine Isip Arci
Rence Maynes
Via Margaret Bumatayo
Yuih Salvador
Marc Daniel Melotindos
nan
Stephanie Anne Mariano
Jessicamae Mercado
Catherine Jane Alhambra
Rory Rm
Ellaine Jara
Ronald Ramas
Mary Claire Cabanda
Lorie Loguenario
Princess Macatuggal
Princess Yobel Domingo
Jeanette O
Patrixia Punzalan
Rosmel Oropesa
Shekinah Cuevas
Dale Schofield
nan
Renz Martinez
Shermie Louize Bryan Herrera
Shirly Ann Larroder
Patricia Berenguel
Ricaport Casanayan
Neil Andrew Ynacis
Cristine Valdez
Folusho Olaniyan
Christabel San Gabriel Andres
Jan Marvin Miranda
Ry Lope
Yasmin Tubice
Krystel Flores
Gerard Lorenzo Dizer Natividad
Ynah Serrano
nan
Rosh Joseph Gador
Ivern Bernales
Giandro Pardilla
Dea Cinco
Christian Mark Boñola
John Paulo Arciaga
Arra Thea Alagad
Kj Chavez
nan
Dianna Marie Platero
Cams Cabungcal
Danniel Tongol
Kristia C.
Lorena Baez
Roma Doria Panaligan
nan
Jose Marie Mangalino
Christopher Gonzalez
Rodella "Leng" Tolentino
John Marin Moreno Clsswb
Ma. Joyce Armia
Jemel Lovino
Elaine Marion Edaño
Renel Tibo
Regine Calibay
Kams Casas Rodriguez
Gem Anonuevo
Lisette Jane Lumberio
Aubrey Lou Maldonado
Maria Zarina Antonio
Ella Tariman
Audrea Marie Boto
Baby Jean Arandia
Abegail Jean Bañez
Jill Marian
John Dominic Ocampo
Oliver Sison
Jessica Galang
Kiara Aldover
Ariel Cole
Rodolfo Cantongos
Kei Bryan Dusaban
Krissia Geramie Mapatac
Reselyn Jane Alonzo
nan
Colene Joice De Leon
Siara Sangalang
Eunice Pamela Canilang
Karl Monteclaro
Catherine Lavadia
Anna Carmela Macam
Lovely Lamptey
Elvin Eligado
Janine Erika Manzala
Sarrah Dulguime
Zaira Cadampog
Jema Flor Basilio
Elaiza Wileman
Kean Jardin
Kenneth Ramil
Camille Catigay
nan
Zen Athena Magdasoc
nan
Jazeinka Isabella Valdez Pineda
Ma. Katrina Gracia Sedanto
El Batuna
Mark Kevin Garcia
Arissa Miles Rodriguez
Quincy Erika Ramos
Marco Caspillan
Lawrence Gatpandan
Anabelle Millena
Leila Isabel Villamor
Charisse Ivan De Leon
Raphael Ventura
Joylyn Agan
Rodalyn Orale
Tine Kris
Mac Gilfred Uy
Christine Mae Linatoc
Jackie Belmonte
Julian Eric Damian
Robert Jethro Enriquez
Mikaela Leigh Padrelanan
Jhon Remilyn Unciano
Jamie Jane Quijano Boneo
Prince Angelo Torres
Roselyn Achas
nan
nan
Enrisa Lara
Jade Ancajas
Currie Orpiano
Anjelica Joice Pantig Amparo
Marlon De Mesa
nan
Tin Salmurin
Russell Rogan
Karl Marx Galado
Mikee Torre
Kate Collie Santos
Trexx Gan
Az Cabrera Chrp
John Bendix Mendoza
Rain Acuesta Chrp
Ashley Sadine Djandaghi Bautista
Nowrine Shiena Hossen
nan
Carlo Estoconing
Simon Kim Hirondo
Carmelo P. Litanon Ii
Kako Usi
nan
Justine Cunanan
Jorge Pitong
Cherry Lou Haluag
Tristan Jerick Reyes
Patrick Malibunas
Cess Balbuena
Maria Christinapaz Parker
Don Refuerzo
Glenn De Guzman
Jv Nebres
Pol Tahoynon
Justin Edward Fernandez
John Laurence Sarmiento
nan
nan
Christian Joseph Garlitos
nan
nan
Paulene Hazelen Gornes
nan
Marianne Diocares
Louisze Jhaede Sanchez
Ryssel Joy Tumayan
April Pie Tayong
Revin Aves Naing
Kenn Dominic Macarat
Erika Ray Ramirez
Angelica Salandanan
Remegio Madarang Jr
Meliza Anne Kionisala
Pamela Pamonag
Ralph Marwin Loyola
Emilyn Alonsagay
Jayrah Cruzado
Helen Wong
Clarisse Buenconsejo
Sophia Mizon
Angelica Mamaid
Blessilda Catap
Equel N.
Kryzel Ann Oja
Princess Miñon
Justine Dela Peña
Christian Gabriel Villegas
Kyle Maverick Schaefer
Maricar B.
Kamille Gonzales
Joy Solana
Hannah Alteza
Anthony Louissetien Morales
Marjorie Fonseca
Rochelle Miguela Angeles
Mikhaela Malabanan
Rizamae Milet Austria
Tel Cadiang
Trisha Marie Flores
Jace Villamor
Abigail Lyle Arquero
Mary Grace Munoz
Stefhanie Sapeda
Shiena Saballo
Maria Katrina Cuenca
Yvette Lacson
Katrina Angela Espiritu
nan
Kristian Riz Canama
Lyndon Ramo Jr
Leslie Saspa
Kristine Castilla
Rizziane Frago
Angelica Marie Wida
Tina Caluya
Elaine Villa Balatero
Kristelle Ann Villalobos
Angel Amosin
Angely May Parel
Dhea Pineda
Karina Manzanilla
Kristine Obsioma
Joemari Rios
Angelika Barriga
nan
nan
Oliver Gabuna
Mae Mira
Megan Rivera
Mary Andrea Jugo
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan